// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package parkingdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ParkingSpace struct {
	ID          pgtype.UUID
	Code        string
	Type        string
	StructureID pgtype.UUID
	Level       *string
	Zone        *string
	MonthlyFee  pgtype.Numeric
	IsVisitor   bool
	Notes       *string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
}

type ParkingAssignment struct {
	ID               pgtype.UUID
	ParkingSpaceID   pgtype.UUID
	UnitID           pgtype.UUID
	VehicleID        pgtype.UUID
	AssignedByUserID pgtype.UUID
	SinceDate        pgtype.Date
	UntilDate        pgtype.Date
	Notes            *string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
	DeletedBy        pgtype.UUID
	Version          int32
}

type ParkingAssignmentHistory struct {
	ID              pgtype.UUID
	ParkingSpaceID  pgtype.UUID
	UnitID          pgtype.UUID
	AssignmentID    pgtype.UUID
	SinceDate       pgtype.Date
	UntilDate       pgtype.Date
	ClosedReason    *string
	SnapshotPayload []byte
	RecordedAt      pgtype.Timestamptz
	RecordedBy      pgtype.UUID
}

type ParkingVisitorReservation struct {
	ID              pgtype.UUID
	ParkingSpaceID  pgtype.UUID
	UnitID          pgtype.UUID
	RequestedBy     pgtype.UUID
	VisitorName     string
	VisitorDocument *string
	VehiclePlate    *string
	SlotStartAt     pgtype.Timestamptz
	SlotEndAt       pgtype.Timestamptz
	IdempotencyKey  *string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	UpdatedBy       pgtype.UUID
	DeletedBy       pgtype.UUID
	Version         int32
}

type ParkingLotteryRun struct {
	ID         pgtype.UUID
	Name       string
	SeedHash   string
	Criteria   []byte
	ExecutedAt pgtype.Timestamptz
	ExecutedBy pgtype.UUID
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedBy  pgtype.UUID
	DeletedBy  pgtype.UUID
	Version    int32
}

type ParkingLotteryResult struct {
	ID             pgtype.UUID
	LotteryRunID   pgtype.UUID
	UnitID         pgtype.UUID
	ParkingSpaceID pgtype.UUID
	Position       int32
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	UpdatedBy      pgtype.UUID
	DeletedBy      pgtype.UUID
	Version        int32
}

type ParkingOutboxEvent struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
	Attempts      int32
	DeliveredAt   pgtype.Timestamptz
	LastError     *string
}
