// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parking.sql

package parkingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ---------------------------------------------------------------------------
// parking_spaces
// ---------------------------------------------------------------------------

const createParkingSpace = `-- name: CreateParkingSpace :one
INSERT INTO parking_spaces (
    code, type, structure_id, level, zone, monthly_fee,
    is_visitor, notes, status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'active', $9, $9
)
RETURNING id, code, type, structure_id, level, zone, monthly_fee,
          is_visitor, notes, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateParkingSpaceParams struct {
	Code        string
	Type        string
	StructureID pgtype.UUID
	Level       *string
	Zone        *string
	MonthlyFee  pgtype.Numeric
	IsVisitor   bool
	Notes       *string
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreateParkingSpace(ctx context.Context, arg CreateParkingSpaceParams) (ParkingSpace, error) {
	row := q.db.QueryRow(ctx, createParkingSpace,
		arg.Code, arg.Type, arg.StructureID,
		arg.Level, arg.Zone, arg.MonthlyFee,
		arg.IsVisitor, arg.Notes, arg.CreatedBy,
	)
	var i ParkingSpace
	err := row.Scan(
		&i.ID, &i.Code, &i.Type, &i.StructureID,
		&i.Level, &i.Zone, &i.MonthlyFee,
		&i.IsVisitor, &i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getParkingSpaceByID = `-- name: GetParkingSpaceByID :one
SELECT id, code, type, structure_id, level, zone, monthly_fee,
       is_visitor, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_spaces
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetParkingSpaceByID(ctx context.Context, id pgtype.UUID) (ParkingSpace, error) {
	row := q.db.QueryRow(ctx, getParkingSpaceByID, id)
	var i ParkingSpace
	err := row.Scan(
		&i.ID, &i.Code, &i.Type, &i.StructureID,
		&i.Level, &i.Zone, &i.MonthlyFee,
		&i.IsVisitor, &i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getParkingSpaceByCode = `-- name: GetParkingSpaceByCode :one
SELECT id, code, type, structure_id, level, zone, monthly_fee,
       is_visitor, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_spaces
 WHERE code = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetParkingSpaceByCode(ctx context.Context, code string) (ParkingSpace, error) {
	row := q.db.QueryRow(ctx, getParkingSpaceByCode, code)
	var i ParkingSpace
	err := row.Scan(
		&i.ID, &i.Code, &i.Type, &i.StructureID,
		&i.Level, &i.Zone, &i.MonthlyFee,
		&i.IsVisitor, &i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listParkingSpaces = `-- name: ListParkingSpaces :many
SELECT id, code, type, structure_id, level, zone, monthly_fee,
       is_visitor, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_spaces
 WHERE deleted_at IS NULL
 ORDER BY code ASC
`

func (q *Queries) ListParkingSpaces(ctx context.Context) ([]ParkingSpace, error) {
	rows, err := q.db.Query(ctx, listParkingSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingSpace{}
	for rows.Next() {
		var i ParkingSpace
		if err := rows.Scan(
			&i.ID, &i.Code, &i.Type, &i.StructureID,
			&i.Level, &i.Zone, &i.MonthlyFee,
			&i.IsVisitor, &i.Notes, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParkingSpace = `-- name: UpdateParkingSpace :one
UPDATE parking_spaces
   SET code         = $1,
       type         = $2,
       structure_id = $3,
       level        = $4,
       zone         = $5,
       monthly_fee  = $6,
       is_visitor   = $7,
       notes        = $8,
       status       = $9,
       updated_at   = now(),
       updated_by   = $10,
       version      = version + 1
 WHERE id = $11
   AND version = $12
   AND deleted_at IS NULL
RETURNING id, code, type, structure_id, level, zone, monthly_fee,
          is_visitor, notes, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdateParkingSpaceParams struct {
	NewCode         string
	NewType         string
	NewStructureID  pgtype.UUID
	NewLevel        *string
	NewZone         *string
	NewMonthlyFee   pgtype.Numeric
	NewIsVisitor    bool
	NewNotes        *string
	NewStatus       string
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateParkingSpace(ctx context.Context, arg UpdateParkingSpaceParams) (ParkingSpace, error) {
	row := q.db.QueryRow(ctx, updateParkingSpace,
		arg.NewCode, arg.NewType, arg.NewStructureID,
		arg.NewLevel, arg.NewZone, arg.NewMonthlyFee,
		arg.NewIsVisitor, arg.NewNotes, arg.NewStatus,
		arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i ParkingSpace
	err := row.Scan(
		&i.ID, &i.Code, &i.Type, &i.StructureID,
		&i.Level, &i.Zone, &i.MonthlyFee,
		&i.IsVisitor, &i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const softDeleteParkingSpace = `-- name: SoftDeleteParkingSpace :exec
UPDATE parking_spaces
   SET deleted_at  = now(),
       deleted_by  = $1,
       updated_at  = now(),
       updated_by  = $1,
       version     = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
`

type SoftDeleteParkingSpaceParams struct {
	DeletedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SoftDeleteParkingSpace(ctx context.Context, arg SoftDeleteParkingSpaceParams) error {
	_, err := q.db.Exec(ctx, softDeleteParkingSpace, arg.DeletedBy, arg.ID, arg.ExpectedVersion)
	return err
}

// ---------------------------------------------------------------------------
// parking_assignments
// ---------------------------------------------------------------------------

const createParkingAssignment = `-- name: CreateParkingAssignment :one
INSERT INTO parking_assignments (
    parking_space_id, unit_id, vehicle_id, assigned_by_user_id,
    since_date, notes, status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, 'active', $4, $4
)
RETURNING id, parking_space_id, unit_id, vehicle_id, assigned_by_user_id,
          since_date, until_date, notes, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateParkingAssignmentParams struct {
	ParkingSpaceID   pgtype.UUID
	UnitID           pgtype.UUID
	VehicleID        pgtype.UUID
	AssignedByUserID pgtype.UUID
	SinceDate        pgtype.Date
	Notes            *string
}

func (q *Queries) CreateParkingAssignment(ctx context.Context, arg CreateParkingAssignmentParams) (ParkingAssignment, error) {
	row := q.db.QueryRow(ctx, createParkingAssignment,
		arg.ParkingSpaceID, arg.UnitID, arg.VehicleID,
		arg.AssignedByUserID, arg.SinceDate, arg.Notes,
	)
	var i ParkingAssignment
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.VehicleID,
		&i.AssignedByUserID, &i.SinceDate, &i.UntilDate,
		&i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getParkingAssignmentByID = `-- name: GetParkingAssignmentByID :one
SELECT id, parking_space_id, unit_id, vehicle_id, assigned_by_user_id,
       since_date, until_date, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_assignments
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetParkingAssignmentByID(ctx context.Context, id pgtype.UUID) (ParkingAssignment, error) {
	row := q.db.QueryRow(ctx, getParkingAssignmentByID, id)
	var i ParkingAssignment
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.VehicleID,
		&i.AssignedByUserID, &i.SinceDate, &i.UntilDate,
		&i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getActiveAssignmentBySpaceID = `-- name: GetActiveAssignmentBySpaceID :one
SELECT id, parking_space_id, unit_id, vehicle_id, assigned_by_user_id,
       since_date, until_date, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_assignments
 WHERE parking_space_id = $1
   AND until_date IS NULL
   AND deleted_at IS NULL
 LIMIT 1
`

func (q *Queries) GetActiveAssignmentBySpaceID(ctx context.Context, parkingSpaceID pgtype.UUID) (ParkingAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveAssignmentBySpaceID, parkingSpaceID)
	var i ParkingAssignment
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.VehicleID,
		&i.AssignedByUserID, &i.SinceDate, &i.UntilDate,
		&i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listActiveAssignmentsByUnitID = `-- name: ListActiveAssignmentsByUnitID :many
SELECT id, parking_space_id, unit_id, vehicle_id, assigned_by_user_id,
       since_date, until_date, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_assignments
 WHERE unit_id = $1
   AND until_date IS NULL
   AND deleted_at IS NULL
 ORDER BY since_date DESC
`

func (q *Queries) ListActiveAssignmentsByUnitID(ctx context.Context, unitID pgtype.UUID) ([]ParkingAssignment, error) {
	rows, err := q.db.Query(ctx, listActiveAssignmentsByUnitID, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingAssignment{}
	for rows.Next() {
		var i ParkingAssignment
		if err := rows.Scan(
			&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.VehicleID,
			&i.AssignedByUserID, &i.SinceDate, &i.UntilDate,
			&i.Notes, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsBySpaceID = `-- name: ListAssignmentsBySpaceID :many
SELECT id, parking_space_id, unit_id, vehicle_id, assigned_by_user_id,
       since_date, until_date, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_assignments
 WHERE parking_space_id = $1
   AND deleted_at IS NULL
 ORDER BY since_date DESC
`

func (q *Queries) ListAssignmentsBySpaceID(ctx context.Context, parkingSpaceID pgtype.UUID) ([]ParkingAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsBySpaceID, parkingSpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingAssignment{}
	for rows.Next() {
		var i ParkingAssignment
		if err := rows.Scan(
			&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.VehicleID,
			&i.AssignedByUserID, &i.SinceDate, &i.UntilDate,
			&i.Notes, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeAssignment = `-- name: CloseAssignment :one
UPDATE parking_assignments
   SET until_date  = $1,
       status      = 'closed',
       updated_at  = now(),
       updated_by  = $2,
       version     = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, parking_space_id, unit_id, vehicle_id, assigned_by_user_id,
          since_date, until_date, notes, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CloseAssignmentParams struct {
	UntilDate       pgtype.Date
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) CloseAssignment(ctx context.Context, arg CloseAssignmentParams) (ParkingAssignment, error) {
	row := q.db.QueryRow(ctx, closeAssignment,
		arg.UntilDate, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i ParkingAssignment
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.VehicleID,
		&i.AssignedByUserID, &i.SinceDate, &i.UntilDate,
		&i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const softDeleteAssignment = `-- name: SoftDeleteAssignment :exec
UPDATE parking_assignments
   SET deleted_at  = now(),
       deleted_by  = $1,
       updated_at  = now(),
       updated_by  = $1,
       version     = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
`

type SoftDeleteAssignmentParams struct {
	DeletedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SoftDeleteAssignment(ctx context.Context, arg SoftDeleteAssignmentParams) error {
	_, err := q.db.Exec(ctx, softDeleteAssignment, arg.DeletedBy, arg.ID, arg.ExpectedVersion)
	return err
}

// ---------------------------------------------------------------------------
// parking_assignment_history
// ---------------------------------------------------------------------------

const recordAssignmentHistory = `-- name: RecordAssignmentHistory :one
INSERT INTO parking_assignment_history (
    parking_space_id, unit_id, assignment_id,
    since_date, until_date, closed_reason,
    snapshot_payload, recorded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, parking_space_id, unit_id, assignment_id,
          since_date, until_date, closed_reason,
          snapshot_payload, recorded_at, recorded_by
`

type RecordAssignmentHistoryParams struct {
	ParkingSpaceID  pgtype.UUID
	UnitID          pgtype.UUID
	AssignmentID    pgtype.UUID
	SinceDate       pgtype.Date
	UntilDate       pgtype.Date
	ClosedReason    *string
	SnapshotPayload []byte
	RecordedBy      pgtype.UUID
}

func (q *Queries) RecordAssignmentHistory(ctx context.Context, arg RecordAssignmentHistoryParams) (ParkingAssignmentHistory, error) {
	row := q.db.QueryRow(ctx, recordAssignmentHistory,
		arg.ParkingSpaceID, arg.UnitID, arg.AssignmentID,
		arg.SinceDate, arg.UntilDate, arg.ClosedReason,
		arg.SnapshotPayload, arg.RecordedBy,
	)
	var i ParkingAssignmentHistory
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.AssignmentID,
		&i.SinceDate, &i.UntilDate, &i.ClosedReason,
		&i.SnapshotPayload, &i.RecordedAt, &i.RecordedBy,
	)
	return i, err
}

const listAssignmentHistoryBySpaceID = `-- name: ListAssignmentHistoryBySpaceID :many
SELECT id, parking_space_id, unit_id, assignment_id,
       since_date, until_date, closed_reason,
       snapshot_payload, recorded_at, recorded_by
  FROM parking_assignment_history
 WHERE parking_space_id = $1
 ORDER BY recorded_at DESC
`

func (q *Queries) ListAssignmentHistoryBySpaceID(ctx context.Context, parkingSpaceID pgtype.UUID) ([]ParkingAssignmentHistory, error) {
	rows, err := q.db.Query(ctx, listAssignmentHistoryBySpaceID, parkingSpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingAssignmentHistory{}
	for rows.Next() {
		var i ParkingAssignmentHistory
		if err := rows.Scan(
			&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.AssignmentID,
			&i.SinceDate, &i.UntilDate, &i.ClosedReason,
			&i.SnapshotPayload, &i.RecordedAt, &i.RecordedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentHistoryByUnitID = `-- name: ListAssignmentHistoryByUnitID :many
SELECT id, parking_space_id, unit_id, assignment_id,
       since_date, until_date, closed_reason,
       snapshot_payload, recorded_at, recorded_by
  FROM parking_assignment_history
 WHERE unit_id = $1
 ORDER BY recorded_at DESC
`

func (q *Queries) ListAssignmentHistoryByUnitID(ctx context.Context, unitID pgtype.UUID) ([]ParkingAssignmentHistory, error) {
	rows, err := q.db.Query(ctx, listAssignmentHistoryByUnitID, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingAssignmentHistory{}
	for rows.Next() {
		var i ParkingAssignmentHistory
		if err := rows.Scan(
			&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.AssignmentID,
			&i.SinceDate, &i.UntilDate, &i.ClosedReason,
			&i.SnapshotPayload, &i.RecordedAt, &i.RecordedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ---------------------------------------------------------------------------
// parking_visitor_reservations
// ---------------------------------------------------------------------------

const createVisitorReservation = `-- name: CreateVisitorReservation :one
INSERT INTO parking_visitor_reservations (
    parking_space_id, unit_id, requested_by,
    visitor_name, visitor_document, vehicle_plate,
    slot_start_at, slot_end_at, idempotency_key,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    'confirmed', $3, $3
)
RETURNING id, parking_space_id, unit_id, requested_by,
          visitor_name, visitor_document, vehicle_plate,
          slot_start_at, slot_end_at, idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateVisitorReservationParams struct {
	ParkingSpaceID  pgtype.UUID
	UnitID          pgtype.UUID
	RequestedBy     pgtype.UUID
	VisitorName     string
	VisitorDocument *string
	VehiclePlate    *string
	SlotStartAt     pgtype.Timestamptz
	SlotEndAt       pgtype.Timestamptz
	IdempotencyKey  *string
}

func (q *Queries) CreateVisitorReservation(ctx context.Context, arg CreateVisitorReservationParams) (ParkingVisitorReservation, error) {
	row := q.db.QueryRow(ctx, createVisitorReservation,
		arg.ParkingSpaceID, arg.UnitID, arg.RequestedBy,
		arg.VisitorName, arg.VisitorDocument, arg.VehiclePlate,
		arg.SlotStartAt, arg.SlotEndAt, arg.IdempotencyKey,
	)
	var i ParkingVisitorReservation
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.RequestedBy,
		&i.VisitorName, &i.VisitorDocument, &i.VehiclePlate,
		&i.SlotStartAt, &i.SlotEndAt, &i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getVisitorReservationByID = `-- name: GetVisitorReservationByID :one
SELECT id, parking_space_id, unit_id, requested_by,
       visitor_name, visitor_document, vehicle_plate,
       slot_start_at, slot_end_at, idempotency_key, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_visitor_reservations
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetVisitorReservationByID(ctx context.Context, id pgtype.UUID) (ParkingVisitorReservation, error) {
	row := q.db.QueryRow(ctx, getVisitorReservationByID, id)
	var i ParkingVisitorReservation
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.RequestedBy,
		&i.VisitorName, &i.VisitorDocument, &i.VehiclePlate,
		&i.SlotStartAt, &i.SlotEndAt, &i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getVisitorReservationByIdempotencyKey = `-- name: GetVisitorReservationByIdempotencyKey :one
SELECT id, parking_space_id, unit_id, requested_by,
       visitor_name, visitor_document, vehicle_plate,
       slot_start_at, slot_end_at, idempotency_key, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_visitor_reservations
 WHERE idempotency_key = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetVisitorReservationByIdempotencyKey(ctx context.Context, idempotencyKey *string) (ParkingVisitorReservation, error) {
	row := q.db.QueryRow(ctx, getVisitorReservationByIdempotencyKey, idempotencyKey)
	var i ParkingVisitorReservation
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.RequestedBy,
		&i.VisitorName, &i.VisitorDocument, &i.VehiclePlate,
		&i.SlotStartAt, &i.SlotEndAt, &i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listVisitorReservationsByDate = `-- name: ListVisitorReservationsByDate :many
SELECT id, parking_space_id, unit_id, requested_by,
       visitor_name, visitor_document, vehicle_plate,
       slot_start_at, slot_end_at, idempotency_key, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_visitor_reservations
 WHERE slot_start_at >= $1
   AND slot_start_at < $2
   AND deleted_at IS NULL
 ORDER BY slot_start_at ASC
`

func (q *Queries) ListVisitorReservationsByDate(ctx context.Context, start pgtype.Timestamptz, end pgtype.Timestamptz) ([]ParkingVisitorReservation, error) {
	rows, err := q.db.Query(ctx, listVisitorReservationsByDate, start, end)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingVisitorReservation{}
	for rows.Next() {
		var i ParkingVisitorReservation
		if err := rows.Scan(
			&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.RequestedBy,
			&i.VisitorName, &i.VisitorDocument, &i.VehiclePlate,
			&i.SlotStartAt, &i.SlotEndAt, &i.IdempotencyKey, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitorReservationsByUnit = `-- name: ListVisitorReservationsByUnit :many
SELECT id, parking_space_id, unit_id, requested_by,
       visitor_name, visitor_document, vehicle_plate,
       slot_start_at, slot_end_at, idempotency_key, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_visitor_reservations
 WHERE unit_id = $1
   AND deleted_at IS NULL
 ORDER BY slot_start_at DESC
`

func (q *Queries) ListVisitorReservationsByUnit(ctx context.Context, unitID pgtype.UUID) ([]ParkingVisitorReservation, error) {
	rows, err := q.db.Query(ctx, listVisitorReservationsByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingVisitorReservation{}
	for rows.Next() {
		var i ParkingVisitorReservation
		if err := rows.Scan(
			&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.RequestedBy,
			&i.VisitorName, &i.VisitorDocument, &i.VehiclePlate,
			&i.SlotStartAt, &i.SlotEndAt, &i.IdempotencyKey, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVisitorReservationStatus = `-- name: UpdateVisitorReservationStatus :one
UPDATE parking_visitor_reservations
   SET status     = $1,
       updated_at = now(),
       updated_by = $2,
       version    = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, parking_space_id, unit_id, requested_by,
          visitor_name, visitor_document, vehicle_plate,
          slot_start_at, slot_end_at, idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdateVisitorReservationStatusParams struct {
	NewStatus       string
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateVisitorReservationStatus(ctx context.Context, arg UpdateVisitorReservationStatusParams) (ParkingVisitorReservation, error) {
	row := q.db.QueryRow(ctx, updateVisitorReservationStatus,
		arg.NewStatus, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i ParkingVisitorReservation
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.RequestedBy,
		&i.VisitorName, &i.VisitorDocument, &i.VehiclePlate,
		&i.SlotStartAt, &i.SlotEndAt, &i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const cancelVisitorReservation = `-- name: CancelVisitorReservation :one
UPDATE parking_visitor_reservations
   SET status     = 'cancelled',
       updated_at = now(),
       updated_by = $1,
       version    = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
   AND status IN ('pending', 'confirmed')
RETURNING id, parking_space_id, unit_id, requested_by,
          visitor_name, visitor_document, vehicle_plate,
          slot_start_at, slot_end_at, idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CancelVisitorReservationParams struct {
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) CancelVisitorReservation(ctx context.Context, arg CancelVisitorReservationParams) (ParkingVisitorReservation, error) {
	row := q.db.QueryRow(ctx, cancelVisitorReservation,
		arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i ParkingVisitorReservation
	err := row.Scan(
		&i.ID, &i.ParkingSpaceID, &i.UnitID, &i.RequestedBy,
		&i.VisitorName, &i.VisitorDocument, &i.VehiclePlate,
		&i.SlotStartAt, &i.SlotEndAt, &i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// ---------------------------------------------------------------------------
// parking_lottery_runs
// ---------------------------------------------------------------------------

const createLotteryRun = `-- name: CreateLotteryRun :one
INSERT INTO parking_lottery_runs (
    name, seed_hash, criteria, executed_by,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, 'completed', $4, $4
)
RETURNING id, name, seed_hash, criteria, executed_at, executed_by,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateLotteryRunParams struct {
	Name       string
	SeedHash   string
	Criteria   []byte
	ExecutedBy pgtype.UUID
}

func (q *Queries) CreateLotteryRun(ctx context.Context, arg CreateLotteryRunParams) (ParkingLotteryRun, error) {
	row := q.db.QueryRow(ctx, createLotteryRun,
		arg.Name, arg.SeedHash, arg.Criteria, arg.ExecutedBy,
	)
	var i ParkingLotteryRun
	err := row.Scan(
		&i.ID, &i.Name, &i.SeedHash, &i.Criteria,
		&i.ExecutedAt, &i.ExecutedBy,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getLotteryRunByID = `-- name: GetLotteryRunByID :one
SELECT id, name, seed_hash, criteria, executed_at, executed_by,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_lottery_runs
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetLotteryRunByID(ctx context.Context, id pgtype.UUID) (ParkingLotteryRun, error) {
	row := q.db.QueryRow(ctx, getLotteryRunByID, id)
	var i ParkingLotteryRun
	err := row.Scan(
		&i.ID, &i.Name, &i.SeedHash, &i.Criteria,
		&i.ExecutedAt, &i.ExecutedBy,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listLotteryRuns = `-- name: ListLotteryRuns :many
SELECT id, name, seed_hash, criteria, executed_at, executed_by,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_lottery_runs
 WHERE deleted_at IS NULL
 ORDER BY executed_at DESC
`

func (q *Queries) ListLotteryRuns(ctx context.Context) ([]ParkingLotteryRun, error) {
	rows, err := q.db.Query(ctx, listLotteryRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingLotteryRun{}
	for rows.Next() {
		var i ParkingLotteryRun
		if err := rows.Scan(
			&i.ID, &i.Name, &i.SeedHash, &i.Criteria,
			&i.ExecutedAt, &i.ExecutedBy,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ---------------------------------------------------------------------------
// parking_lottery_results
// ---------------------------------------------------------------------------

const createLotteryResult = `-- name: CreateLotteryResult :one
INSERT INTO parking_lottery_results (
    lottery_run_id, unit_id, parking_space_id, position,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $6
)
RETURNING id, lottery_run_id, unit_id, parking_space_id, position,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateLotteryResultParams struct {
	LotteryRunID   pgtype.UUID
	UnitID         pgtype.UUID
	ParkingSpaceID pgtype.UUID
	Position       int32
	Status         string
	CreatedBy      pgtype.UUID
}

func (q *Queries) CreateLotteryResult(ctx context.Context, arg CreateLotteryResultParams) (ParkingLotteryResult, error) {
	row := q.db.QueryRow(ctx, createLotteryResult,
		arg.LotteryRunID, arg.UnitID, arg.ParkingSpaceID,
		arg.Position, arg.Status, arg.CreatedBy,
	)
	var i ParkingLotteryResult
	err := row.Scan(
		&i.ID, &i.LotteryRunID, &i.UnitID, &i.ParkingSpaceID,
		&i.Position, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listLotteryResultsByRunID = `-- name: ListLotteryResultsByRunID :many
SELECT id, lottery_run_id, unit_id, parking_space_id, position,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM parking_lottery_results
 WHERE lottery_run_id = $1
   AND deleted_at IS NULL
 ORDER BY position ASC
`

func (q *Queries) ListLotteryResultsByRunID(ctx context.Context, lotteryRunID pgtype.UUID) ([]ParkingLotteryResult, error) {
	rows, err := q.db.Query(ctx, listLotteryResultsByRunID, lotteryRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingLotteryResult{}
	for rows.Next() {
		var i ParkingLotteryResult
		if err := rows.Scan(
			&i.ID, &i.LotteryRunID, &i.UnitID, &i.ParkingSpaceID,
			&i.Position, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ---------------------------------------------------------------------------
// parking_outbox_events
// ---------------------------------------------------------------------------

const enqueueParkingOutboxEvent = `-- name: EnqueueParkingOutboxEvent :one
INSERT INTO parking_outbox_events (
    aggregate_id, event_type, payload, next_attempt_at, attempts
) VALUES (
    $1, $2, $3, now(), 0
)
RETURNING id, aggregate_id, event_type, payload, created_at,
          next_attempt_at, attempts, delivered_at, last_error
`

type EnqueueParkingOutboxEventParams struct {
	AggregateID pgtype.UUID
	EventType   string
	Payload     []byte
}

func (q *Queries) EnqueueParkingOutboxEvent(ctx context.Context, arg EnqueueParkingOutboxEventParams) (ParkingOutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueueParkingOutboxEvent, arg.AggregateID, arg.EventType, arg.Payload)
	var i ParkingOutboxEvent
	err := row.Scan(
		&i.ID, &i.AggregateID, &i.EventType, &i.Payload,
		&i.CreatedAt, &i.NextAttemptAt, &i.Attempts,
		&i.DeliveredAt, &i.LastError,
	)
	return i, err
}

const lockPendingParkingOutboxEvents = `-- name: LockPendingParkingOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, created_at,
       next_attempt_at, attempts, delivered_at, last_error
  FROM parking_outbox_events
 WHERE delivered_at IS NULL
   AND next_attempt_at <= now()
 ORDER BY next_attempt_at ASC
 LIMIT $1
 FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockPendingParkingOutboxEvents(ctx context.Context, limit int32) ([]ParkingOutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockPendingParkingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkingOutboxEvent{}
	for rows.Next() {
		var i ParkingOutboxEvent
		if err := rows.Scan(
			&i.ID, &i.AggregateID, &i.EventType, &i.Payload,
			&i.CreatedAt, &i.NextAttemptAt, &i.Attempts,
			&i.DeliveredAt, &i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markParkingOutboxEventDelivered = `-- name: MarkParkingOutboxEventDelivered :exec
UPDATE parking_outbox_events
   SET delivered_at = now(),
       attempts     = attempts + 1,
       last_error   = NULL
 WHERE id = $1
`

func (q *Queries) MarkParkingOutboxEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markParkingOutboxEventDelivered, id)
	return err
}

const markParkingOutboxEventFailed = `-- name: MarkParkingOutboxEventFailed :exec
UPDATE parking_outbox_events
   SET attempts        = attempts + 1,
       last_error      = $1,
       next_attempt_at = $2
 WHERE id = $3
`

type MarkParkingOutboxEventFailedParams struct {
	LastError     *string
	NextAttemptAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) MarkParkingOutboxEventFailed(ctx context.Context, arg MarkParkingOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markParkingOutboxEventFailed, arg.LastError, arg.NextAttemptAt, arg.ID)
	return err
}
