// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package authzdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveRole = `-- name: ArchiveRole :execrows
UPDATE roles
SET status      = 'archived',
    deleted_at  = now(),
    deleted_by  = $2,
    updated_by  = $2,
    updated_at  = now(),
    version     = version + 1
WHERE id = $1
  AND deleted_at IS NULL
  AND is_system = false
`

type ArchiveRoleParams struct {
	ID        pgtype.UUID
	DeletedBy pgtype.UUID
}

func (q *Queries) ArchiveRole(ctx context.Context, arg ArchiveRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveRole, arg.ID, arg.DeletedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const clearPermissionsForRole = `-- name: ClearPermissionsForRole :execrows
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) ClearPermissionsForRole(ctx context.Context, roleID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearPermissionsForRole, roleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO user_role_assignments (
    user_id, role_id, scope_type, scope_id,
    granted_by, status, created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, 'active', $5, $5)
RETURNING id, user_id, role_id, scope_type, scope_id,
          granted_by, granted_at, revoked_at, revocation_reason,
          status, version, created_at, updated_at,
          created_by, updated_by
`

type CreateAssignmentParams struct {
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
	ScopeType *string
	ScopeID   pgtype.UUID
	GrantedBy pgtype.UUID
}

type CreateAssignmentRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RoleID           pgtype.UUID
	ScopeType        *string
	ScopeID          pgtype.UUID
	GrantedBy        pgtype.UUID
	GrantedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	RevocationReason *string
	Status           string
	Version          int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (CreateAssignmentRow, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.UserID,
		arg.RoleID,
		arg.ScopeType,
		arg.ScopeID,
		arg.GrantedBy,
	)
	var i CreateAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description, is_system, status, created_by, updated_by)
VALUES ($1, $2, false, 'active', $3, $3)
RETURNING id, name, description, is_system, status, version,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by
`

type CreateRoleParams struct {
	Name        string
	Description *string
	CreatedBy   pgtype.UUID
}

type CreateRoleRow struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	IsSystem    bool
	Status      string
	Version     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description, arg.CreatedBy)
	var i CreateRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getActiveAssignmentsByUser = `-- name: GetActiveAssignmentsByUser :many
SELECT id, user_id, role_id, scope_type, scope_id,
       granted_by, granted_at, revoked_at, revocation_reason,
       status, version, created_at, updated_at,
       created_by, updated_by
FROM user_role_assignments
WHERE user_id = $1
  AND revoked_at IS NULL
ORDER BY granted_at DESC
`

type GetActiveAssignmentsByUserRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RoleID           pgtype.UUID
	ScopeType        *string
	ScopeID          pgtype.UUID
	GrantedBy        pgtype.UUID
	GrantedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	RevocationReason *string
	Status           string
	Version          int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
}

func (q *Queries) GetActiveAssignmentsByUser(ctx context.Context, userID pgtype.UUID) ([]GetActiveAssignmentsByUserRow, error) {
	rows, err := q.db.Query(ctx, getActiveAssignmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveAssignmentsByUserRow{}
	for rows.Next() {
		var i GetActiveAssignmentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.ScopeType,
			&i.ScopeID,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, namespace, description, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
FROM permissions
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id pgtype.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getPermissionByNamespace = `-- name: GetPermissionByNamespace :one
SELECT id, namespace, description, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
FROM permissions
WHERE namespace = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPermissionByNamespace(ctx context.Context, namespace string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByNamespace, namespace)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, is_system, status, version,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
FROM roles
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetRoleByIDRow struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	IsSystem    bool
	Status      string
	Version     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
}

func (q *Queries) GetRoleByID(ctx context.Context, id pgtype.UUID) (GetRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i GetRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system, status, version,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
FROM roles
WHERE name = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetRoleByNameRow struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	IsSystem    bool
	Status      string
	Version     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
}

func (q *Queries) GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i GetRoleByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listActiveRoles = `-- name: ListActiveRoles :many

SELECT id, name, description, is_system, status, version,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
FROM roles
WHERE deleted_at IS NULL
  AND status = 'active'
ORDER BY name
`

type ListActiveRolesRow struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	IsSystem    bool
	Status      string
	Version     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
}

// queries/authorization.sql
//
// Conjunto de queries del modulo authorization. sqlc genera el paquete
// `authzdb` en `internal/modules/authorization/infrastructure/persistence/sqlcgen`.
//
// Convenciones:
//   - Soft delete via deleted_at IS NULL en lecturas.
//   - Concurrencia optimista en updates de roles (WHERE version = $).
//   - user_role_assignments NO tiene deleted_at: se materializan
//     revocaciones via revoked_at + revocation_reason.
func (q *Queries) ListActiveRoles(ctx context.Context) ([]ListActiveRolesRow, error) {
	rows, err := q.db.Query(ctx, listActiveRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRolesRow{}
	for rows.Next() {
		var i ListActiveRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, namespace, description, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
FROM permissions
WHERE deleted_at IS NULL
  AND status = 'active'
ORDER BY namespace
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT p.id, p.namespace, p.description, p.status,
       p.created_at, p.updated_at, p.deleted_at,
       p.created_by, p.updated_by, p.deleted_by
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
  AND p.deleted_at IS NULL
ORDER BY p.namespace
`

func (q *Queries) ListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForUser = `-- name: ListPermissionsForUser :many
SELECT DISTINCT p.namespace
FROM user_role_assignments ura
JOIN roles r          ON r.id = ura.role_id
                      AND r.deleted_at IS NULL
                      AND r.status = 'active'
JOIN role_permissions rp ON rp.role_id = r.id
JOIN permissions p    ON p.id = rp.permission_id
                      AND p.deleted_at IS NULL
                      AND p.status = 'active'
WHERE ura.user_id = $1
  AND ura.revoked_at IS NULL
  AND ura.status = 'active'
ORDER BY p.namespace
`

func (q *Queries) ListPermissionsForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var namespace string
		if err := rows.Scan(&namespace); err != nil {
			return nil, err
		}
		items = append(items, namespace)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAssignment = `-- name: RevokeAssignment :execrows
UPDATE user_role_assignments
SET revoked_at        = now(),
    revocation_reason = $2,
    status            = 'revoked',
    updated_by        = $3,
    updated_at        = now(),
    version           = version + 1
WHERE id = $1
  AND revoked_at IS NULL
`

type RevokeAssignmentParams struct {
	ID               pgtype.UUID
	RevocationReason *string
	UpdatedBy        pgtype.UUID
}

func (q *Queries) RevokeAssignment(ctx context.Context, arg RevokeAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAssignment, arg.ID, arg.RevocationReason, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :execrows
DELETE FROM role_permissions
WHERE role_id = $1
  AND permission_id = $2
`

type RevokePermissionFromRoleParams struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePermissionFromRole, arg.RoleID, arg.PermissionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRoleName = `-- name: UpdateRoleName :one
UPDATE roles
SET name        = $2,
    description = $3,
    updated_by  = $4,
    updated_at  = now(),
    version     = version + 1
WHERE id = $1
  AND deleted_at IS NULL
  AND is_system = false
  AND version = $5
RETURNING id, name, description, is_system, status, version,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by
`

type UpdateRoleNameParams struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	UpdatedBy   pgtype.UUID
	Version     int32
}

type UpdateRoleNameRow struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	IsSystem    bool
	Status      string
	Version     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
}

func (q *Queries) UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) (UpdateRoleNameRow, error) {
	row := q.db.QueryRow(ctx, updateRoleName,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UpdatedBy,
		arg.Version,
	)
	var i UpdateRoleNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}
