// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authzdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveRole(ctx context.Context, arg ArchiveRoleParams) (int64, error)
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	ClearPermissionsForRole(ctx context.Context, roleID pgtype.UUID) (int64, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (CreateAssignmentRow, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error)
	GetActiveAssignmentsByUser(ctx context.Context, userID pgtype.UUID) ([]GetActiveAssignmentsByUserRow, error)
	GetPermissionByID(ctx context.Context, id pgtype.UUID) (Permission, error)
	GetPermissionByNamespace(ctx context.Context, namespace string) (Permission, error)
	GetRoleByID(ctx context.Context, id pgtype.UUID) (GetRoleByIDRow, error)
	GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error)
	// queries/authorization.sql
	//
	// Conjunto de queries del modulo authorization. sqlc genera el paquete
	// `authzdb` en `internal/modules/authorization/infrastructure/persistence/sqlcgen`.
	//
	// Convenciones:
	//   - Soft delete via deleted_at IS NULL en lecturas.
	//   - Concurrencia optimista en updates de roles (WHERE version = $).
	//   - user_role_assignments NO tiene deleted_at: se materializan
	//     revocaciones via revoked_at + revocation_reason.
	ListActiveRoles(ctx context.Context) ([]ListActiveRolesRow, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error)
	ListPermissionsForUser(ctx context.Context, userID pgtype.UUID) ([]string, error)
	RevokeAssignment(ctx context.Context, arg RevokeAssignmentParams) (int64, error)
	RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) (int64, error)
	UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) (UpdateRoleNameRow, error)
}

var _ Querier = (*Queries)(nil)
