// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pqrsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PqrsCategory struct {
	ID                    pgtype.UUID
	Code                  string
	Name                  string
	DefaultAssigneeRoleID pgtype.UUID
	Status                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	CreatedBy             pgtype.UUID
	UpdatedBy             pgtype.UUID
	DeletedBy             pgtype.UUID
	Version               int32
}

type PqrsTicket struct {
	ID                pgtype.UUID
	TicketYear        int32
	SerialNumber      int32
	PqrType           string
	CategoryID        pgtype.UUID
	Subject           string
	Body              string
	RequesterUserID   pgtype.UUID
	AssignedToUserID  pgtype.UUID
	AssignedAt        pgtype.Timestamptz
	RespondedAt       pgtype.Timestamptz
	ClosedAt          pgtype.Timestamptz
	EscalatedAt       pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	SlaDueAt          pgtype.Timestamptz
	RequesterRating   pgtype.Int4
	RequesterFeedback *string
	IsAnonymous       bool
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
	DeletedBy         pgtype.UUID
	Version           int32
}

type PqrsResponse struct {
	ID                pgtype.UUID
	TicketID          pgtype.UUID
	ResponseType      string
	Body              string
	RespondedByUserID pgtype.UUID
	RespondedAt       pgtype.Timestamptz
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
	DeletedBy         pgtype.UUID
	Version           int32
}

type PqrsStatusHistory struct {
	ID                   pgtype.UUID
	TicketID             pgtype.UUID
	FromStatus           *string
	ToStatus             string
	TransitionedByUserID pgtype.UUID
	TransitionedAt       pgtype.Timestamptz
	Notes                *string
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedBy            pgtype.UUID
	UpdatedBy            pgtype.UUID
}

type PqrsOutboxEvent struct {
	ID             pgtype.UUID
	TicketID       pgtype.UUID
	EventType      string
	Payload        []byte
	IdempotencyKey *string
	CreatedAt      pgtype.Timestamptz
	NextAttemptAt  pgtype.Timestamptz
	Attempts       int32
	DeliveredAt    pgtype.Timestamptz
	LastError      *string
}
