// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pqrs.sql

package pqrsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// --- Categories ---

const createPQRSCategory = `-- name: CreatePQRSCategory :one
INSERT INTO pqrs_categories (
    code, name, default_assignee_role_id, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, 'active', $4, $4
)
RETURNING id, code, name, default_assignee_role_id, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type CreatePQRSCategoryParams struct {
	Code                  string
	Name                  string
	DefaultAssigneeRoleID pgtype.UUID
	CreatedBy             pgtype.UUID
}

func (q *Queries) CreatePQRSCategory(ctx context.Context, arg CreatePQRSCategoryParams) (PqrsCategory, error) {
	row := q.db.QueryRow(ctx, createPQRSCategory,
		arg.Code, arg.Name, arg.DefaultAssigneeRoleID, arg.CreatedBy,
	)
	var i PqrsCategory
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.DefaultAssigneeRoleID, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getPQRSCategoryByID = `-- name: GetPQRSCategoryByID :one
SELECT id, code, name, default_assignee_role_id, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM pqrs_categories
 WHERE id = $1
   AND deleted_at IS NULL`

func (q *Queries) GetPQRSCategoryByID(ctx context.Context, id pgtype.UUID) (PqrsCategory, error) {
	row := q.db.QueryRow(ctx, getPQRSCategoryByID, id)
	var i PqrsCategory
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.DefaultAssigneeRoleID, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listPQRSCategories = `-- name: ListPQRSCategories :many
SELECT id, code, name, default_assignee_role_id, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM pqrs_categories
 WHERE deleted_at IS NULL
 ORDER BY code ASC`

func (q *Queries) ListPQRSCategories(ctx context.Context) ([]PqrsCategory, error) {
	rows, err := q.db.Query(ctx, listPQRSCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PqrsCategory
	for rows.Next() {
		var i PqrsCategory
		if err := rows.Scan(
			&i.ID, &i.Code, &i.Name, &i.DefaultAssigneeRoleID, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updatePQRSCategory = `-- name: UpdatePQRSCategory :one
UPDATE pqrs_categories
   SET code                     = $1,
       name                     = $2,
       default_assignee_role_id = $3,
       status                   = $4,
       updated_at               = now(),
       updated_by               = $5,
       version                  = version + 1
 WHERE id = $6
   AND version = $7
   AND deleted_at IS NULL
RETURNING id, code, name, default_assignee_role_id, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type UpdatePQRSCategoryParams struct {
	NewCode                  string
	NewName                  string
	NewDefaultAssigneeRoleID pgtype.UUID
	NewStatus                string
	UpdatedBy                pgtype.UUID
	ID                       pgtype.UUID
	ExpectedVersion          int32
}

func (q *Queries) UpdatePQRSCategory(ctx context.Context, arg UpdatePQRSCategoryParams) (PqrsCategory, error) {
	row := q.db.QueryRow(ctx, updatePQRSCategory,
		arg.NewCode, arg.NewName, arg.NewDefaultAssigneeRoleID,
		arg.NewStatus, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i PqrsCategory
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.DefaultAssigneeRoleID, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// --- Tickets ---

const nextPQRSSerialNumber = `-- name: NextPQRSSerialNumber :one
SELECT COALESCE(MAX(serial_number), 0) + 1 AS next_serial
  FROM pqrs_tickets
 WHERE ticket_year = $1
   AND deleted_at IS NULL`

func (q *Queries) NextPQRSSerialNumber(ctx context.Context, ticketYear int32) (int32, error) {
	row := q.db.QueryRow(ctx, nextPQRSSerialNumber, ticketYear)
	var nextSerial int32
	err := row.Scan(&nextSerial)
	return nextSerial, err
}

const createPQRSTicket = `-- name: CreatePQRSTicket :one
INSERT INTO pqrs_tickets (
    ticket_year, serial_number, pqr_type, category_id,
    subject, body, requester_user_id, is_anonymous,
    sla_due_at, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 'radicado', $10, $10
)
RETURNING id, ticket_year, serial_number, pqr_type, category_id,
          subject, body, requester_user_id,
          assigned_to_user_id, assigned_at, responded_at,
          closed_at, escalated_at, cancelled_at, sla_due_at,
          requester_rating, requester_feedback, is_anonymous,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type CreatePQRSTicketParams struct {
	TicketYear      int32
	SerialNumber    int32
	PqrType         string
	CategoryID      pgtype.UUID
	Subject         string
	Body            string
	RequesterUserID pgtype.UUID
	IsAnonymous     bool
	SlaDueAt        pgtype.Timestamptz
	CreatedBy       pgtype.UUID
}

func (q *Queries) CreatePQRSTicket(ctx context.Context, arg CreatePQRSTicketParams) (PqrsTicket, error) {
	row := q.db.QueryRow(ctx, createPQRSTicket,
		arg.TicketYear, arg.SerialNumber, arg.PqrType, arg.CategoryID,
		arg.Subject, arg.Body, arg.RequesterUserID, arg.IsAnonymous,
		arg.SlaDueAt, arg.CreatedBy,
	)
	var i PqrsTicket
	err := row.Scan(
		&i.ID, &i.TicketYear, &i.SerialNumber, &i.PqrType, &i.CategoryID,
		&i.Subject, &i.Body, &i.RequesterUserID,
		&i.AssignedToUserID, &i.AssignedAt, &i.RespondedAt,
		&i.ClosedAt, &i.EscalatedAt, &i.CancelledAt, &i.SlaDueAt,
		&i.RequesterRating, &i.RequesterFeedback, &i.IsAnonymous,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getPQRSTicketByID = `-- name: GetPQRSTicketByID :one
SELECT id, ticket_year, serial_number, pqr_type, category_id,
       subject, body, requester_user_id,
       assigned_to_user_id, assigned_at, responded_at,
       closed_at, escalated_at, cancelled_at, sla_due_at,
       requester_rating, requester_feedback, is_anonymous,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM pqrs_tickets
 WHERE id = $1
   AND deleted_at IS NULL`

func (q *Queries) GetPQRSTicketByID(ctx context.Context, id pgtype.UUID) (PqrsTicket, error) {
	row := q.db.QueryRow(ctx, getPQRSTicketByID, id)
	var i PqrsTicket
	err := row.Scan(
		&i.ID, &i.TicketYear, &i.SerialNumber, &i.PqrType, &i.CategoryID,
		&i.Subject, &i.Body, &i.RequesterUserID,
		&i.AssignedToUserID, &i.AssignedAt, &i.RespondedAt,
		&i.ClosedAt, &i.EscalatedAt, &i.CancelledAt, &i.SlaDueAt,
		&i.RequesterRating, &i.RequesterFeedback, &i.IsAnonymous,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listPQRSTickets = `-- name: ListPQRSTickets :many
SELECT id, ticket_year, serial_number, pqr_type, category_id,
       subject, body, requester_user_id,
       assigned_to_user_id, assigned_at, responded_at,
       closed_at, escalated_at, cancelled_at, sla_due_at,
       requester_rating, requester_feedback, is_anonymous,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM pqrs_tickets
 WHERE deleted_at IS NULL
   AND ($1::text IS NULL OR status = $1)
   AND ($2::text IS NULL OR pqr_type = $2)
   AND ($3::uuid IS NULL OR requester_user_id = $3)
   AND ($4::uuid IS NULL OR assigned_to_user_id = $4)
 ORDER BY created_at DESC`

type ListPQRSTicketsParams struct {
	FilterStatus    *string
	FilterPqrType   *string
	FilterRequester pgtype.UUID
	FilterAssigned  pgtype.UUID
}

func (q *Queries) ListPQRSTickets(ctx context.Context, arg ListPQRSTicketsParams) ([]PqrsTicket, error) {
	rows, err := q.db.Query(ctx, listPQRSTickets,
		arg.FilterStatus, arg.FilterPqrType,
		arg.FilterRequester, arg.FilterAssigned,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PqrsTicket
	for rows.Next() {
		var i PqrsTicket
		if err := rows.Scan(
			&i.ID, &i.TicketYear, &i.SerialNumber, &i.PqrType, &i.CategoryID,
			&i.Subject, &i.Body, &i.RequesterUserID,
			&i.AssignedToUserID, &i.AssignedAt, &i.RespondedAt,
			&i.ClosedAt, &i.EscalatedAt, &i.CancelledAt, &i.SlaDueAt,
			&i.RequesterRating, &i.RequesterFeedback, &i.IsAnonymous,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updatePQRSTicketStatus = `-- name: UpdatePQRSTicketStatus :one
UPDATE pqrs_tickets
   SET status     = $1,
       updated_at = now(),
       updated_by = $2,
       version    = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, ticket_year, serial_number, pqr_type, category_id,
          subject, body, requester_user_id,
          assigned_to_user_id, assigned_at, responded_at,
          closed_at, escalated_at, cancelled_at, sla_due_at,
          requester_rating, requester_feedback, is_anonymous,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type UpdatePQRSTicketStatusParams struct {
	NewStatus       string
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdatePQRSTicketStatus(ctx context.Context, arg UpdatePQRSTicketStatusParams) (PqrsTicket, error) {
	row := q.db.QueryRow(ctx, updatePQRSTicketStatus,
		arg.NewStatus, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i PqrsTicket
	err := row.Scan(
		&i.ID, &i.TicketYear, &i.SerialNumber, &i.PqrType, &i.CategoryID,
		&i.Subject, &i.Body, &i.RequesterUserID,
		&i.AssignedToUserID, &i.AssignedAt, &i.RespondedAt,
		&i.ClosedAt, &i.EscalatedAt, &i.CancelledAt, &i.SlaDueAt,
		&i.RequesterRating, &i.RequesterFeedback, &i.IsAnonymous,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const assignPQRSTicket = `-- name: AssignPQRSTicket :one
UPDATE pqrs_tickets
   SET assigned_to_user_id = $1,
       assigned_at         = now(),
       updated_at          = now(),
       updated_by          = $2,
       version             = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, ticket_year, serial_number, pqr_type, category_id,
          subject, body, requester_user_id,
          assigned_to_user_id, assigned_at, responded_at,
          closed_at, escalated_at, cancelled_at, sla_due_at,
          requester_rating, requester_feedback, is_anonymous,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type AssignPQRSTicketParams struct {
	AssigneeUserID  pgtype.UUID
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) AssignPQRSTicket(ctx context.Context, arg AssignPQRSTicketParams) (PqrsTicket, error) {
	row := q.db.QueryRow(ctx, assignPQRSTicket,
		arg.AssigneeUserID, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i PqrsTicket
	err := row.Scan(
		&i.ID, &i.TicketYear, &i.SerialNumber, &i.PqrType, &i.CategoryID,
		&i.Subject, &i.Body, &i.RequesterUserID,
		&i.AssignedToUserID, &i.AssignedAt, &i.RespondedAt,
		&i.ClosedAt, &i.EscalatedAt, &i.CancelledAt, &i.SlaDueAt,
		&i.RequesterRating, &i.RequesterFeedback, &i.IsAnonymous,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const setPQRSTicketResponded = `-- name: SetPQRSTicketResponded :one
UPDATE pqrs_tickets
   SET status       = 'respondido',
       responded_at = now(),
       updated_at   = now(),
       updated_by   = $1,
       version      = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
RETURNING id, ticket_year, serial_number, pqr_type, category_id,
          subject, body, requester_user_id,
          assigned_to_user_id, assigned_at, responded_at,
          closed_at, escalated_at, cancelled_at, sla_due_at,
          requester_rating, requester_feedback, is_anonymous,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type SetPQRSTicketRespondedParams struct {
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SetPQRSTicketResponded(ctx context.Context, arg SetPQRSTicketRespondedParams) (PqrsTicket, error) {
	row := q.db.QueryRow(ctx, setPQRSTicketResponded,
		arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i PqrsTicket
	err := row.Scan(
		&i.ID, &i.TicketYear, &i.SerialNumber, &i.PqrType, &i.CategoryID,
		&i.Subject, &i.Body, &i.RequesterUserID,
		&i.AssignedToUserID, &i.AssignedAt, &i.RespondedAt,
		&i.ClosedAt, &i.EscalatedAt, &i.CancelledAt, &i.SlaDueAt,
		&i.RequesterRating, &i.RequesterFeedback, &i.IsAnonymous,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const closePQRSTicket = `-- name: ClosePQRSTicket :one
UPDATE pqrs_tickets
   SET status             = 'cerrado',
       closed_at          = now(),
       requester_rating   = $1,
       requester_feedback = $2,
       updated_at         = now(),
       updated_by         = $3,
       version            = version + 1
 WHERE id = $4
   AND version = $5
   AND deleted_at IS NULL
RETURNING id, ticket_year, serial_number, pqr_type, category_id,
          subject, body, requester_user_id,
          assigned_to_user_id, assigned_at, responded_at,
          closed_at, escalated_at, cancelled_at, sla_due_at,
          requester_rating, requester_feedback, is_anonymous,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type ClosePQRSTicketParams struct {
	Rating          pgtype.Int4
	Feedback        *string
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) ClosePQRSTicket(ctx context.Context, arg ClosePQRSTicketParams) (PqrsTicket, error) {
	row := q.db.QueryRow(ctx, closePQRSTicket,
		arg.Rating, arg.Feedback, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i PqrsTicket
	err := row.Scan(
		&i.ID, &i.TicketYear, &i.SerialNumber, &i.PqrType, &i.CategoryID,
		&i.Subject, &i.Body, &i.RequesterUserID,
		&i.AssignedToUserID, &i.AssignedAt, &i.RespondedAt,
		&i.ClosedAt, &i.EscalatedAt, &i.CancelledAt, &i.SlaDueAt,
		&i.RequesterRating, &i.RequesterFeedback, &i.IsAnonymous,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const escalatePQRSTicket = `-- name: EscalatePQRSTicket :one
UPDATE pqrs_tickets
   SET status       = 'escalado',
       escalated_at = now(),
       updated_at   = now(),
       updated_by   = $1,
       version      = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
RETURNING id, ticket_year, serial_number, pqr_type, category_id,
          subject, body, requester_user_id,
          assigned_to_user_id, assigned_at, responded_at,
          closed_at, escalated_at, cancelled_at, sla_due_at,
          requester_rating, requester_feedback, is_anonymous,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type EscalatePQRSTicketParams struct {
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) EscalatePQRSTicket(ctx context.Context, arg EscalatePQRSTicketParams) (PqrsTicket, error) {
	row := q.db.QueryRow(ctx, escalatePQRSTicket,
		arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i PqrsTicket
	err := row.Scan(
		&i.ID, &i.TicketYear, &i.SerialNumber, &i.PqrType, &i.CategoryID,
		&i.Subject, &i.Body, &i.RequesterUserID,
		&i.AssignedToUserID, &i.AssignedAt, &i.RespondedAt,
		&i.ClosedAt, &i.EscalatedAt, &i.CancelledAt, &i.SlaDueAt,
		&i.RequesterRating, &i.RequesterFeedback, &i.IsAnonymous,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const cancelPQRSTicket = `-- name: CancelPQRSTicket :one
UPDATE pqrs_tickets
   SET status       = 'cancelado',
       cancelled_at = now(),
       updated_at   = now(),
       updated_by   = $1,
       version      = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
RETURNING id, ticket_year, serial_number, pqr_type, category_id,
          subject, body, requester_user_id,
          assigned_to_user_id, assigned_at, responded_at,
          closed_at, escalated_at, cancelled_at, sla_due_at,
          requester_rating, requester_feedback, is_anonymous,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type CancelPQRSTicketParams struct {
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) CancelPQRSTicket(ctx context.Context, arg CancelPQRSTicketParams) (PqrsTicket, error) {
	row := q.db.QueryRow(ctx, cancelPQRSTicket,
		arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i PqrsTicket
	err := row.Scan(
		&i.ID, &i.TicketYear, &i.SerialNumber, &i.PqrType, &i.CategoryID,
		&i.Subject, &i.Body, &i.RequesterUserID,
		&i.AssignedToUserID, &i.AssignedAt, &i.RespondedAt,
		&i.ClosedAt, &i.EscalatedAt, &i.CancelledAt, &i.SlaDueAt,
		&i.RequesterRating, &i.RequesterFeedback, &i.IsAnonymous,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// --- Responses ---

const createPQRSResponse = `-- name: CreatePQRSResponse :one
INSERT INTO pqrs_responses (
    ticket_id, response_type, body,
    responded_by_user_id, responded_at,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, now(), 'active', $4, $4
)
RETURNING id, ticket_id, response_type, body,
          responded_by_user_id, responded_at,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type CreatePQRSResponseParams struct {
	TicketID          pgtype.UUID
	ResponseType      string
	Body              string
	RespondedByUserID pgtype.UUID
}

func (q *Queries) CreatePQRSResponse(ctx context.Context, arg CreatePQRSResponseParams) (PqrsResponse, error) {
	row := q.db.QueryRow(ctx, createPQRSResponse,
		arg.TicketID, arg.ResponseType, arg.Body, arg.RespondedByUserID,
	)
	var i PqrsResponse
	err := row.Scan(
		&i.ID, &i.TicketID, &i.ResponseType, &i.Body,
		&i.RespondedByUserID, &i.RespondedAt,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listPQRSResponsesByTicketID = `-- name: ListPQRSResponsesByTicketID :many
SELECT id, ticket_id, response_type, body,
       responded_by_user_id, responded_at,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM pqrs_responses
 WHERE ticket_id = $1
   AND deleted_at IS NULL
 ORDER BY responded_at DESC`

func (q *Queries) ListPQRSResponsesByTicketID(ctx context.Context, ticketID pgtype.UUID) ([]PqrsResponse, error) {
	rows, err := q.db.Query(ctx, listPQRSResponsesByTicketID, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PqrsResponse
	for rows.Next() {
		var i PqrsResponse
		if err := rows.Scan(
			&i.ID, &i.TicketID, &i.ResponseType, &i.Body,
			&i.RespondedByUserID, &i.RespondedAt,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const hasPQRSOfficialResponse = `-- name: HasPQRSOfficialResponse :one
SELECT EXISTS (
    SELECT 1
      FROM pqrs_responses
     WHERE ticket_id = $1
       AND response_type = 'official_response'
       AND deleted_at IS NULL
) AS has_official`

func (q *Queries) HasPQRSOfficialResponse(ctx context.Context, ticketID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPQRSOfficialResponse, ticketID)
	var hasOfficial bool
	err := row.Scan(&hasOfficial)
	return hasOfficial, err
}

// --- Status History ---

const recordPQRSStatusHistory = `-- name: RecordPQRSStatusHistory :one
INSERT INTO pqrs_status_history (
    ticket_id, from_status, to_status,
    transitioned_by_user_id, transitioned_at,
    notes, status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, now(), $5, 'recorded', $4, $4
)
RETURNING id, ticket_id, from_status, to_status,
          transitioned_by_user_id, transitioned_at,
          notes, status, created_at, updated_at,
          created_by, updated_by`

type RecordPQRSStatusHistoryParams struct {
	TicketID             pgtype.UUID
	FromStatus           *string
	ToStatus             string
	TransitionedByUserID pgtype.UUID
	Notes                *string
}

func (q *Queries) RecordPQRSStatusHistory(ctx context.Context, arg RecordPQRSStatusHistoryParams) (PqrsStatusHistory, error) {
	row := q.db.QueryRow(ctx, recordPQRSStatusHistory,
		arg.TicketID, arg.FromStatus, arg.ToStatus,
		arg.TransitionedByUserID, arg.Notes,
	)
	var i PqrsStatusHistory
	err := row.Scan(
		&i.ID, &i.TicketID, &i.FromStatus, &i.ToStatus,
		&i.TransitionedByUserID, &i.TransitionedAt,
		&i.Notes, &i.Status, &i.CreatedAt, &i.UpdatedAt,
		&i.CreatedBy, &i.UpdatedBy,
	)
	return i, err
}

const listPQRSStatusHistoryByTicketID = `-- name: ListPQRSStatusHistoryByTicketID :many
SELECT id, ticket_id, from_status, to_status,
       transitioned_by_user_id, transitioned_at,
       notes, status, created_at, updated_at,
       created_by, updated_by
  FROM pqrs_status_history
 WHERE ticket_id = $1
 ORDER BY transitioned_at DESC`

func (q *Queries) ListPQRSStatusHistoryByTicketID(ctx context.Context, ticketID pgtype.UUID) ([]PqrsStatusHistory, error) {
	rows, err := q.db.Query(ctx, listPQRSStatusHistoryByTicketID, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PqrsStatusHistory
	for rows.Next() {
		var i PqrsStatusHistory
		if err := rows.Scan(
			&i.ID, &i.TicketID, &i.FromStatus, &i.ToStatus,
			&i.TransitionedByUserID, &i.TransitionedAt,
			&i.Notes, &i.Status, &i.CreatedAt, &i.UpdatedAt,
			&i.CreatedBy, &i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// --- Outbox ---

const enqueuePQRSOutboxEvent = `-- name: EnqueuePQRSOutboxEvent :one
INSERT INTO pqrs_outbox_events (
    ticket_id, event_type, payload, idempotency_key,
    next_attempt_at, attempts
) VALUES (
    $1, $2, $3, $4, now(), 0
)
RETURNING id, ticket_id, event_type, payload, idempotency_key,
          created_at, next_attempt_at, attempts,
          delivered_at, last_error`

type EnqueuePQRSOutboxEventParams struct {
	TicketID       pgtype.UUID
	EventType      string
	Payload        []byte
	IdempotencyKey *string
}

func (q *Queries) EnqueuePQRSOutboxEvent(ctx context.Context, arg EnqueuePQRSOutboxEventParams) (PqrsOutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueuePQRSOutboxEvent,
		arg.TicketID, arg.EventType, arg.Payload, arg.IdempotencyKey,
	)
	var i PqrsOutboxEvent
	err := row.Scan(
		&i.ID, &i.TicketID, &i.EventType, &i.Payload, &i.IdempotencyKey,
		&i.CreatedAt, &i.NextAttemptAt, &i.Attempts,
		&i.DeliveredAt, &i.LastError,
	)
	return i, err
}

const lockPendingPQRSOutboxEvents = `-- name: LockPendingPQRSOutboxEvents :many
SELECT id, ticket_id, event_type, payload, idempotency_key,
       created_at, next_attempt_at, attempts,
       delivered_at, last_error
  FROM pqrs_outbox_events
 WHERE delivered_at IS NULL
   AND next_attempt_at <= now()
 ORDER BY next_attempt_at ASC
 LIMIT $1
 FOR UPDATE SKIP LOCKED`

func (q *Queries) LockPendingPQRSOutboxEvents(ctx context.Context, limit int32) ([]PqrsOutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockPendingPQRSOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PqrsOutboxEvent
	for rows.Next() {
		var i PqrsOutboxEvent
		if err := rows.Scan(
			&i.ID, &i.TicketID, &i.EventType, &i.Payload, &i.IdempotencyKey,
			&i.CreatedAt, &i.NextAttemptAt, &i.Attempts,
			&i.DeliveredAt, &i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const markPQRSOutboxEventDelivered = `-- name: MarkPQRSOutboxEventDelivered :exec
UPDATE pqrs_outbox_events
   SET delivered_at = now(),
       attempts     = attempts + 1,
       last_error   = NULL
 WHERE id = $1`

func (q *Queries) MarkPQRSOutboxEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPQRSOutboxEventDelivered, id)
	return err
}

const markPQRSOutboxEventFailed = `-- name: MarkPQRSOutboxEventFailed :exec
UPDATE pqrs_outbox_events
   SET attempts        = attempts + 1,
       last_error      = $1,
       next_attempt_at = $2
 WHERE id = $3`

type MarkPQRSOutboxEventFailedParams struct {
	LastError     *string
	NextAttemptAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) MarkPQRSOutboxEventFailed(ctx context.Context, arg MarkPQRSOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markPQRSOutboxEventFailed,
		arg.LastError, arg.NextAttemptAt, arg.ID,
	)
	return err
}
