// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package announcementsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledge = `-- name: Acknowledge :one

INSERT INTO announcement_acknowledgments (
    announcement_id, user_id, created_by, updated_by
) VALUES (
    $1, $2, $2, $2
)
ON CONFLICT (announcement_id, user_id) DO UPDATE
   SET acknowledged_at = announcement_acknowledgments.acknowledged_at
RETURNING id, announcement_id, user_id, acknowledged_at,
          created_at, updated_at, created_by, updated_by
`

type AcknowledgeParams struct {
	AnnouncementID pgtype.UUID
	UserID         pgtype.UUID
}

// ----------------------------------------------------------------------------
// announcement_acknowledgments
// ----------------------------------------------------------------------------
// Inserta una confirmacion de lectura. ON CONFLICT DO NOTHING para que sea
// idempotente (un usuario no acumula acks duplicados).
func (q *Queries) Acknowledge(ctx context.Context, arg AcknowledgeParams) (AnnouncementAcknowledgment, error) {
	row := q.db.QueryRow(ctx, acknowledge, arg.AnnouncementID, arg.UserID)
	var i AnnouncementAcknowledgment
	err := row.Scan(
		&i.ID,
		&i.AnnouncementID,
		&i.UserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const addAudience = `-- name: AddAudience :one

INSERT INTO announcement_audiences (
    announcement_id, target_type, target_id, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, 'active', $4, $4
)
RETURNING id, announcement_id, target_type, target_id, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by
`

type AddAudienceParams struct {
	AnnouncementID pgtype.UUID
	TargetType     string
	TargetID       pgtype.UUID
	CreatedBy      pgtype.UUID
}

// ----------------------------------------------------------------------------
// announcement_audiences
// ----------------------------------------------------------------------------
// Inserta una audiencia para un anuncio. La coherencia
// (target_type='global' <-> target_id NULL) se enforza por CHECK.
func (q *Queries) AddAudience(ctx context.Context, arg AddAudienceParams) (AnnouncementAudience, error) {
	row := q.db.QueryRow(ctx, addAudience,
		arg.AnnouncementID,
		arg.TargetType,
		arg.TargetID,
		arg.CreatedBy,
	)
	var i AnnouncementAudience
	err := row.Scan(
		&i.ID,
		&i.AnnouncementID,
		&i.TargetType,
		&i.TargetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const archiveAnnouncement = `-- name: ArchiveAnnouncement :one
UPDATE announcements
   SET status     = 'archived',
       deleted_at = now(),
       deleted_by = $1,
       updated_at = now(),
       updated_by = $1,
       version    = version + 1
 WHERE id = $2
   AND deleted_at IS NULL
RETURNING id, title, body, published_by_user_id, published_at,
          pinned, expires_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type ArchiveAnnouncementParams struct {
	DeletedBy pgtype.UUID
	ID        pgtype.UUID
}

// Soft-delete: marca el anuncio como archivado.
func (q *Queries) ArchiveAnnouncement(ctx context.Context, arg ArchiveAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, archiveAnnouncement, arg.DeletedBy, arg.ID)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.PublishedByUserID,
		&i.PublishedAt,
		&i.Pinned,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one


INSERT INTO announcements (
    title, body, published_by_user_id, pinned, expires_at, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, 'published', $3, $3
)
RETURNING id, title, body, published_by_user_id, published_at,
          pinned, expires_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateAnnouncementParams struct {
	Title             string
	Body              string
	PublishedByUserID pgtype.UUID
	Pinned            bool
	ExpiresAt         pgtype.Timestamptz
}

// Queries del modulo announcements (sqlc).
//
// Convenciones:
//   - Listados excluyen filas con deleted_at IS NOT NULL.
//   - Soft-delete via marcar status='archived' y deleted_at = now().
//   - El feed por usuario ($1=user_id) usa arrays uuid[] de scopes:
//     $2 role_ids, $3 structure_ids, $4 unit_ids; arrays vacios filtran
//     correctamente porque target_id = ANY('{}'::uuid[]) es FALSE.
//   - Acknowledgments son insert ON CONFLICT DO NOTHING (idempotencia).
//
// ----------------------------------------------------------------------------
// announcements
// ----------------------------------------------------------------------------
// Crea un anuncio en estado 'published'. published_by_user_id se replica
// en created_by/updated_by por defecto. published_at = now() salvo override.
func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.Title,
		arg.Body,
		arg.PublishedByUserID,
		arg.Pinned,
		arg.ExpiresAt,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.PublishedByUserID,
		&i.PublishedAt,
		&i.Pinned,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT id, title, body, published_by_user_id, published_at,
       pinned, expires_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM announcements
 WHERE id = $1
   AND deleted_at IS NULL
`

// Devuelve un anuncio por id (no soft-deleted).
func (q *Queries) GetAnnouncementByID(ctx context.Context, id pgtype.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.PublishedByUserID,
		&i.PublishedAt,
		&i.Pinned,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const listAudiencesByAnnouncement = `-- name: ListAudiencesByAnnouncement :many
SELECT id, announcement_id, target_type, target_id, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
  FROM announcement_audiences
 WHERE announcement_id = $1
   AND deleted_at IS NULL
 ORDER BY created_at ASC
`

// Lista las audiencias activas de un anuncio.
func (q *Queries) ListAudiencesByAnnouncement(ctx context.Context, announcementID pgtype.UUID) ([]AnnouncementAudience, error) {
	rows, err := q.db.Query(ctx, listAudiencesByAnnouncement, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnnouncementAudience{}
	for rows.Next() {
		var i AnnouncementAudience
		if err := rows.Scan(
			&i.ID,
			&i.AnnouncementID,
			&i.TargetType,
			&i.TargetID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedForUser = `-- name: ListFeedForUser :many
SELECT a.id, a.title, a.body, a.published_by_user_id, a.published_at,
       a.pinned, a.expires_at, a.status,
       a.created_at, a.updated_at, a.deleted_at,
       a.created_by, a.updated_by, a.deleted_by, a.version
  FROM announcements a
 WHERE a.status = 'published'
   AND a.deleted_at IS NULL
   AND (a.expires_at IS NULL OR a.expires_at > now())
   AND ($1::uuid IS NOT NULL OR $1::uuid IS NULL)
   AND EXISTS (
        SELECT 1
          FROM announcement_audiences aa
         WHERE aa.announcement_id = a.id
           AND aa.deleted_at IS NULL
           AND (
                aa.target_type = 'global'
                OR (aa.target_type = 'role'      AND aa.target_id = ANY($2::uuid[]))
                OR (aa.target_type = 'structure' AND aa.target_id = ANY($3::uuid[]))
                OR (aa.target_type = 'unit'      AND aa.target_id = ANY($4::uuid[]))
           )
   )
 ORDER BY a.pinned DESC, a.published_at DESC
 LIMIT $6
 OFFSET $5
`

type ListFeedForUserParams struct {
	UserID       pgtype.UUID
	RoleIds      []pgtype.UUID
	StructureIds []pgtype.UUID
	UnitIds      []pgtype.UUID
	Off          int32
	Lim          int32
}

// Devuelve los anuncios VISIBLES para el usuario. Visible significa:
//   - status='published' AND deleted_at IS NULL,
//   - (expires_at IS NULL OR expires_at > now()),
//   - existe al menos UNA audiencia que matche:
//     target_type='global' OR
//     target_type='role' AND target_id = ANY($2::uuid[]) OR
//     target_type='structure' AND target_id = ANY($3::uuid[]) OR
//     target_type='unit' AND target_id = ANY($4::uuid[]).
//
// Orden: pinned DESC, published_at DESC.
// $1 user_id se mantiene en la firma para futuro uso (ej. excluir
// ack-eados, segmentar por usuario), aunque hoy no participa del WHERE.
func (q *Queries) ListFeedForUser(ctx context.Context, arg ListFeedForUserParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listFeedForUser,
		arg.UserID,
		arg.RoleIds,
		arg.StructureIds,
		arg.UnitIds,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.PublishedByUserID,
			&i.PublishedAt,
			&i.Pinned,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
