// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package announcementsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ----------------------------------------------------------------------------
	// announcement_acknowledgments
	// ----------------------------------------------------------------------------
	// Inserta una confirmacion de lectura. ON CONFLICT DO NOTHING para que sea
	// idempotente (un usuario no acumula acks duplicados).
	Acknowledge(ctx context.Context, arg AcknowledgeParams) (AnnouncementAcknowledgment, error)
	// ----------------------------------------------------------------------------
	// announcement_audiences
	// ----------------------------------------------------------------------------
	// Inserta una audiencia para un anuncio. La coherencia
	// (target_type='global' <-> target_id NULL) se enforza por CHECK.
	AddAudience(ctx context.Context, arg AddAudienceParams) (AnnouncementAudience, error)
	// Soft-delete: marca el anuncio como archivado.
	ArchiveAnnouncement(ctx context.Context, arg ArchiveAnnouncementParams) (Announcement, error)
	// Queries del modulo announcements (sqlc).
	//
	// Convenciones:
	//   * Listados excluyen filas con deleted_at IS NOT NULL.
	//   * Soft-delete via marcar status='archived' y deleted_at = now().
	//   * El feed por usuario ($1=user_id) usa arrays uuid[] de scopes:
	//     $2 role_ids, $3 structure_ids, $4 unit_ids; arrays vacios filtran
	//     correctamente porque target_id = ANY('{}'::uuid[]) es FALSE.
	//   * Acknowledgments son insert ON CONFLICT DO NOTHING (idempotencia).
	// ----------------------------------------------------------------------------
	// announcements
	// ----------------------------------------------------------------------------
	// Crea un anuncio en estado 'published'. published_by_user_id se replica
	// en created_by/updated_by por defecto. published_at = now() salvo override.
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	// Devuelve un anuncio por id (no soft-deleted).
	GetAnnouncementByID(ctx context.Context, id pgtype.UUID) (Announcement, error)
	// Lista las audiencias activas de un anuncio.
	ListAudiencesByAnnouncement(ctx context.Context, announcementID pgtype.UUID) ([]AnnouncementAudience, error)
	// Devuelve los anuncios VISIBLES para el usuario. Visible significa:
	//   - status='published' AND deleted_at IS NULL,
	//   - (expires_at IS NULL OR expires_at > now()),
	//   - existe al menos UNA audiencia que matche:
	//     target_type='global' OR
	//     target_type='role' AND target_id = ANY($2::uuid[]) OR
	//     target_type='structure' AND target_id = ANY($3::uuid[]) OR
	//     target_type='unit' AND target_id = ANY($4::uuid[]).
	// Orden: pinned DESC, published_at DESC.
	// $1 user_id se mantiene en la firma para futuro uso (ej. excluir
	// ack-eados, segmentar por usuario), aunque hoy no participa del WHERE.
	ListFeedForUser(ctx context.Context, arg ListFeedForUserParams) ([]Announcement, error)
}

var _ Querier = (*Queries)(nil)
