// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assemblies.sql

package assembliesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// --- assemblies ---

const createAssembly = `-- name: CreateAssembly :one
INSERT INTO assemblies (
    name, assembly_type, scheduled_at, voting_mode,
    quorum_required_pct, location, notes,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'draft', $8, $8
)
RETURNING id, name, assembly_type, scheduled_at, voting_mode,
          quorum_required_pct, location, notes,
          started_at, closed_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateAssemblyParams struct {
	Name              string
	AssemblyType      string
	ScheduledAt       pgtype.Timestamptz
	VotingMode        string
	QuorumRequiredPct pgtype.Numeric
	Location          *string
	Notes             *string
	CreatedBy         pgtype.UUID
}

func (q *Queries) CreateAssembly(ctx context.Context, arg CreateAssemblyParams) (Assembly, error) {
	row := q.db.QueryRow(ctx, createAssembly,
		arg.Name, arg.AssemblyType, arg.ScheduledAt, arg.VotingMode,
		arg.QuorumRequiredPct, arg.Location, arg.Notes, arg.CreatedBy,
	)
	var i Assembly
	err := row.Scan(
		&i.ID, &i.Name, &i.AssemblyType, &i.ScheduledAt, &i.VotingMode,
		&i.QuorumRequiredPct, &i.Location, &i.Notes,
		&i.StartedAt, &i.ClosedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getAssemblyByID = `-- name: GetAssemblyByID :one
SELECT id, name, assembly_type, scheduled_at, voting_mode,
       quorum_required_pct, location, notes,
       started_at, closed_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assemblies
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetAssemblyByID(ctx context.Context, id pgtype.UUID) (Assembly, error) {
	row := q.db.QueryRow(ctx, getAssemblyByID, id)
	var i Assembly
	err := row.Scan(
		&i.ID, &i.Name, &i.AssemblyType, &i.ScheduledAt, &i.VotingMode,
		&i.QuorumRequiredPct, &i.Location, &i.Notes,
		&i.StartedAt, &i.ClosedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listAssemblies = `-- name: ListAssemblies :many
SELECT id, name, assembly_type, scheduled_at, voting_mode,
       quorum_required_pct, location, notes,
       started_at, closed_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assemblies
 WHERE deleted_at IS NULL
 ORDER BY scheduled_at DESC
`

func (q *Queries) ListAssemblies(ctx context.Context) ([]Assembly, error) {
	rows, err := q.db.Query(ctx, listAssemblies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assembly
	for rows.Next() {
		var i Assembly
		if err := rows.Scan(
			&i.ID, &i.Name, &i.AssemblyType, &i.ScheduledAt, &i.VotingMode,
			&i.QuorumRequiredPct, &i.Location, &i.Notes,
			&i.StartedAt, &i.ClosedAt, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateAssemblyStatus = `-- name: UpdateAssemblyStatus :one
UPDATE assemblies
   SET status     = $1,
       started_at = COALESCE($2, started_at),
       closed_at  = COALESCE($3, closed_at),
       updated_at = now(),
       updated_by = $4,
       version    = version + 1
 WHERE id = $5
   AND version = $6
   AND deleted_at IS NULL
RETURNING id, name, assembly_type, scheduled_at, voting_mode,
          quorum_required_pct, location, notes,
          started_at, closed_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdateAssemblyStatusParams struct {
	NewStatus       string
	NewStartedAt    pgtype.Timestamptz
	NewClosedAt     pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateAssemblyStatus(ctx context.Context, arg UpdateAssemblyStatusParams) (Assembly, error) {
	row := q.db.QueryRow(ctx, updateAssemblyStatus,
		arg.NewStatus, arg.NewStartedAt, arg.NewClosedAt,
		arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Assembly
	err := row.Scan(
		&i.ID, &i.Name, &i.AssemblyType, &i.ScheduledAt, &i.VotingMode,
		&i.QuorumRequiredPct, &i.Location, &i.Notes,
		&i.StartedAt, &i.ClosedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// --- assembly_calls ---

const createAssemblyCall = `-- name: CreateAssemblyCall :one
INSERT INTO assembly_calls (
    assembly_id, channels, agenda, body_md,
    published_by, status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, 'published', $5, $5
)
RETURNING id, assembly_id, published_at, channels, agenda,
          body_md, published_by, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateAssemblyCallParams struct {
	AssemblyID  pgtype.UUID
	Channels    []byte
	Agenda      []byte
	BodyMD      *string
	PublishedBy pgtype.UUID
}

func (q *Queries) CreateAssemblyCall(ctx context.Context, arg CreateAssemblyCallParams) (AssemblyCall, error) {
	row := q.db.QueryRow(ctx, createAssemblyCall,
		arg.AssemblyID, arg.Channels, arg.Agenda, arg.BodyMD, arg.PublishedBy,
	)
	var i AssemblyCall
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.PublishedAt, &i.Channels, &i.Agenda,
		&i.BodyMD, &i.PublishedBy, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getAssemblyCallByID = `-- name: GetAssemblyCallByID :one
SELECT id, assembly_id, published_at, channels, agenda,
       body_md, published_by, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assembly_calls
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetAssemblyCallByID(ctx context.Context, id pgtype.UUID) (AssemblyCall, error) {
	row := q.db.QueryRow(ctx, getAssemblyCallByID, id)
	var i AssemblyCall
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.PublishedAt, &i.Channels, &i.Agenda,
		&i.BodyMD, &i.PublishedBy, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listAssemblyCallsByAssemblyID = `-- name: ListAssemblyCallsByAssemblyID :many
SELECT id, assembly_id, published_at, channels, agenda,
       body_md, published_by, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assembly_calls
 WHERE assembly_id = $1
   AND deleted_at IS NULL
 ORDER BY published_at DESC
`

func (q *Queries) ListAssemblyCallsByAssemblyID(ctx context.Context, assemblyID pgtype.UUID) ([]AssemblyCall, error) {
	rows, err := q.db.Query(ctx, listAssemblyCallsByAssemblyID, assemblyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssemblyCall
	for rows.Next() {
		var i AssemblyCall
		if err := rows.Scan(
			&i.ID, &i.AssemblyID, &i.PublishedAt, &i.Channels, &i.Agenda,
			&i.BodyMD, &i.PublishedBy, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// --- assembly_attendances ---

const createAssemblyAttendance = `-- name: CreateAssemblyAttendance :one
INSERT INTO assembly_attendances (
    assembly_id, unit_id, attendee_user_id, represented_by_user_id,
    coefficient_at_event, is_remote, has_voting_right, notes,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'present', $9, $9
)
RETURNING id, assembly_id, unit_id, attendee_user_id,
          represented_by_user_id, coefficient_at_event,
          arrival_at, departure_at, is_remote, has_voting_right,
          notes, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateAssemblyAttendanceParams struct {
	AssemblyID          pgtype.UUID
	UnitID              pgtype.UUID
	AttendeeUserID      pgtype.UUID
	RepresentedByUserID pgtype.UUID
	CoefficientAtEvent  pgtype.Numeric
	IsRemote            bool
	HasVotingRight      bool
	Notes               *string
	CreatedBy           pgtype.UUID
}

func (q *Queries) CreateAssemblyAttendance(ctx context.Context, arg CreateAssemblyAttendanceParams) (AssemblyAttendance, error) {
	row := q.db.QueryRow(ctx, createAssemblyAttendance,
		arg.AssemblyID, arg.UnitID, arg.AttendeeUserID, arg.RepresentedByUserID,
		arg.CoefficientAtEvent, arg.IsRemote, arg.HasVotingRight, arg.Notes,
		arg.CreatedBy,
	)
	var i AssemblyAttendance
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.UnitID, &i.AttendeeUserID,
		&i.RepresentedByUserID, &i.CoefficientAtEvent,
		&i.ArrivalAt, &i.DepartureAt, &i.IsRemote, &i.HasVotingRight,
		&i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getAssemblyAttendanceByID = `-- name: GetAssemblyAttendanceByID :one
SELECT id, assembly_id, unit_id, attendee_user_id,
       represented_by_user_id, coefficient_at_event,
       arrival_at, departure_at, is_remote, has_voting_right,
       notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assembly_attendances
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetAssemblyAttendanceByID(ctx context.Context, id pgtype.UUID) (AssemblyAttendance, error) {
	row := q.db.QueryRow(ctx, getAssemblyAttendanceByID, id)
	var i AssemblyAttendance
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.UnitID, &i.AttendeeUserID,
		&i.RepresentedByUserID, &i.CoefficientAtEvent,
		&i.ArrivalAt, &i.DepartureAt, &i.IsRemote, &i.HasVotingRight,
		&i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listAssemblyAttendancesByAssemblyID = `-- name: ListAssemblyAttendancesByAssemblyID :many
SELECT id, assembly_id, unit_id, attendee_user_id,
       represented_by_user_id, coefficient_at_event,
       arrival_at, departure_at, is_remote, has_voting_right,
       notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assembly_attendances
 WHERE assembly_id = $1
   AND deleted_at IS NULL
 ORDER BY arrival_at ASC
`

func (q *Queries) ListAssemblyAttendancesByAssemblyID(ctx context.Context, assemblyID pgtype.UUID) ([]AssemblyAttendance, error) {
	rows, err := q.db.Query(ctx, listAssemblyAttendancesByAssemblyID, assemblyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssemblyAttendance
	for rows.Next() {
		var i AssemblyAttendance
		if err := rows.Scan(
			&i.ID, &i.AssemblyID, &i.UnitID, &i.AttendeeUserID,
			&i.RepresentedByUserID, &i.CoefficientAtEvent,
			&i.ArrivalAt, &i.DepartureAt, &i.IsRemote, &i.HasVotingRight,
			&i.Notes, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const sumCoefficientByAssemblyID = `-- name: SumCoefficientByAssemblyID :one
SELECT COALESCE(SUM(coefficient_at_event), 0)::NUMERIC(7,6) AS total_coefficient
  FROM assembly_attendances
 WHERE assembly_id = $1
   AND has_voting_right = true
   AND status = 'present'
   AND deleted_at IS NULL
`

func (q *Queries) SumCoefficientByAssemblyID(ctx context.Context, assemblyID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumCoefficientByAssemblyID, assemblyID)
	var totalCoefficient pgtype.Numeric
	err := row.Scan(&totalCoefficient)
	return totalCoefficient, err
}

// --- assembly_proxies ---

const createAssemblyProxy = `-- name: CreateAssemblyProxy :one
INSERT INTO assembly_proxies (
    assembly_id, grantor_user_id, proxy_user_id, unit_id,
    document_url, document_hash,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, 'pending', $7, $7
)
RETURNING id, assembly_id, grantor_user_id, proxy_user_id, unit_id,
          document_url, document_hash,
          validated_at, validated_by, revoked_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateAssemblyProxyParams struct {
	AssemblyID    pgtype.UUID
	GrantorUserID pgtype.UUID
	ProxyUserID   pgtype.UUID
	UnitID        pgtype.UUID
	DocumentURL   *string
	DocumentHash  *string
	CreatedBy     pgtype.UUID
}

func (q *Queries) CreateAssemblyProxy(ctx context.Context, arg CreateAssemblyProxyParams) (AssemblyProxy, error) {
	row := q.db.QueryRow(ctx, createAssemblyProxy,
		arg.AssemblyID, arg.GrantorUserID, arg.ProxyUserID, arg.UnitID,
		arg.DocumentURL, arg.DocumentHash, arg.CreatedBy,
	)
	var i AssemblyProxy
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.GrantorUserID, &i.ProxyUserID, &i.UnitID,
		&i.DocumentURL, &i.DocumentHash,
		&i.ValidatedAt, &i.ValidatedBy, &i.RevokedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getAssemblyProxyByID = `-- name: GetAssemblyProxyByID :one
SELECT id, assembly_id, grantor_user_id, proxy_user_id, unit_id,
       document_url, document_hash,
       validated_at, validated_by, revoked_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assembly_proxies
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetAssemblyProxyByID(ctx context.Context, id pgtype.UUID) (AssemblyProxy, error) {
	row := q.db.QueryRow(ctx, getAssemblyProxyByID, id)
	var i AssemblyProxy
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.GrantorUserID, &i.ProxyUserID, &i.UnitID,
		&i.DocumentURL, &i.DocumentHash,
		&i.ValidatedAt, &i.ValidatedBy, &i.RevokedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listAssemblyProxiesByAssemblyID = `-- name: ListAssemblyProxiesByAssemblyID :many
SELECT id, assembly_id, grantor_user_id, proxy_user_id, unit_id,
       document_url, document_hash,
       validated_at, validated_by, revoked_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assembly_proxies
 WHERE assembly_id = $1
   AND deleted_at IS NULL
 ORDER BY created_at DESC
`

func (q *Queries) ListAssemblyProxiesByAssemblyID(ctx context.Context, assemblyID pgtype.UUID) ([]AssemblyProxy, error) {
	rows, err := q.db.Query(ctx, listAssemblyProxiesByAssemblyID, assemblyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssemblyProxy
	for rows.Next() {
		var i AssemblyProxy
		if err := rows.Scan(
			&i.ID, &i.AssemblyID, &i.GrantorUserID, &i.ProxyUserID, &i.UnitID,
			&i.DocumentURL, &i.DocumentHash,
			&i.ValidatedAt, &i.ValidatedBy, &i.RevokedAt, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countProxiesByProxyUser = `-- name: CountProxiesByProxyUser :one
SELECT COUNT(*)::INTEGER AS proxy_count
  FROM assembly_proxies
 WHERE assembly_id = $1
   AND proxy_user_id = $2
   AND status IN ('pending', 'validated')
   AND deleted_at IS NULL
`

func (q *Queries) CountProxiesByProxyUser(ctx context.Context, assemblyID pgtype.UUID, proxyUserID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countProxiesByProxyUser, assemblyID, proxyUserID)
	var proxyCount int32
	err := row.Scan(&proxyCount)
	return proxyCount, err
}

const validateAssemblyProxy = `-- name: ValidateAssemblyProxy :one
UPDATE assembly_proxies
   SET status       = 'validated',
       validated_at = now(),
       validated_by = $1,
       updated_at   = now(),
       updated_by   = $1,
       version      = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
RETURNING id, assembly_id, grantor_user_id, proxy_user_id, unit_id,
          document_url, document_hash,
          validated_at, validated_by, revoked_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type ValidateAssemblyProxyParams struct {
	ValidatedBy     pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) ValidateAssemblyProxy(ctx context.Context, arg ValidateAssemblyProxyParams) (AssemblyProxy, error) {
	row := q.db.QueryRow(ctx, validateAssemblyProxy,
		arg.ValidatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i AssemblyProxy
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.GrantorUserID, &i.ProxyUserID, &i.UnitID,
		&i.DocumentURL, &i.DocumentHash,
		&i.ValidatedAt, &i.ValidatedBy, &i.RevokedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// --- assembly_motions ---

const createAssemblyMotion = `-- name: CreateAssemblyMotion :one
INSERT INTO assembly_motions (
    assembly_id, title, description, decision_type,
    voting_method, options,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, 'draft', $7, $7
)
RETURNING id, assembly_id, title, description,
          decision_type, voting_method, options,
          opens_at, closes_at, results, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateAssemblyMotionParams struct {
	AssemblyID   pgtype.UUID
	Title        string
	Description  *string
	DecisionType string
	VotingMethod string
	Options      []byte
	CreatedBy    pgtype.UUID
}

func (q *Queries) CreateAssemblyMotion(ctx context.Context, arg CreateAssemblyMotionParams) (AssemblyMotion, error) {
	row := q.db.QueryRow(ctx, createAssemblyMotion,
		arg.AssemblyID, arg.Title, arg.Description,
		arg.DecisionType, arg.VotingMethod, arg.Options,
		arg.CreatedBy,
	)
	var i AssemblyMotion
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.Title, &i.Description,
		&i.DecisionType, &i.VotingMethod, &i.Options,
		&i.OpensAt, &i.ClosesAt, &i.Results, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getAssemblyMotionByID = `-- name: GetAssemblyMotionByID :one
SELECT id, assembly_id, title, description,
       decision_type, voting_method, options,
       opens_at, closes_at, results, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assembly_motions
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetAssemblyMotionByID(ctx context.Context, id pgtype.UUID) (AssemblyMotion, error) {
	row := q.db.QueryRow(ctx, getAssemblyMotionByID, id)
	var i AssemblyMotion
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.Title, &i.Description,
		&i.DecisionType, &i.VotingMethod, &i.Options,
		&i.OpensAt, &i.ClosesAt, &i.Results, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listAssemblyMotionsByAssemblyID = `-- name: ListAssemblyMotionsByAssemblyID :many
SELECT id, assembly_id, title, description,
       decision_type, voting_method, options,
       opens_at, closes_at, results, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM assembly_motions
 WHERE assembly_id = $1
   AND deleted_at IS NULL
 ORDER BY created_at ASC
`

func (q *Queries) ListAssemblyMotionsByAssemblyID(ctx context.Context, assemblyID pgtype.UUID) ([]AssemblyMotion, error) {
	rows, err := q.db.Query(ctx, listAssemblyMotionsByAssemblyID, assemblyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssemblyMotion
	for rows.Next() {
		var i AssemblyMotion
		if err := rows.Scan(
			&i.ID, &i.AssemblyID, &i.Title, &i.Description,
			&i.DecisionType, &i.VotingMethod, &i.Options,
			&i.OpensAt, &i.ClosesAt, &i.Results, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateAssemblyMotionStatus = `-- name: UpdateAssemblyMotionStatus :one
UPDATE assembly_motions
   SET status     = $1,
       opens_at   = COALESCE($2, opens_at),
       closes_at  = COALESCE($3, closes_at),
       results    = COALESCE($4, results),
       updated_at = now(),
       updated_by = $5,
       version    = version + 1
 WHERE id = $6
   AND version = $7
   AND deleted_at IS NULL
RETURNING id, assembly_id, title, description,
          decision_type, voting_method, options,
          opens_at, closes_at, results, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdateAssemblyMotionStatusParams struct {
	NewStatus       string
	NewOpensAt      pgtype.Timestamptz
	NewClosesAt     pgtype.Timestamptz
	NewResults      []byte
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateAssemblyMotionStatus(ctx context.Context, arg UpdateAssemblyMotionStatusParams) (AssemblyMotion, error) {
	row := q.db.QueryRow(ctx, updateAssemblyMotionStatus,
		arg.NewStatus, arg.NewOpensAt, arg.NewClosesAt, arg.NewResults,
		arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i AssemblyMotion
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.Title, &i.Description,
		&i.DecisionType, &i.VotingMethod, &i.Options,
		&i.OpensAt, &i.ClosesAt, &i.Results, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// --- votes ---

const createVote = `-- name: CreateVote :one
INSERT INTO votes (
    motion_id, voter_user_id, unit_id, coefficient_used,
    option, cast_at, prev_vote_hash, vote_hash, nonce,
    is_proxy_vote, status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    'cast', $11, $11
)
RETURNING id, motion_id, voter_user_id, unit_id, coefficient_used,
          option, cast_at, prev_vote_hash, vote_hash, nonce,
          is_proxy_vote, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateVoteParams struct {
	MotionID        pgtype.UUID
	VoterUserID     pgtype.UUID
	UnitID          pgtype.UUID
	CoefficientUsed pgtype.Numeric
	Option          string
	CastAt          pgtype.Timestamptz
	PrevVoteHash    *string
	VoteHash        string
	Nonce           string
	IsProxyVote     bool
	CreatedBy       pgtype.UUID
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote,
		arg.MotionID, arg.VoterUserID, arg.UnitID, arg.CoefficientUsed,
		arg.Option, arg.CastAt, arg.PrevVoteHash, arg.VoteHash, arg.Nonce,
		arg.IsProxyVote, arg.CreatedBy,
	)
	var i Vote
	err := row.Scan(
		&i.ID, &i.MotionID, &i.VoterUserID, &i.UnitID, &i.CoefficientUsed,
		&i.Option, &i.CastAt, &i.PrevVoteHash, &i.VoteHash, &i.Nonce,
		&i.IsProxyVote, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getVoteByID = `-- name: GetVoteByID :one
SELECT id, motion_id, voter_user_id, unit_id, coefficient_used,
       option, cast_at, prev_vote_hash, vote_hash, nonce,
       is_proxy_vote, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM votes
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetVoteByID(ctx context.Context, id pgtype.UUID) (Vote, error) {
	row := q.db.QueryRow(ctx, getVoteByID, id)
	var i Vote
	err := row.Scan(
		&i.ID, &i.MotionID, &i.VoterUserID, &i.UnitID, &i.CoefficientUsed,
		&i.Option, &i.CastAt, &i.PrevVoteHash, &i.VoteHash, &i.Nonce,
		&i.IsProxyVote, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listVotesByMotionID = `-- name: ListVotesByMotionID :many
SELECT id, motion_id, voter_user_id, unit_id, coefficient_used,
       option, cast_at, prev_vote_hash, vote_hash, nonce,
       is_proxy_vote, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM votes
 WHERE motion_id = $1
   AND deleted_at IS NULL
 ORDER BY cast_at ASC
`

func (q *Queries) ListVotesByMotionID(ctx context.Context, motionID pgtype.UUID) ([]Vote, error) {
	rows, err := q.db.Query(ctx, listVotesByMotionID, motionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID, &i.MotionID, &i.VoterUserID, &i.UnitID, &i.CoefficientUsed,
			&i.Option, &i.CastAt, &i.PrevVoteHash, &i.VoteHash, &i.Nonce,
			&i.IsProxyVote, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getActiveVoteByMotionAndUnit = `-- name: GetActiveVoteByMotionAndUnit :one
SELECT id, motion_id, voter_user_id, unit_id, coefficient_used,
       option, cast_at, prev_vote_hash, vote_hash, nonce,
       is_proxy_vote, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM votes
 WHERE motion_id = $1
   AND unit_id = $2
   AND status = 'cast'
   AND deleted_at IS NULL
 LIMIT 1
`

func (q *Queries) GetActiveVoteByMotionAndUnit(ctx context.Context, motionID pgtype.UUID, unitID pgtype.UUID) (Vote, error) {
	row := q.db.QueryRow(ctx, getActiveVoteByMotionAndUnit, motionID, unitID)
	var i Vote
	err := row.Scan(
		&i.ID, &i.MotionID, &i.VoterUserID, &i.UnitID, &i.CoefficientUsed,
		&i.Option, &i.CastAt, &i.PrevVoteHash, &i.VoteHash, &i.Nonce,
		&i.IsProxyVote, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getLastVoteHash = `-- name: GetLastVoteHash :one
SELECT vote_hash
  FROM votes
 WHERE motion_id = $1
   AND deleted_at IS NULL
 ORDER BY cast_at DESC
 LIMIT 1
`

func (q *Queries) GetLastVoteHash(ctx context.Context, motionID pgtype.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getLastVoteHash, motionID)
	var voteHash *string
	err := row.Scan(&voteHash)
	return voteHash, err
}

const voidVote = `-- name: VoidVote :exec
UPDATE votes
   SET status     = 'changed',
       updated_at = now(),
       updated_by = $1,
       version    = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
`

type VoidVoteParams struct {
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) VoidVote(ctx context.Context, arg VoidVoteParams) error {
	_, err := q.db.Exec(ctx, voidVote, arg.UpdatedBy, arg.ID, arg.ExpectedVersion)
	return err
}

// --- vote_evidence ---

const createVoteEvidence = `-- name: CreateVoteEvidence :one
INSERT INTO vote_evidence (
    vote_id, motion_id, prev_vote_hash, vote_hash,
    payload_json, client_ip, user_agent, ntp_offset_ms
) VALUES (
    $1, $2, $3, $4, $5, $6::INET, $7, $8
)
RETURNING id, vote_id, motion_id, prev_vote_hash, vote_hash,
          payload_json, client_ip, user_agent, ntp_offset_ms,
          sealed_at, created_at
`

type CreateVoteEvidenceParams struct {
	VoteID       pgtype.UUID
	MotionID     pgtype.UUID
	PrevVoteHash *string
	VoteHash     string
	PayloadJSON  []byte
	ClientIP     *string
	UserAgent    *string
	NTPOffsetMS  *int32
}

func (q *Queries) CreateVoteEvidence(ctx context.Context, arg CreateVoteEvidenceParams) (VoteEvidence, error) {
	row := q.db.QueryRow(ctx, createVoteEvidence,
		arg.VoteID, arg.MotionID, arg.PrevVoteHash, arg.VoteHash,
		arg.PayloadJSON, arg.ClientIP, arg.UserAgent, arg.NTPOffsetMS,
	)
	var i VoteEvidence
	err := row.Scan(
		&i.ID, &i.VoteID, &i.MotionID, &i.PrevVoteHash, &i.VoteHash,
		&i.PayloadJSON, &i.ClientIP, &i.UserAgent, &i.NTPOffsetMS,
		&i.SealedAt, &i.CreatedAt,
	)
	return i, err
}

const listVoteEvidenceByMotionID = `-- name: ListVoteEvidenceByMotionID :many
SELECT id, vote_id, motion_id, prev_vote_hash, vote_hash,
       payload_json, client_ip, user_agent, ntp_offset_ms,
       sealed_at, created_at
  FROM vote_evidence
 WHERE motion_id = $1
 ORDER BY sealed_at ASC
`

func (q *Queries) ListVoteEvidenceByMotionID(ctx context.Context, motionID pgtype.UUID) ([]VoteEvidence, error) {
	rows, err := q.db.Query(ctx, listVoteEvidenceByMotionID, motionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoteEvidence
	for rows.Next() {
		var i VoteEvidence
		if err := rows.Scan(
			&i.ID, &i.VoteID, &i.MotionID, &i.PrevVoteHash, &i.VoteHash,
			&i.PayloadJSON, &i.ClientIP, &i.UserAgent, &i.NTPOffsetMS,
			&i.SealedAt, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// --- acts ---

const createAct = `-- name: CreateAct :one
INSERT INTO acts (
    assembly_id, body_md, archive_until,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, 'draft', $4, $4
)
RETURNING id, assembly_id, body_md, pdf_url, pdf_hash,
          sealed_at, archive_until, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateActParams struct {
	AssemblyID   pgtype.UUID
	BodyMD       string
	ArchiveUntil pgtype.Date
	CreatedBy    pgtype.UUID
}

func (q *Queries) CreateAct(ctx context.Context, arg CreateActParams) (Act, error) {
	row := q.db.QueryRow(ctx, createAct,
		arg.AssemblyID, arg.BodyMD, arg.ArchiveUntil, arg.CreatedBy,
	)
	var i Act
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.BodyMD, &i.PDFURL, &i.PDFHash,
		&i.SealedAt, &i.ArchiveUntil, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getActByID = `-- name: GetActByID :one
SELECT id, assembly_id, body_md, pdf_url, pdf_hash,
       sealed_at, archive_until, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM acts
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetActByID(ctx context.Context, id pgtype.UUID) (Act, error) {
	row := q.db.QueryRow(ctx, getActByID, id)
	var i Act
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.BodyMD, &i.PDFURL, &i.PDFHash,
		&i.SealedAt, &i.ArchiveUntil, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getActByAssemblyID = `-- name: GetActByAssemblyID :one
SELECT id, assembly_id, body_md, pdf_url, pdf_hash,
       sealed_at, archive_until, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM acts
 WHERE assembly_id = $1
   AND deleted_at IS NULL
 LIMIT 1
`

func (q *Queries) GetActByAssemblyID(ctx context.Context, assemblyID pgtype.UUID) (Act, error) {
	row := q.db.QueryRow(ctx, getActByAssemblyID, assemblyID)
	var i Act
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.BodyMD, &i.PDFURL, &i.PDFHash,
		&i.SealedAt, &i.ArchiveUntil, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const updateActStatus = `-- name: UpdateActStatus :one
UPDATE acts
   SET status     = $1,
       sealed_at  = COALESCE($2, sealed_at),
       updated_at = now(),
       updated_by = $3,
       version    = version + 1
 WHERE id = $4
   AND version = $5
   AND deleted_at IS NULL
RETURNING id, assembly_id, body_md, pdf_url, pdf_hash,
          sealed_at, archive_until, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdateActStatusParams struct {
	NewStatus       string
	NewSealedAt     pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateActStatus(ctx context.Context, arg UpdateActStatusParams) (Act, error) {
	row := q.db.QueryRow(ctx, updateActStatus,
		arg.NewStatus, arg.NewSealedAt, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Act
	err := row.Scan(
		&i.ID, &i.AssemblyID, &i.BodyMD, &i.PDFURL, &i.PDFHash,
		&i.SealedAt, &i.ArchiveUntil, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// --- act_signatures ---

const createActSignature = `-- name: CreateActSignature :one
INSERT INTO act_signatures (
    act_id, signer_user_id, role, signature_method,
    evidence_hash, client_ip, user_agent,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6::INET, $7, 'valid', $8, $8
)
RETURNING id, act_id, signer_user_id, role, signed_at,
          signature_method, evidence_hash,
          client_ip, user_agent, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateActSignatureParams struct {
	ActID           pgtype.UUID
	SignerUserID    pgtype.UUID
	Role            string
	SignatureMethod string
	EvidenceHash    string
	ClientIP        *string
	UserAgent       *string
	CreatedBy       pgtype.UUID
}

func (q *Queries) CreateActSignature(ctx context.Context, arg CreateActSignatureParams) (ActSignature, error) {
	row := q.db.QueryRow(ctx, createActSignature,
		arg.ActID, arg.SignerUserID, arg.Role, arg.SignatureMethod,
		arg.EvidenceHash, arg.ClientIP, arg.UserAgent, arg.CreatedBy,
	)
	var i ActSignature
	err := row.Scan(
		&i.ID, &i.ActID, &i.SignerUserID, &i.Role, &i.SignedAt,
		&i.SignatureMethod, &i.EvidenceHash,
		&i.ClientIP, &i.UserAgent, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listActSignaturesByActID = `-- name: ListActSignaturesByActID :many
SELECT id, act_id, signer_user_id, role, signed_at,
       signature_method, evidence_hash,
       client_ip, user_agent, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM act_signatures
 WHERE act_id = $1
   AND deleted_at IS NULL
 ORDER BY signed_at ASC
`

func (q *Queries) ListActSignaturesByActID(ctx context.Context, actID pgtype.UUID) ([]ActSignature, error) {
	rows, err := q.db.Query(ctx, listActSignaturesByActID, actID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActSignature
	for rows.Next() {
		var i ActSignature
		if err := rows.Scan(
			&i.ID, &i.ActID, &i.SignerUserID, &i.Role, &i.SignedAt,
			&i.SignatureMethod, &i.EvidenceHash,
			&i.ClientIP, &i.UserAgent, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// --- outbox ---

const enqueueAssembliesOutboxEvent = `-- name: EnqueueAssembliesOutboxEvent :one
INSERT INTO assemblies_outbox_events (
    aggregate_id, event_type, payload, next_attempt_at, attempts
) VALUES (
    $1, $2, $3, now(), 0
)
RETURNING id, aggregate_id, event_type, payload, created_at,
          next_attempt_at, attempts, delivered_at, last_error
`

type EnqueueAssembliesOutboxEventParams struct {
	AggregateID pgtype.UUID
	EventType   string
	Payload     []byte
}

func (q *Queries) EnqueueAssembliesOutboxEvent(ctx context.Context, arg EnqueueAssembliesOutboxEventParams) (AssembliesOutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueueAssembliesOutboxEvent,
		arg.AggregateID, arg.EventType, arg.Payload,
	)
	var i AssembliesOutboxEvent
	err := row.Scan(
		&i.ID, &i.AggregateID, &i.EventType, &i.Payload, &i.CreatedAt,
		&i.NextAttemptAt, &i.Attempts, &i.DeliveredAt, &i.LastError,
	)
	return i, err
}

const lockPendingAssembliesOutboxEvents = `-- name: LockPendingAssembliesOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, created_at,
       next_attempt_at, attempts, delivered_at, last_error
  FROM assemblies_outbox_events
 WHERE delivered_at IS NULL
   AND next_attempt_at <= now()
 ORDER BY next_attempt_at ASC
 LIMIT $1
 FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockPendingAssembliesOutboxEvents(ctx context.Context, limit int32) ([]AssembliesOutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockPendingAssembliesOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssembliesOutboxEvent
	for rows.Next() {
		var i AssembliesOutboxEvent
		if err := rows.Scan(
			&i.ID, &i.AggregateID, &i.EventType, &i.Payload, &i.CreatedAt,
			&i.NextAttemptAt, &i.Attempts, &i.DeliveredAt, &i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const markAssembliesOutboxEventDelivered = `-- name: MarkAssembliesOutboxEventDelivered :exec
UPDATE assemblies_outbox_events
   SET delivered_at = now(),
       attempts     = attempts + 1,
       last_error   = NULL
 WHERE id = $1
`

func (q *Queries) MarkAssembliesOutboxEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAssembliesOutboxEventDelivered, id)
	return err
}

const markAssembliesOutboxEventFailed = `-- name: MarkAssembliesOutboxEventFailed :exec
UPDATE assemblies_outbox_events
   SET attempts        = attempts + 1,
       last_error      = $1,
       next_attempt_at = $2
 WHERE id = $3
`

type MarkAssembliesOutboxEventFailedParams struct {
	LastError     *string
	NextAttemptAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) MarkAssembliesOutboxEventFailed(ctx context.Context, arg MarkAssembliesOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markAssembliesOutboxEventFailed,
		arg.LastError, arg.NextAttemptAt, arg.ID,
	)
	return err
}
