// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package assembliesdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assembly struct {
	ID                pgtype.UUID
	Name              string
	AssemblyType      string
	ScheduledAt       pgtype.Timestamptz
	VotingMode        string
	QuorumRequiredPct pgtype.Numeric
	Location          *string
	Notes             *string
	StartedAt         pgtype.Timestamptz
	ClosedAt          pgtype.Timestamptz
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
	DeletedBy         pgtype.UUID
	Version           int32
}

type AssemblyCall struct {
	ID          pgtype.UUID
	AssemblyID  pgtype.UUID
	PublishedAt pgtype.Timestamptz
	Channels    []byte
	Agenda      []byte
	BodyMD      *string
	PublishedBy pgtype.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
}

type AssemblyAttendance struct {
	ID                  pgtype.UUID
	AssemblyID          pgtype.UUID
	UnitID              pgtype.UUID
	AttendeeUserID      pgtype.UUID
	RepresentedByUserID pgtype.UUID
	CoefficientAtEvent  pgtype.Numeric
	ArrivalAt           pgtype.Timestamptz
	DepartureAt         pgtype.Timestamptz
	IsRemote            bool
	HasVotingRight      bool
	Notes               *string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	UpdatedBy           pgtype.UUID
	DeletedBy           pgtype.UUID
	Version             int32
}

type AssemblyProxy struct {
	ID            pgtype.UUID
	AssemblyID    pgtype.UUID
	GrantorUserID pgtype.UUID
	ProxyUserID   pgtype.UUID
	UnitID        pgtype.UUID
	DocumentURL   *string
	DocumentHash  *string
	ValidatedAt   pgtype.Timestamptz
	ValidatedBy   pgtype.UUID
	RevokedAt     pgtype.Timestamptz
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	UpdatedBy     pgtype.UUID
	DeletedBy     pgtype.UUID
	Version       int32
}

type AssemblyMotion struct {
	ID           pgtype.UUID
	AssemblyID   pgtype.UUID
	Title        string
	Description  *string
	DecisionType string
	VotingMethod string
	Options      []byte
	OpensAt      pgtype.Timestamptz
	ClosesAt     pgtype.Timestamptz
	Results      []byte
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedBy    pgtype.UUID
	Version      int32
}

type Vote struct {
	ID              pgtype.UUID
	MotionID        pgtype.UUID
	VoterUserID     pgtype.UUID
	UnitID          pgtype.UUID
	CoefficientUsed pgtype.Numeric
	Option          string
	CastAt          pgtype.Timestamptz
	PrevVoteHash    *string
	VoteHash        string
	Nonce           string
	IsProxyVote     bool
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	UpdatedBy       pgtype.UUID
	DeletedBy       pgtype.UUID
	Version         int32
}

type VoteEvidence struct {
	ID           pgtype.UUID
	VoteID       pgtype.UUID
	MotionID     pgtype.UUID
	PrevVoteHash *string
	VoteHash     string
	PayloadJSON  []byte
	ClientIP     *string
	UserAgent    *string
	NTPOffsetMS  *int32
	SealedAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Act struct {
	ID           pgtype.UUID
	AssemblyID   pgtype.UUID
	BodyMD       string
	PDFURL       *string
	PDFHash      *string
	SealedAt     pgtype.Timestamptz
	ArchiveUntil pgtype.Date
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedBy    pgtype.UUID
	Version      int32
}

type ActSignature struct {
	ID              pgtype.UUID
	ActID           pgtype.UUID
	SignerUserID    pgtype.UUID
	Role            string
	SignedAt        pgtype.Timestamptz
	SignatureMethod string
	EvidenceHash    string
	ClientIP        *string
	UserAgent       *string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	UpdatedBy       pgtype.UUID
	DeletedBy       pgtype.UUID
	Version         int32
}

type AssembliesOutboxEvent struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
	Attempts      int32
	DeliveredAt   pgtype.Timestamptz
	LastError     *string
}
