// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reservationsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommonArea struct {
	ID                  pgtype.UUID
	Code                string
	Name                string
	Kind                string
	MaxCapacity         *int32
	OpeningTime         *string
	ClosingTime         *string
	SlotDurationMinutes int32
	CostPerUse          pgtype.Numeric
	SecurityDeposit     pgtype.Numeric
	RequiresApproval    bool
	IsActive            bool
	Description         *string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	UpdatedBy           pgtype.UUID
	DeletedBy           pgtype.UUID
	Version             int32
}

type ReservationBlackout struct {
	ID           pgtype.UUID
	CommonAreaID pgtype.UUID
	FromAt       pgtype.Timestamptz
	ToAt         pgtype.Timestamptz
	Reason       string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedBy    pgtype.UUID
	Version      int32
}

type Reservation struct {
	ID                pgtype.UUID
	CommonAreaID      pgtype.UUID
	UnitID            pgtype.UUID
	RequestedByUserID pgtype.UUID
	SlotStartAt       pgtype.Timestamptz
	SlotEndAt         pgtype.Timestamptz
	AttendeesCount    *int32
	Cost              pgtype.Numeric
	SecurityDeposit   pgtype.Numeric
	DepositRefunded   bool
	QrCodeHash        *string
	IdempotencyKey    *string
	Notes             *string
	ApprovedBy        pgtype.UUID
	ApprovedAt        pgtype.Timestamptz
	CancelledBy       pgtype.UUID
	CancelledAt       pgtype.Timestamptz
	ConsumedAt        pgtype.Timestamptz
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
	DeletedBy         pgtype.UUID
	Version           int32
}

type ReservationStatusHistory struct {
	ID            pgtype.UUID
	ReservationID pgtype.UUID
	FromStatus    *string
	ToStatus      string
	ChangedBy     pgtype.UUID
	Reason        *string
	ChangedAt     pgtype.Timestamptz
}

type ReservationsOutboxEvent struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
	Attempts      int32
	DeliveredAt   pgtype.Timestamptz
	LastError     *string
}
