// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package reservationsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ---------------------------------------------------------------------------
// common_areas
// ---------------------------------------------------------------------------

const createCommonArea = `-- name: CreateCommonArea :one
INSERT INTO common_areas (
    code, name, kind, max_capacity,
    opening_time, closing_time, slot_duration_minutes,
    cost_per_use, security_deposit,
    requires_approval, is_active, description,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    'active', $13, $13
)
RETURNING id, code, name, kind, max_capacity,
          opening_time, closing_time, slot_duration_minutes,
          cost_per_use, security_deposit,
          requires_approval, is_active, description,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateCommonAreaParams struct {
	Code                string
	Name                string
	Kind                string
	MaxCapacity         *int32
	OpeningTime         *string
	ClosingTime         *string
	SlotDurationMinutes int32
	CostPerUse          pgtype.Numeric
	SecurityDeposit     pgtype.Numeric
	RequiresApproval    bool
	IsActive            bool
	Description         *string
	CreatedBy           pgtype.UUID
}

func (q *Queries) CreateCommonArea(ctx context.Context, arg CreateCommonAreaParams) (CommonArea, error) {
	row := q.db.QueryRow(ctx, createCommonArea,
		arg.Code, arg.Name, arg.Kind, arg.MaxCapacity,
		arg.OpeningTime, arg.ClosingTime, arg.SlotDurationMinutes,
		arg.CostPerUse, arg.SecurityDeposit,
		arg.RequiresApproval, arg.IsActive, arg.Description,
		arg.CreatedBy,
	)
	var i CommonArea
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Kind, &i.MaxCapacity,
		&i.OpeningTime, &i.ClosingTime, &i.SlotDurationMinutes,
		&i.CostPerUse, &i.SecurityDeposit,
		&i.RequiresApproval, &i.IsActive, &i.Description,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getCommonAreaByID = `-- name: GetCommonAreaByID :one
SELECT id, code, name, kind, max_capacity,
       opening_time, closing_time, slot_duration_minutes,
       cost_per_use, security_deposit,
       requires_approval, is_active, description,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM common_areas
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetCommonAreaByID(ctx context.Context, id pgtype.UUID) (CommonArea, error) {
	row := q.db.QueryRow(ctx, getCommonAreaByID, id)
	var i CommonArea
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Kind, &i.MaxCapacity,
		&i.OpeningTime, &i.ClosingTime, &i.SlotDurationMinutes,
		&i.CostPerUse, &i.SecurityDeposit,
		&i.RequiresApproval, &i.IsActive, &i.Description,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listCommonAreas = `-- name: ListCommonAreas :many
SELECT id, code, name, kind, max_capacity,
       opening_time, closing_time, slot_duration_minutes,
       cost_per_use, security_deposit,
       requires_approval, is_active, description,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM common_areas
 WHERE deleted_at IS NULL
 ORDER BY name ASC
`

func (q *Queries) ListCommonAreas(ctx context.Context) ([]CommonArea, error) {
	rows, err := q.db.Query(ctx, listCommonAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommonArea{}
	for rows.Next() {
		var i CommonArea
		if err := rows.Scan(
			&i.ID, &i.Code, &i.Name, &i.Kind, &i.MaxCapacity,
			&i.OpeningTime, &i.ClosingTime, &i.SlotDurationMinutes,
			&i.CostPerUse, &i.SecurityDeposit,
			&i.RequiresApproval, &i.IsActive, &i.Description,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommonArea = `-- name: UpdateCommonArea :one
UPDATE common_areas
   SET code                 = $1,
       name                 = $2,
       kind                 = $3,
       max_capacity         = $4,
       opening_time         = $5,
       closing_time         = $6,
       slot_duration_minutes = $7,
       cost_per_use         = $8,
       security_deposit     = $9,
       requires_approval    = $10,
       is_active            = $11,
       description          = $12,
       status               = $13,
       updated_at           = now(),
       updated_by           = $14,
       version              = version + 1
 WHERE id = $15
   AND version = $16
   AND deleted_at IS NULL
RETURNING id, code, name, kind, max_capacity,
          opening_time, closing_time, slot_duration_minutes,
          cost_per_use, security_deposit,
          requires_approval, is_active, description,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdateCommonAreaParams struct {
	NewCode                string
	NewName                string
	NewKind                string
	NewMaxCapacity         *int32
	NewOpeningTime         *string
	NewClosingTime         *string
	NewSlotDurationMinutes int32
	NewCostPerUse          pgtype.Numeric
	NewSecurityDeposit     pgtype.Numeric
	NewRequiresApproval    bool
	NewIsActive            bool
	NewDescription         *string
	NewStatus              string
	UpdatedBy              pgtype.UUID
	ID                     pgtype.UUID
	ExpectedVersion        int32
}

func (q *Queries) UpdateCommonArea(ctx context.Context, arg UpdateCommonAreaParams) (CommonArea, error) {
	row := q.db.QueryRow(ctx, updateCommonArea,
		arg.NewCode, arg.NewName, arg.NewKind, arg.NewMaxCapacity,
		arg.NewOpeningTime, arg.NewClosingTime, arg.NewSlotDurationMinutes,
		arg.NewCostPerUse, arg.NewSecurityDeposit,
		arg.NewRequiresApproval, arg.NewIsActive, arg.NewDescription,
		arg.NewStatus, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i CommonArea
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Kind, &i.MaxCapacity,
		&i.OpeningTime, &i.ClosingTime, &i.SlotDurationMinutes,
		&i.CostPerUse, &i.SecurityDeposit,
		&i.RequiresApproval, &i.IsActive, &i.Description,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// ---------------------------------------------------------------------------
// reservation_blackouts
// ---------------------------------------------------------------------------

const createBlackout = `-- name: CreateBlackout :one
INSERT INTO reservation_blackouts (
    common_area_id, from_at, to_at, reason,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, 'active', $5, $5
)
RETURNING id, common_area_id, from_at, to_at, reason,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateBlackoutParams struct {
	CommonAreaID pgtype.UUID
	FromAt       pgtype.Timestamptz
	ToAt         pgtype.Timestamptz
	Reason       string
	CreatedBy    pgtype.UUID
}

func (q *Queries) CreateBlackout(ctx context.Context, arg CreateBlackoutParams) (ReservationBlackout, error) {
	row := q.db.QueryRow(ctx, createBlackout,
		arg.CommonAreaID, arg.FromAt, arg.ToAt, arg.Reason, arg.CreatedBy,
	)
	var i ReservationBlackout
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.FromAt, &i.ToAt, &i.Reason,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listActiveBlackoutsByCommonArea = `-- name: ListActiveBlackoutsByCommonArea :many
SELECT id, common_area_id, from_at, to_at, reason,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM reservation_blackouts
 WHERE common_area_id = $1
   AND status = 'active'
   AND deleted_at IS NULL
 ORDER BY from_at ASC
`

func (q *Queries) ListActiveBlackoutsByCommonArea(ctx context.Context, commonAreaID pgtype.UUID) ([]ReservationBlackout, error) {
	rows, err := q.db.Query(ctx, listActiveBlackoutsByCommonArea, commonAreaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationBlackout{}
	for rows.Next() {
		var i ReservationBlackout
		if err := rows.Scan(
			&i.ID, &i.CommonAreaID, &i.FromAt, &i.ToAt, &i.Reason,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlackoutsByCommonAreaAndWindow = `-- name: ListBlackoutsByCommonAreaAndWindow :many
SELECT id, common_area_id, from_at, to_at, reason,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM reservation_blackouts
 WHERE common_area_id = $1
   AND status = 'active'
   AND deleted_at IS NULL
   AND from_at < $3
   AND to_at > $2
 ORDER BY from_at ASC
`

func (q *Queries) ListBlackoutsByCommonAreaAndWindow(ctx context.Context, commonAreaID pgtype.UUID, windowStart pgtype.Timestamptz, windowEnd pgtype.Timestamptz) ([]ReservationBlackout, error) {
	rows, err := q.db.Query(ctx, listBlackoutsByCommonAreaAndWindow, commonAreaID, windowStart, windowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationBlackout{}
	for rows.Next() {
		var i ReservationBlackout
		if err := rows.Scan(
			&i.ID, &i.CommonAreaID, &i.FromAt, &i.ToAt, &i.Reason,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ---------------------------------------------------------------------------
// reservations
// ---------------------------------------------------------------------------

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
    common_area_id, unit_id, requested_by_user_id,
    slot_start_at, slot_end_at, attendees_count,
    cost, security_deposit, qr_code_hash,
    idempotency_key, notes,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $3, $3
)
RETURNING id, common_area_id, unit_id, requested_by_user_id,
          slot_start_at, slot_end_at, attendees_count,
          cost, security_deposit, deposit_refunded,
          qr_code_hash, idempotency_key, notes,
          approved_by, approved_at, cancelled_by, cancelled_at,
          consumed_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateReservationParams struct {
	CommonAreaID      pgtype.UUID
	UnitID            pgtype.UUID
	RequestedByUserID pgtype.UUID
	SlotStartAt       pgtype.Timestamptz
	SlotEndAt         pgtype.Timestamptz
	AttendeesCount    *int32
	Cost              pgtype.Numeric
	SecurityDeposit   pgtype.Numeric
	QrCodeHash        *string
	IdempotencyKey    *string
	Notes             *string
	Status            string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.CommonAreaID, arg.UnitID, arg.RequestedByUserID,
		arg.SlotStartAt, arg.SlotEndAt, arg.AttendeesCount,
		arg.Cost, arg.SecurityDeposit, arg.QrCodeHash,
		arg.IdempotencyKey, arg.Notes, arg.Status,
	)
	var i Reservation
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
		&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
		&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
		&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
		&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
		&i.ConsumedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, common_area_id, unit_id, requested_by_user_id,
       slot_start_at, slot_end_at, attendees_count,
       cost, security_deposit, deposit_refunded,
       qr_code_hash, idempotency_key, notes,
       approved_by, approved_at, cancelled_by, cancelled_at,
       consumed_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM reservations
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetReservationByID(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
		&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
		&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
		&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
		&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
		&i.ConsumedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT id, common_area_id, unit_id, requested_by_user_id,
       slot_start_at, slot_end_at, attendees_count,
       cost, security_deposit, deposit_refunded,
       qr_code_hash, idempotency_key, notes,
       approved_by, approved_at, cancelled_by, cancelled_at,
       consumed_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM reservations
 WHERE idempotency_key = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i Reservation
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
		&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
		&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
		&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
		&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
		&i.ConsumedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getReservationByQRCodeHash = `-- name: GetReservationByQRCodeHash :one
SELECT id, common_area_id, unit_id, requested_by_user_id,
       slot_start_at, slot_end_at, attendees_count,
       cost, security_deposit, deposit_refunded,
       qr_code_hash, idempotency_key, notes,
       approved_by, approved_at, cancelled_by, cancelled_at,
       consumed_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM reservations
 WHERE qr_code_hash = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetReservationByQRCodeHash(ctx context.Context, qrCodeHash *string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByQRCodeHash, qrCodeHash)
	var i Reservation
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
		&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
		&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
		&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
		&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
		&i.ConsumedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listReservations = `-- name: ListReservations :many
SELECT id, common_area_id, unit_id, requested_by_user_id,
       slot_start_at, slot_end_at, attendees_count,
       cost, security_deposit, deposit_refunded,
       qr_code_hash, idempotency_key, notes,
       approved_by, approved_at, cancelled_by, cancelled_at,
       consumed_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM reservations
 WHERE deleted_at IS NULL
 ORDER BY slot_start_at DESC
`

func (q *Queries) ListReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
			&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
			&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
			&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
			&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
			&i.ConsumedAt, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUnit = `-- name: ListReservationsByUnit :many
SELECT id, common_area_id, unit_id, requested_by_user_id,
       slot_start_at, slot_end_at, attendees_count,
       cost, security_deposit, deposit_refunded,
       qr_code_hash, idempotency_key, notes,
       approved_by, approved_at, cancelled_by, cancelled_at,
       consumed_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM reservations
 WHERE unit_id = $1
   AND deleted_at IS NULL
 ORDER BY slot_start_at DESC
`

func (q *Queries) ListReservationsByUnit(ctx context.Context, unitID pgtype.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
			&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
			&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
			&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
			&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
			&i.ConsumedAt, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByCommonAreaAndDate = `-- name: ListReservationsByCommonAreaAndDate :many
SELECT id, common_area_id, unit_id, requested_by_user_id,
       slot_start_at, slot_end_at, attendees_count,
       cost, security_deposit, deposit_refunded,
       qr_code_hash, idempotency_key, notes,
       approved_by, approved_at, cancelled_by, cancelled_at,
       consumed_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM reservations
 WHERE common_area_id = $1
   AND slot_start_at >= $2
   AND slot_start_at < $3
   AND deleted_at IS NULL
 ORDER BY slot_start_at ASC
`

func (q *Queries) ListReservationsByCommonAreaAndDate(ctx context.Context, commonAreaID pgtype.UUID, start pgtype.Timestamptz, end pgtype.Timestamptz) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByCommonAreaAndDate, commonAreaID, start, end)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
			&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
			&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
			&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
			&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
			&i.ConsumedAt, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE reservations
   SET status     = $1,
       updated_at = now(),
       updated_by = $2,
       version    = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, common_area_id, unit_id, requested_by_user_id,
          slot_start_at, slot_end_at, attendees_count,
          cost, security_deposit, deposit_refunded,
          qr_code_hash, idempotency_key, notes,
          approved_by, approved_at, cancelled_by, cancelled_at,
          consumed_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdateReservationStatusParams struct {
	NewStatus       string
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus,
		arg.NewStatus, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Reservation
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
		&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
		&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
		&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
		&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
		&i.ConsumedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const approveReservation = `-- name: ApproveReservation :one
UPDATE reservations
   SET status      = 'confirmed',
       approved_by = $1,
       approved_at = now(),
       updated_at  = now(),
       updated_by  = $1,
       version     = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
   AND status = 'pending'
RETURNING id, common_area_id, unit_id, requested_by_user_id,
          slot_start_at, slot_end_at, attendees_count,
          cost, security_deposit, deposit_refunded,
          qr_code_hash, idempotency_key, notes,
          approved_by, approved_at, cancelled_by, cancelled_at,
          consumed_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type ApproveReservationParams struct {
	ApprovedBy      pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) ApproveReservation(ctx context.Context, arg ApproveReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, approveReservation,
		arg.ApprovedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Reservation
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
		&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
		&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
		&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
		&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
		&i.ConsumedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const cancelReservation = `-- name: CancelReservation :one
UPDATE reservations
   SET status       = 'cancelled',
       cancelled_by = $1,
       cancelled_at = now(),
       updated_at   = now(),
       updated_by   = $1,
       version      = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
   AND status IN ('pending', 'confirmed')
RETURNING id, common_area_id, unit_id, requested_by_user_id,
          slot_start_at, slot_end_at, attendees_count,
          cost, security_deposit, deposit_refunded,
          qr_code_hash, idempotency_key, notes,
          approved_by, approved_at, cancelled_by, cancelled_at,
          consumed_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CancelReservationParams struct {
	CancelledBy     pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) CancelReservation(ctx context.Context, arg CancelReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, cancelReservation,
		arg.CancelledBy, arg.ID, arg.ExpectedVersion,
	)
	var i Reservation
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
		&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
		&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
		&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
		&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
		&i.ConsumedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const rejectReservation = `-- name: RejectReservation :one
UPDATE reservations
   SET status     = 'rejected',
       updated_at = now(),
       updated_by = $1,
       version    = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
   AND status = 'pending'
RETURNING id, common_area_id, unit_id, requested_by_user_id,
          slot_start_at, slot_end_at, attendees_count,
          cost, security_deposit, deposit_refunded,
          qr_code_hash, idempotency_key, notes,
          approved_by, approved_at, cancelled_by, cancelled_at,
          consumed_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type RejectReservationParams struct {
	RejectedBy      pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) RejectReservation(ctx context.Context, arg RejectReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, rejectReservation,
		arg.RejectedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Reservation
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
		&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
		&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
		&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
		&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
		&i.ConsumedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const checkinReservation = `-- name: CheckinReservation :one
UPDATE reservations
   SET status      = 'consumed',
       consumed_at = now(),
       updated_at  = now(),
       updated_by  = $1,
       version     = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
   AND status = 'confirmed'
RETURNING id, common_area_id, unit_id, requested_by_user_id,
          slot_start_at, slot_end_at, attendees_count,
          cost, security_deposit, deposit_refunded,
          qr_code_hash, idempotency_key, notes,
          approved_by, approved_at, cancelled_by, cancelled_at,
          consumed_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CheckinReservationParams struct {
	GuardBy         pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) CheckinReservation(ctx context.Context, arg CheckinReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, checkinReservation,
		arg.GuardBy, arg.ID, arg.ExpectedVersion,
	)
	var i Reservation
	err := row.Scan(
		&i.ID, &i.CommonAreaID, &i.UnitID, &i.RequestedByUserID,
		&i.SlotStartAt, &i.SlotEndAt, &i.AttendeesCount,
		&i.Cost, &i.SecurityDeposit, &i.DepositRefunded,
		&i.QrCodeHash, &i.IdempotencyKey, &i.Notes,
		&i.ApprovedBy, &i.ApprovedAt, &i.CancelledBy, &i.CancelledAt,
		&i.ConsumedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// ---------------------------------------------------------------------------
// reservation_status_history
// ---------------------------------------------------------------------------

const recordStatusHistory = `-- name: RecordStatusHistory :one
INSERT INTO reservation_status_history (
    reservation_id, from_status, to_status,
    changed_by, reason
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, reservation_id, from_status, to_status,
          changed_by, reason, changed_at
`

type RecordStatusHistoryParams struct {
	ReservationID pgtype.UUID
	FromStatus    *string
	ToStatus      string
	ChangedBy     pgtype.UUID
	Reason        *string
}

func (q *Queries) RecordStatusHistory(ctx context.Context, arg RecordStatusHistoryParams) (ReservationStatusHistory, error) {
	row := q.db.QueryRow(ctx, recordStatusHistory,
		arg.ReservationID, arg.FromStatus, arg.ToStatus,
		arg.ChangedBy, arg.Reason,
	)
	var i ReservationStatusHistory
	err := row.Scan(
		&i.ID, &i.ReservationID, &i.FromStatus, &i.ToStatus,
		&i.ChangedBy, &i.Reason, &i.ChangedAt,
	)
	return i, err
}

const listStatusHistoryByReservation = `-- name: ListStatusHistoryByReservation :many
SELECT id, reservation_id, from_status, to_status,
       changed_by, reason, changed_at
  FROM reservation_status_history
 WHERE reservation_id = $1
 ORDER BY changed_at DESC
`

func (q *Queries) ListStatusHistoryByReservation(ctx context.Context, reservationID pgtype.UUID) ([]ReservationStatusHistory, error) {
	rows, err := q.db.Query(ctx, listStatusHistoryByReservation, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationStatusHistory{}
	for rows.Next() {
		var i ReservationStatusHistory
		if err := rows.Scan(
			&i.ID, &i.ReservationID, &i.FromStatus, &i.ToStatus,
			&i.ChangedBy, &i.Reason, &i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ---------------------------------------------------------------------------
// reservations_outbox_events
// ---------------------------------------------------------------------------

const enqueueReservationOutboxEvent = `-- name: EnqueueReservationOutboxEvent :one
INSERT INTO reservations_outbox_events (
    aggregate_id, event_type, payload, next_attempt_at, attempts
) VALUES (
    $1, $2, $3, now(), 0
)
RETURNING id, aggregate_id, event_type, payload, created_at,
          next_attempt_at, attempts, delivered_at, last_error
`

type EnqueueReservationOutboxEventParams struct {
	AggregateID pgtype.UUID
	EventType   string
	Payload     []byte
}

func (q *Queries) EnqueueReservationOutboxEvent(ctx context.Context, arg EnqueueReservationOutboxEventParams) (ReservationsOutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueueReservationOutboxEvent, arg.AggregateID, arg.EventType, arg.Payload)
	var i ReservationsOutboxEvent
	err := row.Scan(
		&i.ID, &i.AggregateID, &i.EventType, &i.Payload,
		&i.CreatedAt, &i.NextAttemptAt, &i.Attempts,
		&i.DeliveredAt, &i.LastError,
	)
	return i, err
}

const lockPendingReservationOutboxEvents = `-- name: LockPendingReservationOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, created_at,
       next_attempt_at, attempts, delivered_at, last_error
  FROM reservations_outbox_events
 WHERE delivered_at IS NULL
   AND next_attempt_at <= now()
 ORDER BY next_attempt_at ASC
 LIMIT $1
 FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockPendingReservationOutboxEvents(ctx context.Context, limit int32) ([]ReservationsOutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockPendingReservationOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationsOutboxEvent{}
	for rows.Next() {
		var i ReservationsOutboxEvent
		if err := rows.Scan(
			&i.ID, &i.AggregateID, &i.EventType, &i.Payload,
			&i.CreatedAt, &i.NextAttemptAt, &i.Attempts,
			&i.DeliveredAt, &i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReservationOutboxEventDelivered = `-- name: MarkReservationOutboxEventDelivered :exec
UPDATE reservations_outbox_events
   SET delivered_at = now(),
       attempts     = attempts + 1,
       last_error   = NULL
 WHERE id = $1
`

func (q *Queries) MarkReservationOutboxEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReservationOutboxEventDelivered, id)
	return err
}

const markReservationOutboxEventFailed = `-- name: MarkReservationOutboxEventFailed :exec
UPDATE reservations_outbox_events
   SET attempts        = attempts + 1,
       last_error      = $1,
       next_attempt_at = $2
 WHERE id = $3
`

type MarkReservationOutboxEventFailedParams struct {
	LastError     *string
	NextAttemptAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) MarkReservationOutboxEventFailed(ctx context.Context, arg MarkReservationOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markReservationOutboxEventFailed, arg.LastError, arg.NextAttemptAt, arg.ID)
	return err
}
