// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveBlacklistEntry = `-- name: ArchiveBlacklistEntry :one
UPDATE blacklisted_persons
   SET status     = 'archived',
       deleted_at = now(),
       deleted_by = $1,
       updated_at = now(),
       updated_by = $1,
       version    = version + 1
 WHERE id = $2
   AND deleted_at IS NULL
RETURNING id, document_type, document_number, full_name, reason,
          reported_by_unit_id, reported_by_user_id, expires_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type ArchiveBlacklistEntryParams struct {
	DeletedBy pgtype.UUID
	ID        pgtype.UUID
}

// Soft-delete: marca la entrada como archivada.
func (q *Queries) ArchiveBlacklistEntry(ctx context.Context, arg ArchiveBlacklistEntryParams) (BlacklistedPerson, error) {
	row := q.db.QueryRow(ctx, archiveBlacklistEntry, arg.DeletedBy, arg.ID)
	var i BlacklistedPerson
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.FullName,
		&i.Reason,
		&i.ReportedByUnitID,
		&i.ReportedByUserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const closeVisitorEntry = `-- name: CloseVisitorEntry :one
UPDATE visitor_entries
   SET exit_time = now(),
       status    = 'closed',
       updated_at = now(),
       updated_by = $1,
       version   = version + 1
 WHERE id = $2
   AND deleted_at IS NULL
   AND exit_time IS NULL
   AND status = 'active'
RETURNING id, unit_id, pre_registration_id, visitor_full_name,
          visitor_document_type, visitor_document_number, photo_url,
          guard_id, entry_time, exit_time, source, notes, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CloseVisitorEntryParams struct {
	UpdatedBy pgtype.UUID
	ID        pgtype.UUID
}

// Cierra una entrada activa fijando exit_time = now() y status='closed'.
func (q *Queries) CloseVisitorEntry(ctx context.Context, arg CloseVisitorEntryParams) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, closeVisitorEntry, arg.UpdatedBy, arg.ID)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.PreRegistrationID,
		&i.VisitorFullName,
		&i.VisitorDocumentType,
		&i.VisitorDocumentNumber,
		&i.PhotoUrl,
		&i.GuardID,
		&i.EntryTime,
		&i.ExitTime,
		&i.Source,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const createBlacklistEntry = `-- name: CreateBlacklistEntry :one
INSERT INTO blacklisted_persons (
    document_type, document_number, full_name, reason,
    reported_by_unit_id, reported_by_user_id, expires_at, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'active', $8, $8
)
RETURNING id, document_type, document_number, full_name, reason,
          reported_by_unit_id, reported_by_user_id, expires_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateBlacklistEntryParams struct {
	DocumentType     string
	DocumentNumber   string
	FullName         *string
	Reason           string
	ReportedByUnitID pgtype.UUID
	ReportedByUserID pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
}

// Crea una entrada nueva en la blacklist.
func (q *Queries) CreateBlacklistEntry(ctx context.Context, arg CreateBlacklistEntryParams) (BlacklistedPerson, error) {
	row := q.db.QueryRow(ctx, createBlacklistEntry,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.FullName,
		arg.Reason,
		arg.ReportedByUnitID,
		arg.ReportedByUserID,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i BlacklistedPerson
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.FullName,
		&i.Reason,
		&i.ReportedByUnitID,
		&i.ReportedByUserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const createPreRegistration = `-- name: CreatePreRegistration :one

INSERT INTO visitor_pre_registrations (
    unit_id, created_by_user_id, visitor_full_name,
    visitor_document_type, visitor_document_number, expected_at,
    expires_at, max_uses, uses_count, qr_code_hash, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 0, $9, 'active', $2, $2
)
RETURNING id, unit_id, created_by_user_id, visitor_full_name,
          visitor_document_type, visitor_document_number, expected_at,
          expires_at, max_uses, uses_count, qr_code_hash, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreatePreRegistrationParams struct {
	UnitID                pgtype.UUID
	CreatedByUserID       pgtype.UUID
	VisitorFullName       string
	VisitorDocumentType   *string
	VisitorDocumentNumber *string
	ExpectedAt            pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	MaxUses               int32
	QrCodeHash            string
}

// ----------------------------------------------------------------------------
// visitor_pre_registrations
// ----------------------------------------------------------------------------
// Crea un pre-registro nuevo. El qr_code_hash es el sha256 del codigo plano
// generado por la capa de aplicacion (que entrega el plano UNA vez al
// cliente).
func (q *Queries) CreatePreRegistration(ctx context.Context, arg CreatePreRegistrationParams) (VisitorPreRegistration, error) {
	row := q.db.QueryRow(ctx, createPreRegistration,
		arg.UnitID,
		arg.CreatedByUserID,
		arg.VisitorFullName,
		arg.VisitorDocumentType,
		arg.VisitorDocumentNumber,
		arg.ExpectedAt,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.QrCodeHash,
	)
	var i VisitorPreRegistration
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.CreatedByUserID,
		&i.VisitorFullName,
		&i.VisitorDocumentType,
		&i.VisitorDocumentNumber,
		&i.ExpectedAt,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsesCount,
		&i.QrCodeHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const createVisitorEntry = `-- name: CreateVisitorEntry :one

INSERT INTO visitor_entries (
    unit_id, pre_registration_id, visitor_full_name,
    visitor_document_type, visitor_document_number, photo_url,
    guard_id, source, notes, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $7, $7
)
RETURNING id, unit_id, pre_registration_id, visitor_full_name,
          visitor_document_type, visitor_document_number, photo_url,
          guard_id, entry_time, exit_time, source, notes, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateVisitorEntryParams struct {
	UnitID                pgtype.UUID
	PreRegistrationID     pgtype.UUID
	VisitorFullName       string
	VisitorDocumentType   *string
	VisitorDocumentNumber string
	PhotoUrl              *string
	GuardID               pgtype.UUID
	Source                string
	Notes                 *string
	Status                string
}

// ----------------------------------------------------------------------------
// visitor_entries
// ----------------------------------------------------------------------------
// Inserta una entrada de visitante. La capa de aplicacion decide el status
// ('active' para checkin valido, 'rejected' para intento bloqueado por
// blacklist).
func (q *Queries) CreateVisitorEntry(ctx context.Context, arg CreateVisitorEntryParams) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, createVisitorEntry,
		arg.UnitID,
		arg.PreRegistrationID,
		arg.VisitorFullName,
		arg.VisitorDocumentType,
		arg.VisitorDocumentNumber,
		arg.PhotoUrl,
		arg.GuardID,
		arg.Source,
		arg.Notes,
		arg.Status,
	)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.PreRegistrationID,
		&i.VisitorFullName,
		&i.VisitorDocumentType,
		&i.VisitorDocumentNumber,
		&i.PhotoUrl,
		&i.GuardID,
		&i.EntryTime,
		&i.ExitTime,
		&i.Source,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getBlacklistByDocument = `-- name: GetBlacklistByDocument :one


SELECT id, document_type, document_number, full_name, reason,
       reported_by_unit_id, reported_by_user_id, expires_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM blacklisted_persons
 WHERE document_type = $1
   AND document_number = $2
   AND deleted_at IS NULL
   AND (expires_at IS NULL OR expires_at > now())
 LIMIT 1
`

type GetBlacklistByDocumentParams struct {
	DocumentType   string
	DocumentNumber string
}

// Queries del modulo access_control (sqlc).
//
// Convenciones:
//   - Listados excluyen filas con deleted_at IS NOT NULL.
//   - Soft-delete via marcar status='archived' y deleted_at = now().
//   - Concurrencia optimista: cada update incrementa version.
//   - Las queries de pre-registro consideran "expirado" cuando expires_at
//     es NULL o ya paso. La capa de aplicacion entrega el QR plano una
//     unica vez; aqui solo guardamos el hash sha256.
//
// ----------------------------------------------------------------------------
// blacklisted_persons
// ----------------------------------------------------------------------------
// Devuelve la entrada activa de blacklist para (document_type, document_number)
// si existe y no esta expirada. Camino caliente del checkin.
func (q *Queries) GetBlacklistByDocument(ctx context.Context, arg GetBlacklistByDocumentParams) (BlacklistedPerson, error) {
	row := q.db.QueryRow(ctx, getBlacklistByDocument, arg.DocumentType, arg.DocumentNumber)
	var i BlacklistedPerson
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.FullName,
		&i.Reason,
		&i.ReportedByUnitID,
		&i.ReportedByUserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, unit_id, pre_registration_id, visitor_full_name,
       visitor_document_type, visitor_document_number, photo_url,
       guard_id, entry_time, exit_time, source, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM visitor_entries
 WHERE id = $1
   AND deleted_at IS NULL
`

// Devuelve una entrada por id (cualquier estado, no eliminada).
func (q *Queries) GetEntryByID(ctx context.Context, id pgtype.UUID) (VisitorEntry, error) {
	row := q.db.QueryRow(ctx, getEntryByID, id)
	var i VisitorEntry
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.PreRegistrationID,
		&i.VisitorFullName,
		&i.VisitorDocumentType,
		&i.VisitorDocumentNumber,
		&i.PhotoUrl,
		&i.GuardID,
		&i.EntryTime,
		&i.ExitTime,
		&i.Source,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getPreRegistrationByQRHash = `-- name: GetPreRegistrationByQRHash :one
SELECT id, unit_id, created_by_user_id, visitor_full_name,
       visitor_document_type, visitor_document_number, expected_at,
       expires_at, max_uses, uses_count, qr_code_hash, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM visitor_pre_registrations
 WHERE qr_code_hash = $1
   AND deleted_at IS NULL
`

// Devuelve el pre-registro por hash del QR (no aplica filtro de estado;
// el caller decide).
func (q *Queries) GetPreRegistrationByQRHash(ctx context.Context, qrCodeHash string) (VisitorPreRegistration, error) {
	row := q.db.QueryRow(ctx, getPreRegistrationByQRHash, qrCodeHash)
	var i VisitorPreRegistration
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.CreatedByUserID,
		&i.VisitorFullName,
		&i.VisitorDocumentType,
		&i.VisitorDocumentNumber,
		&i.ExpectedAt,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsesCount,
		&i.QrCodeHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const incrementPreRegistrationUses = `-- name: IncrementPreRegistrationUses :one
UPDATE visitor_pre_registrations
   SET uses_count = uses_count + 1,
       status = CASE
                  WHEN uses_count + 1 >= max_uses THEN 'consumed'
                  ELSE status
                END,
       updated_at = now(),
       version = version + 1
 WHERE qr_code_hash = $1
   AND status = 'active'
   AND deleted_at IS NULL
   AND expires_at > now()
   AND uses_count < max_uses
RETURNING id, unit_id, created_by_user_id, visitor_full_name,
          visitor_document_type, visitor_document_number, expected_at,
          expires_at, max_uses, uses_count, qr_code_hash, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

// Incrementa uses_count atomicamente si el pre-registro:
//   - sigue activo,
//   - no expiro,
//   - todavia tiene cupos disponibles.
//
// Si se alcanza max_uses, marca como 'consumed'. Si no se cumple alguna
// condicion, devuelve 0 filas (el caller mapea a 410 Gone).
func (q *Queries) IncrementPreRegistrationUses(ctx context.Context, qrCodeHash string) (VisitorPreRegistration, error) {
	row := q.db.QueryRow(ctx, incrementPreRegistrationUses, qrCodeHash)
	var i VisitorPreRegistration
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.CreatedByUserID,
		&i.VisitorFullName,
		&i.VisitorDocumentType,
		&i.VisitorDocumentNumber,
		&i.ExpectedAt,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsesCount,
		&i.QrCodeHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const listActiveVisits = `-- name: ListActiveVisits :many
SELECT id, unit_id, pre_registration_id, visitor_full_name,
       visitor_document_type, visitor_document_number, photo_url,
       guard_id, entry_time, exit_time, source, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM visitor_entries
 WHERE deleted_at IS NULL
   AND exit_time IS NULL
   AND status = 'active'
 ORDER BY entry_time DESC
`

// Visitas activas: status='active', sin exit_time. Para el dashboard del
// guarda.
func (q *Queries) ListActiveVisits(ctx context.Context) ([]VisitorEntry, error) {
	rows, err := q.db.Query(ctx, listActiveVisits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VisitorEntry{}
	for rows.Next() {
		var i VisitorEntry
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.PreRegistrationID,
			&i.VisitorFullName,
			&i.VisitorDocumentType,
			&i.VisitorDocumentNumber,
			&i.PhotoUrl,
			&i.GuardID,
			&i.EntryTime,
			&i.ExitTime,
			&i.Source,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlacklist = `-- name: ListBlacklist :many
SELECT id, document_type, document_number, full_name, reason,
       reported_by_unit_id, reported_by_user_id, expires_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM blacklisted_persons
 WHERE deleted_at IS NULL
 ORDER BY created_at DESC
`

// Lista las entradas activas de blacklist (no eliminadas) ordenadas por
// created_at desc.
func (q *Queries) ListBlacklist(ctx context.Context) ([]BlacklistedPerson, error) {
	rows, err := q.db.Query(ctx, listBlacklist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlacklistedPerson{}
	for rows.Next() {
		var i BlacklistedPerson
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.FullName,
			&i.Reason,
			&i.ReportedByUnitID,
			&i.ReportedByUserID,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
