// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Soft-delete: marca la entrada como archivada.
	ArchiveBlacklistEntry(ctx context.Context, arg ArchiveBlacklistEntryParams) (BlacklistedPerson, error)
	// Cierra una entrada activa fijando exit_time = now() y status='closed'.
	CloseVisitorEntry(ctx context.Context, arg CloseVisitorEntryParams) (VisitorEntry, error)
	// Crea una entrada nueva en la blacklist.
	CreateBlacklistEntry(ctx context.Context, arg CreateBlacklistEntryParams) (BlacklistedPerson, error)
	// ----------------------------------------------------------------------------
	// visitor_pre_registrations
	// ----------------------------------------------------------------------------
	// Crea un pre-registro nuevo. El qr_code_hash es el sha256 del codigo plano
	// generado por la capa de aplicacion (que entrega el plano UNA vez al
	// cliente).
	CreatePreRegistration(ctx context.Context, arg CreatePreRegistrationParams) (VisitorPreRegistration, error)
	// ----------------------------------------------------------------------------
	// visitor_entries
	// ----------------------------------------------------------------------------
	// Inserta una entrada de visitante. La capa de aplicacion decide el status
	// ('active' para checkin valido, 'rejected' para intento bloqueado por
	// blacklist).
	CreateVisitorEntry(ctx context.Context, arg CreateVisitorEntryParams) (VisitorEntry, error)
	// Queries del modulo access_control (sqlc).
	//
	// Convenciones:
	//   * Listados excluyen filas con deleted_at IS NOT NULL.
	//   * Soft-delete via marcar status='archived' y deleted_at = now().
	//   * Concurrencia optimista: cada update incrementa version.
	//   * Las queries de pre-registro consideran "expirado" cuando expires_at
	//     es NULL o ya paso. La capa de aplicacion entrega el QR plano una
	//     unica vez; aqui solo guardamos el hash sha256.
	// ----------------------------------------------------------------------------
	// blacklisted_persons
	// ----------------------------------------------------------------------------
	// Devuelve la entrada activa de blacklist para (document_type, document_number)
	// si existe y no esta expirada. Camino caliente del checkin.
	GetBlacklistByDocument(ctx context.Context, arg GetBlacklistByDocumentParams) (BlacklistedPerson, error)
	// Devuelve una entrada por id (cualquier estado, no eliminada).
	GetEntryByID(ctx context.Context, id pgtype.UUID) (VisitorEntry, error)
	// Devuelve el pre-registro por hash del QR (no aplica filtro de estado;
	// el caller decide).
	GetPreRegistrationByQRHash(ctx context.Context, qrCodeHash string) (VisitorPreRegistration, error)
	// Incrementa uses_count atomicamente si el pre-registro:
	//   * sigue activo,
	//   * no expiro,
	//   * todavia tiene cupos disponibles.
	// Si se alcanza max_uses, marca como 'consumed'. Si no se cumple alguna
	// condicion, devuelve 0 filas (el caller mapea a 410 Gone).
	IncrementPreRegistrationUses(ctx context.Context, qrCodeHash string) (VisitorPreRegistration, error)
	// Visitas activas: status='active', sin exit_time. Para el dashboard del
	// guarda.
	ListActiveVisits(ctx context.Context) ([]VisitorEntry, error)
	// Lista las entradas activas de blacklist (no eliminadas) ordenadas por
	// created_at desc.
	ListBlacklist(ctx context.Context) ([]BlacklistedPerson, error)
}

var _ Querier = (*Queries)(nil)
