// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package peopledb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Announcement struct {
	ID                pgtype.UUID
	Title             string
	Body              string
	PublishedByUserID pgtype.UUID
	PublishedAt       pgtype.Timestamptz
	Pinned            bool
	ExpiresAt         pgtype.Timestamptz
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
	DeletedBy         pgtype.UUID
	Version           int32
}

type AnnouncementAcknowledgment struct {
	ID             pgtype.UUID
	AnnouncementID pgtype.UUID
	UserID         pgtype.UUID
	AcknowledgedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	UpdatedBy      pgtype.UUID
}

type AnnouncementAudience struct {
	ID             pgtype.UUID
	AnnouncementID pgtype.UUID
	TargetType     string
	TargetID       pgtype.UUID
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	UpdatedBy      pgtype.UUID
	DeletedBy      pgtype.UUID
}

type BlacklistedPerson struct {
	ID               pgtype.UUID
	DocumentType     string
	DocumentNumber   string
	FullName         *string
	Reason           string
	ReportedByUnitID pgtype.UUID
	ReportedByUserID pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
	DeletedBy        pgtype.UUID
	Version          int32
}

type Package struct {
	ID                  pgtype.UUID
	UnitID              pgtype.UUID
	RecipientName       string
	CategoryID          pgtype.UUID
	ReceivedEvidenceUrl *string
	Carrier             *string
	TrackingNumber      *string
	ReceivedByUserID    pgtype.UUID
	ReceivedAt          pgtype.Timestamptz
	DeliveredAt         pgtype.Timestamptz
	ReturnedAt          pgtype.Timestamptz
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	UpdatedBy           pgtype.UUID
	DeletedBy           pgtype.UUID
	Version             int32
}

type PackageCategory struct {
	ID               pgtype.UUID
	Name             string
	RequiresEvidence bool
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
	DeletedBy        pgtype.UUID
}

type PackageDeliveryEvent struct {
	ID                  pgtype.UUID
	PackageID           pgtype.UUID
	DeliveredToUserID   pgtype.UUID
	RecipientNameManual *string
	DeliveryMethod      string
	SignatureUrl        *string
	PhotoEvidenceUrl    *string
	DeliveredByUserID   pgtype.UUID
	DeliveredAt         pgtype.Timestamptz
	Notes               *string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	UpdatedBy           pgtype.UUID
	DeletedBy           pgtype.UUID
	Version             int32
}

type PackageOutboxEvent struct {
	ID            pgtype.UUID
	PackageID     pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
	Attempts      int32
	DeliveredAt   pgtype.Timestamptz
	LastError     *string
}

type Permission struct {
	ID          pgtype.UUID
	Namespace   string
	Description *string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
}

type ResidentialStructure struct {
	ID          pgtype.UUID
	Name        string
	Type        string
	ParentID    pgtype.UUID
	Description *string
	OrderIndex  int32
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
}

type Role struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	IsSystem    bool
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
}

type RolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
	GrantedAt    pgtype.Timestamptz
}

type TenantBranding struct {
	ID             pgtype.UUID
	Singleton      bool
	DisplayName    string
	LogoUrl        *string
	PrimaryColor   *string
	SecondaryColor *string
	Timezone       string
	Locale         string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	UpdatedBy      pgtype.UUID
	DeletedBy      pgtype.UUID
	Version        int32
}

type TenantSetting struct {
	ID          pgtype.UUID
	Key         string
	Value       []byte
	Description *string
	Category    *string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
}

type Unit struct {
	ID          pgtype.UUID
	StructureID pgtype.UUID
	Code        string
	Type        string
	AreaM2      pgtype.Numeric
	Bedrooms    *int32
	Coefficient pgtype.Numeric
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
}

type UnitOccupancy struct {
	ID          pgtype.UUID
	UnitID      pgtype.UUID
	UserID      pgtype.UUID
	RoleInUnit  string
	IsPrimary   bool
	MoveInDate  pgtype.Date
	MoveOutDate pgtype.Date
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
}

type UnitOwner struct {
	ID         pgtype.UUID
	UnitID     pgtype.UUID
	UserID     pgtype.UUID
	Percentage pgtype.Numeric
	SinceDate  pgtype.Date
	UntilDate  pgtype.Date
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedBy  pgtype.UUID
	DeletedBy  pgtype.UUID
	Version    int32
}

type UnitVehicleAssignment struct {
	ID        pgtype.UUID
	UnitID    pgtype.UUID
	VehicleID pgtype.UUID
	SinceDate pgtype.Date
	UntilDate pgtype.Date
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	DeletedBy pgtype.UUID
	Version   int32
}

type User struct {
	ID                  pgtype.UUID
	DocumentType        string
	DocumentNumber      string
	Names               string
	LastNames           string
	Email               *string
	Phone               *string
	PasswordHash        string
	MfaSecret           *string
	MfaEnrolledAt       pgtype.Timestamptz
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	LastLoginAt         pgtype.Timestamptz
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	UpdatedBy           pgtype.UUID
	DeletedBy           pgtype.UUID
	Version             int32
}

type UserMfaRecoveryCode struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  string
	UsedAt    pgtype.Timestamptz
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	Version   int32
}

type UserRoleAssignment struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RoleID           pgtype.UUID
	ScopeType        *string
	ScopeID          pgtype.UUID
	GrantedBy        pgtype.UUID
	GrantedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	RevocationReason *string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
	Version          int32
}

type UserSession struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	TokenHash        string
	ParentSessionID  pgtype.UUID
	Ip               *netip.Addr
	UserAgent        *string
	IssuedAt         pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	RevocationReason *string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
	Version          int32
}

type Vehicle struct {
	ID        pgtype.UUID
	Plate     string
	Type      string
	Brand     *string
	Model     *string
	Color     *string
	Year      *int32
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	DeletedBy pgtype.UUID
	Version   int32
}

type VisitorEntry struct {
	ID                    pgtype.UUID
	UnitID                pgtype.UUID
	PreRegistrationID     pgtype.UUID
	VisitorFullName       string
	VisitorDocumentType   *string
	VisitorDocumentNumber string
	PhotoUrl              *string
	GuardID               pgtype.UUID
	EntryTime             pgtype.Timestamptz
	ExitTime              pgtype.Timestamptz
	Source                string
	Notes                 *string
	Status                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	CreatedBy             pgtype.UUID
	UpdatedBy             pgtype.UUID
	DeletedBy             pgtype.UUID
	Version               int32
}

type VisitorPreRegistration struct {
	ID                    pgtype.UUID
	UnitID                pgtype.UUID
	CreatedByUserID       pgtype.UUID
	VisitorFullName       string
	VisitorDocumentType   *string
	VisitorDocumentNumber *string
	ExpectedAt            pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	MaxUses               int32
	UsesCount             int32
	QrCodeHash            string
	Status                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	CreatedBy             pgtype.UUID
	UpdatedBy             pgtype.UUID
	DeletedBy             pgtype.UUID
	Version               int32
}
