// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package peopledb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignVehicleToUnit = `-- name: AssignVehicleToUnit :one
INSERT INTO unit_vehicle_assignments (
    unit_id, vehicle_id, since_date, status,
    created_by, updated_by
) VALUES (
    $1,
    $2,
    COALESCE($3::DATE, CURRENT_DATE),
    'active',
    $4,
    $4
)
RETURNING id, unit_id, vehicle_id, since_date, until_date, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type AssignVehicleToUnitParams struct {
	UnitID    pgtype.UUID
	VehicleID pgtype.UUID
	SinceDate pgtype.Date
	CreatedBy pgtype.UUID
}

// Crea una asignacion activa de un vehiculo a una unidad. La unicidad
// (vehiculo asignado a UNA sola unidad activa) se enforza con el indice
// parcial unique de la tabla; un INSERT que la viole devolvera error 23505
// y la capa de repositorio lo mapea a ErrVehicleAlreadyAssigned.
func (q *Queries) AssignVehicleToUnit(ctx context.Context, arg AssignVehicleToUnitParams) (UnitVehicleAssignment, error) {
	row := q.db.QueryRow(ctx, assignVehicleToUnit,
		arg.UnitID,
		arg.VehicleID,
		arg.SinceDate,
		arg.CreatedBy,
	)
	var i UnitVehicleAssignment
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.VehicleID,
		&i.SinceDate,
		&i.UntilDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const createVehicle = `-- name: CreateVehicle :one

INSERT INTO vehicles (
    plate, type, brand, model, color, year, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, 'active', $7, $7
)
RETURNING id, plate, type, brand, model, color, year, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateVehicleParams struct {
	Plate     string
	Type      string
	Brand     *string
	Model     *string
	Color     *string
	Year      *int32
	CreatedBy pgtype.UUID
}

// Queries del modulo people (sqlc).
//
// Convenciones:
//   - Listados excluyen filas con deleted_at IS NOT NULL.
//   - La placa se persiste ya normalizada (uppercase + trim) por la capa
//     de aplicacion; las queries no transforman la entrada.
//   - Soft-delete via marcar status='archived' y deleted_at = now().
//   - Concurrencia optimista: cada update incrementa version.
//
// Crea un vehiculo nuevo. La placa se asume ya normalizada (upper+trim).
func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.Plate,
		arg.Type,
		arg.Brand,
		arg.Model,
		arg.Color,
		arg.Year,
		arg.CreatedBy,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.Type,
		&i.Brand,
		&i.Model,
		&i.Color,
		&i.Year,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const endVehicleAssignment = `-- name: EndVehicleAssignment :one
UPDATE unit_vehicle_assignments
   SET until_date = COALESCE($1::DATE, CURRENT_DATE),
       updated_at = now(),
       updated_by = $2,
       version    = version + 1
 WHERE id = $3
   AND deleted_at IS NULL
   AND until_date IS NULL
RETURNING id, unit_id, vehicle_id, since_date, until_date, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type EndVehicleAssignmentParams struct {
	UntilDate pgtype.Date
	UpdatedBy pgtype.UUID
	ID        pgtype.UUID
}

// Cierra una asignacion fijando until_date = CURRENT_DATE (o el provisto).
// Solo afecta filas activas (sin until_date).
func (q *Queries) EndVehicleAssignment(ctx context.Context, arg EndVehicleAssignmentParams) (UnitVehicleAssignment, error) {
	row := q.db.QueryRow(ctx, endVehicleAssignment, arg.UntilDate, arg.UpdatedBy, arg.ID)
	var i UnitVehicleAssignment
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.VehicleID,
		&i.SinceDate,
		&i.UntilDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, plate, type, brand, model, color, year, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM vehicles
 WHERE id = $1
   AND deleted_at IS NULL
`

// Un vehiculo por id (solo activos / no eliminados).
func (q *Queries) GetVehicleByID(ctx context.Context, id pgtype.UUID) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.Type,
		&i.Brand,
		&i.Model,
		&i.Color,
		&i.Year,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getVehicleByPlate = `-- name: GetVehicleByPlate :one
SELECT id, plate, type, brand, model, color, year, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM vehicles
 WHERE plate = $1
   AND deleted_at IS NULL
`

// Un vehiculo por placa (la placa se asume ya normalizada).
func (q *Queries) GetVehicleByPlate(ctx context.Context, plate string) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByPlate, plate)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.Type,
		&i.Brand,
		&i.Model,
		&i.Color,
		&i.Year,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const listActiveAssignmentsByUnit = `-- name: ListActiveAssignmentsByUnit :many
SELECT a.id, a.unit_id, a.vehicle_id, a.since_date, a.until_date, a.status,
       a.created_at, a.updated_at, a.deleted_at,
       a.created_by, a.updated_by, a.deleted_by, a.version,
       v.plate, v.type AS vehicle_type, v.brand, v.model, v.color, v.year
  FROM unit_vehicle_assignments a
  JOIN vehicles v ON v.id = a.vehicle_id
 WHERE a.unit_id = $1
   AND a.deleted_at IS NULL
   AND a.until_date IS NULL
 ORDER BY a.since_date DESC, a.created_at DESC
`

type ListActiveAssignmentsByUnitRow struct {
	ID          pgtype.UUID
	UnitID      pgtype.UUID
	VehicleID   pgtype.UUID
	SinceDate   pgtype.Date
	UntilDate   pgtype.Date
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
	Plate       string
	VehicleType string
	Brand       *string
	Model       *string
	Color       *string
	Year        *int32
}

// Lista asignaciones activas (sin until_date) de una unidad, junto con
// los datos del vehiculo asociado para evitar un round-trip extra.
func (q *Queries) ListActiveAssignmentsByUnit(ctx context.Context, unitID pgtype.UUID) ([]ListActiveAssignmentsByUnitRow, error) {
	rows, err := q.db.Query(ctx, listActiveAssignmentsByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAssignmentsByUnitRow{}
	for rows.Next() {
		var i ListActiveAssignmentsByUnitRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.VehicleID,
			&i.SinceDate,
			&i.UntilDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
			&i.Plate,
			&i.VehicleType,
			&i.Brand,
			&i.Model,
			&i.Color,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVehicles = `-- name: ListAllVehicles :many
SELECT id, plate, type, brand, model, color, year, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM vehicles
 WHERE deleted_at IS NULL
 ORDER BY plate
`

// Lista todos los vehiculos activos ordenados por placa.
func (q *Queries) ListAllVehicles(ctx context.Context) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listAllVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.Plate,
			&i.Type,
			&i.Brand,
			&i.Model,
			&i.Color,
			&i.Year,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
