// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package peopledb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Crea una asignacion activa de un vehiculo a una unidad. La unicidad
	// (vehiculo asignado a UNA sola unidad activa) se enforza con el indice
	// parcial unique de la tabla; un INSERT que la viole devolvera error 23505
	// y la capa de repositorio lo mapea a ErrVehicleAlreadyAssigned.
	AssignVehicleToUnit(ctx context.Context, arg AssignVehicleToUnitParams) (UnitVehicleAssignment, error)
	// Queries del modulo people (sqlc).
	//
	// Convenciones:
	//   * Listados excluyen filas con deleted_at IS NOT NULL.
	//   * La placa se persiste ya normalizada (uppercase + trim) por la capa
	//     de aplicacion; las queries no transforman la entrada.
	//   * Soft-delete via marcar status='archived' y deleted_at = now().
	//   * Concurrencia optimista: cada update incrementa version.
	// Crea un vehiculo nuevo. La placa se asume ya normalizada (upper+trim).
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	// Cierra una asignacion fijando until_date = CURRENT_DATE (o el provisto).
	// Solo afecta filas activas (sin until_date).
	EndVehicleAssignment(ctx context.Context, arg EndVehicleAssignmentParams) (UnitVehicleAssignment, error)
	// Un vehiculo por id (solo activos / no eliminados).
	GetVehicleByID(ctx context.Context, id pgtype.UUID) (Vehicle, error)
	// Un vehiculo por placa (la placa se asume ya normalizada).
	GetVehicleByPlate(ctx context.Context, plate string) (Vehicle, error)
	// Lista asignaciones activas (sin until_date) de una unidad, junto con
	// los datos del vehiculo asociado para evitar un round-trip extra.
	ListActiveAssignmentsByUnit(ctx context.Context, unitID pgtype.UUID) ([]ListActiveAssignmentsByUnitRow, error)
	// Lista todos los vehiculos activos ordenados por placa.
	ListAllVehicles(ctx context.Context) ([]Vehicle, error)
}

var _ Querier = (*Queries)(nil)
