// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantcfgdb

import (
	"context"
)

type Querier interface {
	// Soft-delete: marca la setting como archived.
	ArchiveSetting(ctx context.Context, arg ArchiveSettingParams) (TenantSetting, error)
	// Total de settings activos para paginacion.
	CountSettings(ctx context.Context, category *string) (int64, error)
	// Devuelve la unica fila singleton de branding del tenant.
	GetBranding(ctx context.Context) (TenantBranding, error)
	// Una setting por key (solo activas).
	GetSetting(ctx context.Context, key string) (TenantSetting, error)
	// Queries del modulo tenant_config (sqlc).
	//
	// Convenciones:
	//   * Listados excluyen filas con deleted_at IS NOT NULL.
	//   * Branding es singleton: GetBranding devuelve la unica fila vigente.
	//   * Soft-delete via marcar status='archived' y deleted_at = now().
	//   * Concurrencia optimista: cada update incrementa version y compara
	//     contra el version provisto.
	// Lista paginada de settings activos. Si @category es NULL/vacio, no
	// filtra por categoria.
	ListSettings(ctx context.Context, arg ListSettingsParams) ([]TenantSetting, error)
	// Actualiza la fila singleton. Concurrencia optimista por version.
	UpdateBranding(ctx context.Context, arg UpdateBrandingParams) (TenantBranding, error)
	// Inserta o actualiza una setting por key. Si existia, incrementa version.
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (TenantSetting, error)
}

var _ Querier = (*Queries)(nil)
