// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_config.sql

package tenantcfgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveSetting = `-- name: ArchiveSetting :one
UPDATE tenant_settings
   SET status     = 'archived',
       deleted_at = now(),
       deleted_by = $2,
       updated_at = now(),
       updated_by = $2,
       version    = version + 1
 WHERE key = $1
   AND deleted_at IS NULL
RETURNING id, key, value, description, category, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type ArchiveSettingParams struct {
	Key       string
	DeletedBy pgtype.UUID
}

// Soft-delete: marca la setting como archived.
func (q *Queries) ArchiveSetting(ctx context.Context, arg ArchiveSettingParams) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, archiveSetting, arg.Key, arg.DeletedBy)
	var i TenantSetting
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const countSettings = `-- name: CountSettings :one
SELECT COUNT(*)
  FROM tenant_settings
 WHERE deleted_at IS NULL
   AND ($1::TEXT IS NULL OR category = $1::TEXT)
`

// Total de settings activos para paginacion.
func (q *Queries) CountSettings(ctx context.Context, category *string) (int64, error) {
	row := q.db.QueryRow(ctx, countSettings, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBranding = `-- name: GetBranding :one
SELECT id, singleton, display_name, logo_url, primary_color, secondary_color,
       timezone, locale, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM tenant_branding
 WHERE deleted_at IS NULL
 LIMIT 1
`

// Devuelve la unica fila singleton de branding del tenant.
func (q *Queries) GetBranding(ctx context.Context) (TenantBranding, error) {
	row := q.db.QueryRow(ctx, getBranding)
	var i TenantBranding
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.DisplayName,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.Timezone,
		&i.Locale,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT id, key, value, description, category, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM tenant_settings
 WHERE key = $1
   AND deleted_at IS NULL
`

// Una setting por key (solo activas).
func (q *Queries) GetSetting(ctx context.Context, key string) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i TenantSetting
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many

SELECT id, key, value, description, category, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM tenant_settings
 WHERE deleted_at IS NULL
   AND ($3::TEXT IS NULL OR category = $3::TEXT)
 ORDER BY category NULLS LAST, key
 LIMIT $1 OFFSET $2
`

type ListSettingsParams struct {
	Limit    int32
	Offset   int32
	Category *string
}

// Queries del modulo tenant_config (sqlc).
//
// Convenciones:
//   - Listados excluyen filas con deleted_at IS NOT NULL.
//   - Branding es singleton: GetBranding devuelve la unica fila vigente.
//   - Soft-delete via marcar status='archived' y deleted_at = now().
//   - Concurrencia optimista: cada update incrementa version y compara
//     contra el version provisto.
//
// Lista paginada de settings activos. Si @category es NULL/vacio, no
// filtra por categoria.
func (q *Queries) ListSettings(ctx context.Context, arg ListSettingsParams) ([]TenantSetting, error) {
	rows, err := q.db.Query(ctx, listSettings, arg.Limit, arg.Offset, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantSetting{}
	for rows.Next() {
		var i TenantSetting
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranding = `-- name: UpdateBranding :one
UPDATE tenant_branding
   SET display_name    = $1,
       logo_url        = $2,
       primary_color   = $3,
       secondary_color = $4,
       timezone        = $5,
       locale          = $6,
       updated_at      = now(),
       updated_by      = $7,
       version         = version + 1
 WHERE singleton = TRUE
   AND deleted_at IS NULL
   AND version = $8
RETURNING id, singleton, display_name, logo_url, primary_color, secondary_color,
          timezone, locale, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdateBrandingParams struct {
	DisplayName    string
	LogoUrl        *string
	PrimaryColor   *string
	SecondaryColor *string
	Timezone       string
	Locale         string
	UpdatedBy      pgtype.UUID
	Version        int32
}

// Actualiza la fila singleton. Concurrencia optimista por version.
func (q *Queries) UpdateBranding(ctx context.Context, arg UpdateBrandingParams) (TenantBranding, error) {
	row := q.db.QueryRow(ctx, updateBranding,
		arg.DisplayName,
		arg.LogoUrl,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.Timezone,
		arg.Locale,
		arg.UpdatedBy,
		arg.Version,
	)
	var i TenantBranding
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.DisplayName,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.Timezone,
		&i.Locale,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO tenant_settings (key, value, description, category, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, 'active', $5, $5)
ON CONFLICT (key) DO UPDATE
   SET value       = EXCLUDED.value,
       description = COALESCE(EXCLUDED.description, tenant_settings.description),
       category    = COALESCE(EXCLUDED.category,    tenant_settings.category),
       status      = 'active',
       deleted_at  = NULL,
       deleted_by  = NULL,
       updated_at  = now(),
       updated_by  = EXCLUDED.updated_by,
       version     = tenant_settings.version + 1
RETURNING id, key, value, description, category, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpsertSettingParams struct {
	Key         string
	Value       []byte
	Description *string
	Category    *string
	CreatedBy   pgtype.UUID
}

// Inserta o actualiza una setting por key. Si existia, incrementa version.
func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, upsertSetting,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.Category,
		arg.CreatedBy,
	)
	var i TenantSetting
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}
