// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package superadmindb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignTenantToAdministrator(ctx context.Context, arg AssignTenantToAdministratorParams) error
	CreateAdministrator(ctx context.Context, arg CreateAdministratorParams) (PlatformAdministrator, error)
	// Queries del modulo superadmin (DB central).
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteTenant(ctx context.Context, id pgtype.UUID) error
	GetAdministratorByID(ctx context.Context, id pgtype.UUID) (PlatformAdministrator, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	ListAdministrators(ctx context.Context) ([]PlatformAdministrator, error)
	ListTenantsByAdministrator(ctx context.Context, administratorID pgtype.UUID) ([]Tenant, error)
	SearchPlatformUsersByDocument(ctx context.Context, arg SearchPlatformUsersByDocumentParams) ([]PlatformUser, error)
	SearchPlatformUsersByEmail(ctx context.Context, dollar_1 *string) ([]PlatformUser, error)
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error
}

var _ Querier = (*Queries)(nil)
