// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: superadmin.sql

package superadmindb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTenantToAdministrator = `-- name: AssignTenantToAdministrator :exec
UPDATE tenants
SET administrator_id = $2,
    updated_at = now()
WHERE id = $1
`

type AssignTenantToAdministratorParams struct {
	ID              pgtype.UUID
	AdministratorID pgtype.UUID
}

func (q *Queries) AssignTenantToAdministrator(ctx context.Context, arg AssignTenantToAdministratorParams) error {
	_, err := q.db.Exec(ctx, assignTenantToAdministrator, arg.ID, arg.AdministratorID)
	return err
}

const createAdministrator = `-- name: CreateAdministrator :one
INSERT INTO platform_administrators (
    name, legal_id, contact_email, contact_phone, status
)
VALUES ($1, $2, $3, $4, COALESCE($5, 'active'))
RETURNING id, name, legal_id, contact_email, contact_phone, status, created_at, updated_at
`

type CreateAdministratorParams struct {
	Name         string
	LegalID      *string
	ContactEmail *string
	ContactPhone *string
	Column5      interface{}
}

func (q *Queries) CreateAdministrator(ctx context.Context, arg CreateAdministratorParams) (PlatformAdministrator, error) {
	row := q.db.QueryRow(ctx, createAdministrator,
		arg.Name,
		arg.LegalID,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Column5,
	)
	var i PlatformAdministrator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LegalID,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (
    slug, display_name, database_url, plan, status,
    administrator_id, logo_url, primary_color,
    timezone, country, currency, expected_units, activated_at
)
VALUES (
    $1, $2, $3, COALESCE($4, 'pilot'), COALESCE($5, 'provisioning'),
    $6, $7, $8,
    COALESCE($9, 'America/Bogota'), COALESCE($10, 'CO'),
    COALESCE($11, 'COP'), $12, $13
)
RETURNING id, slug, display_name, database_url, status, plan, created_at, updated_at, activated_at, suspended_at, administrator_id, logo_url, primary_color, timezone, country, currency, expected_units
`

type CreateTenantParams struct {
	Slug            string
	DisplayName     string
	DatabaseUrl     string
	Column4         interface{}
	Column5         interface{}
	AdministratorID pgtype.UUID
	LogoUrl         *string
	PrimaryColor    *string
	Column9         interface{}
	Column10        interface{}
	Column11        interface{}
	ExpectedUnits   *int32
	ActivatedAt     pgtype.Timestamptz
}

// Queries del modulo superadmin (DB central).
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Slug,
		arg.DisplayName,
		arg.DatabaseUrl,
		arg.Column4,
		arg.Column5,
		arg.AdministratorID,
		arg.LogoUrl,
		arg.PrimaryColor,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.ExpectedUnits,
		arg.ActivatedAt,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.DatabaseUrl,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.AdministratorID,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Timezone,
		&i.Country,
		&i.Currency,
		&i.ExpectedUnits,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants
WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getAdministratorByID = `-- name: GetAdministratorByID :one
SELECT id, name, legal_id, contact_email, contact_phone, status, created_at, updated_at
FROM platform_administrators
WHERE id = $1
`

func (q *Queries) GetAdministratorByID(ctx context.Context, id pgtype.UUID) (PlatformAdministrator, error) {
	row := q.db.QueryRow(ctx, getAdministratorByID, id)
	var i PlatformAdministrator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LegalID,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO platform_audit_logs (
    actor_user_id, action, target_type, target_id, metadata, ip, user_agent
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	ActorUserID pgtype.UUID
	Action      string
	TargetType  *string
	TargetID    pgtype.UUID
	Metadata    []byte
	Ip          *netip.Addr
	UserAgent   *string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const listAdministrators = `-- name: ListAdministrators :many
SELECT id, name, legal_id, contact_email, contact_phone, status, created_at, updated_at
FROM platform_administrators
WHERE status != 'inactive'
ORDER BY name
`

func (q *Queries) ListAdministrators(ctx context.Context) ([]PlatformAdministrator, error) {
	rows, err := q.db.Query(ctx, listAdministrators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAdministrator{}
	for rows.Next() {
		var i PlatformAdministrator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LegalID,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsByAdministrator = `-- name: ListTenantsByAdministrator :many
SELECT id, slug, display_name, database_url, status, plan, created_at, updated_at, activated_at, suspended_at, administrator_id, logo_url, primary_color, timezone, country, currency, expected_units
FROM tenants
WHERE administrator_id = $1
  AND status != 'archived'
ORDER BY display_name
`

func (q *Queries) ListTenantsByAdministrator(ctx context.Context, administratorID pgtype.UUID) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsByAdministrator, administratorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.DatabaseUrl,
			&i.Status,
			&i.Plan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivatedAt,
			&i.SuspendedAt,
			&i.AdministratorID,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.Timezone,
			&i.Country,
			&i.Currency,
			&i.ExpectedUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlatformUsersByDocument = `-- name: SearchPlatformUsersByDocument :many
SELECT id, document_type, document_number, names, last_names, email, phone, photo_url, password_hash, mfa_secret, mfa_enrolled_at, public_code, failed_login_attempts, locked_until, last_login_at, status, created_at, updated_at, deleted_at
FROM platform_users
WHERE document_type = $1
  AND document_number LIKE $2 || '%'
  AND deleted_at IS NULL
ORDER BY last_names, names
LIMIT 50
`

type SearchPlatformUsersByDocumentParams struct {
	DocumentType string
	Column2      *string
}

func (q *Queries) SearchPlatformUsersByDocument(ctx context.Context, arg SearchPlatformUsersByDocumentParams) ([]PlatformUser, error) {
	rows, err := q.db.Query(ctx, searchPlatformUsersByDocument, arg.DocumentType, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformUser{}
	for rows.Next() {
		var i PlatformUser
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Names,
			&i.LastNames,
			&i.Email,
			&i.Phone,
			&i.PhotoUrl,
			&i.PasswordHash,
			&i.MfaSecret,
			&i.MfaEnrolledAt,
			&i.PublicCode,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlatformUsersByEmail = `-- name: SearchPlatformUsersByEmail :many
SELECT id, document_type, document_number, names, last_names, email, phone, photo_url, password_hash, mfa_secret, mfa_enrolled_at, public_code, failed_login_attempts, locked_until, last_login_at, status, created_at, updated_at, deleted_at
FROM platform_users
WHERE lower(email) LIKE lower('%' || $1 || '%')
  AND deleted_at IS NULL
ORDER BY email
LIMIT 50
`

func (q *Queries) SearchPlatformUsersByEmail(ctx context.Context, dollar_1 *string) ([]PlatformUser, error) {
	rows, err := q.db.Query(ctx, searchPlatformUsersByEmail, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformUser{}
	for rows.Next() {
		var i PlatformUser
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Names,
			&i.LastNames,
			&i.Email,
			&i.Phone,
			&i.PhotoUrl,
			&i.PasswordHash,
			&i.MfaSecret,
			&i.MfaEnrolledAt,
			&i.PublicCode,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE tenants
SET status = $2,
    activated_at = CASE
        WHEN $2 = 'active' AND activated_at IS NULL THEN now()
        ELSE activated_at
    END,
    suspended_at = CASE
        WHEN $2 = 'suspended' THEN now()
        ELSE suspended_at
    END,
    updated_at = now()
WHERE id = $1
`

type UpdateTenantStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error {
	_, err := q.db.Exec(ctx, updateTenantStatus, arg.ID, arg.Status)
	return err
}
