// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package financedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChartOfAccount struct {
	ID          pgtype.UUID
	Code        string
	Name        string
	AccountType string
	ParentID    pgtype.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
}

type CostCenter struct {
	ID        pgtype.UUID
	Code      string
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	DeletedBy pgtype.UUID
	Version   int32
}

type BillingAccount struct {
	ID           pgtype.UUID
	UnitID       pgtype.UUID
	HolderUserID pgtype.UUID
	OpenedAt     pgtype.Timestamptz
	ClosedAt     pgtype.Timestamptz
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedBy    pgtype.UUID
	Version      int32
}

type Charge struct {
	ID               pgtype.UUID
	BillingAccountID pgtype.UUID
	Concept          string
	PeriodYear       *int32
	PeriodMonth      *int32
	Amount           pgtype.Numeric
	Balance          pgtype.Numeric
	DueDate          pgtype.Date
	CostCenterID     pgtype.UUID
	AccountID        pgtype.UUID
	IdempotencyKey   *string
	Description      *string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
	DeletedBy        pgtype.UUID
	Version          int32
}

type Payment struct {
	ID                pgtype.UUID
	BillingAccountID  pgtype.UUID
	PayerUserID       pgtype.UUID
	MethodCode        string
	Gateway           *string
	GatewayTxnID      *string
	IdempotencyKey    *string
	Amount            pgtype.Numeric
	Currency          string
	UnallocatedAmount pgtype.Numeric
	CapturedAt        pgtype.Timestamptz
	SettledAt         pgtype.Timestamptz
	FailureReason     *string
	ReceiptNumber     *string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
	DeletedBy         pgtype.UUID
	Version           int32
}

type PaymentAllocation struct {
	ID        pgtype.UUID
	PaymentID pgtype.UUID
	ChargeID  pgtype.UUID
	Amount    pgtype.Numeric
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	DeletedBy pgtype.UUID
	Version   int32
}

type PaymentReversal struct {
	ID          pgtype.UUID
	PaymentID   pgtype.UUID
	Reason      string
	RequestedBy pgtype.UUID
	RequestedAt pgtype.Timestamptz
	ApprovedBy  pgtype.UUID
	ApprovedAt  pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	DeletedBy   pgtype.UUID
	Version     int32
}

type PeriodClosure struct {
	ID           pgtype.UUID
	PeriodYear   int32
	PeriodMonth  int32
	ClosedSoftAt pgtype.Timestamptz
	ClosedHardAt pgtype.Timestamptz
	ClosedBy     pgtype.UUID
	Notes        *string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedBy    pgtype.UUID
	Version      int32
}

type PaymentWebhookIdempotency struct {
	ID             pgtype.UUID
	Gateway        string
	IdempotencyKey string
	PayloadHash    *string
	ReceivedAt     pgtype.Timestamptz
	ProcessedAt    pgtype.Timestamptz
	PaymentID      pgtype.UUID
	LastError      *string
}

type FinanceOutboxEvent struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
	Attempts      int32
	DeliveredAt   pgtype.Timestamptz
	LastError     *string
}
