// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package packagesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPackage = `-- name: CreatePackage :one

INSERT INTO packages (
    unit_id, recipient_name, category_id, received_evidence_url,
    carrier, tracking_number, received_by_user_id, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'received', $7, $7
)
RETURNING id, unit_id, recipient_name, category_id, received_evidence_url,
          carrier, tracking_number, received_by_user_id, received_at,
          delivered_at, returned_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreatePackageParams struct {
	UnitID              pgtype.UUID
	RecipientName       string
	CategoryID          pgtype.UUID
	ReceivedEvidenceUrl *string
	Carrier             *string
	TrackingNumber      *string
	ReceivedByUserID    pgtype.UUID
}

// ----------------------------------------------------------------------------
// packages
// ----------------------------------------------------------------------------
// Crea un paquete nuevo en estado 'received'.
func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, createPackage,
		arg.UnitID,
		arg.RecipientName,
		arg.CategoryID,
		arg.ReceivedEvidenceUrl,
		arg.Carrier,
		arg.TrackingNumber,
		arg.ReceivedByUserID,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.RecipientName,
		&i.CategoryID,
		&i.ReceivedEvidenceUrl,
		&i.Carrier,
		&i.TrackingNumber,
		&i.ReceivedByUserID,
		&i.ReceivedAt,
		&i.DeliveredAt,
		&i.ReturnedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :one

INSERT INTO package_outbox_events (
    package_id, event_type, payload, next_attempt_at, attempts
) VALUES (
    $1, $2, $3, now(), 0
)
RETURNING id, package_id, event_type, payload, created_at,
          next_attempt_at, attempts, delivered_at, last_error
`

type EnqueueOutboxEventParams struct {
	PackageID pgtype.UUID
	EventType string
	Payload   []byte
}

// ----------------------------------------------------------------------------
// package_outbox_events
// ----------------------------------------------------------------------------
// Inserta un evento en el outbox modulo-local.
func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) (PackageOutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueueOutboxEvent, arg.PackageID, arg.EventType, arg.Payload)
	var i PackageOutboxEvent
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.NextAttemptAt,
		&i.Attempts,
		&i.DeliveredAt,
		&i.LastError,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, requires_evidence, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
  FROM package_categories
 WHERE id = $1
   AND deleted_at IS NULL
 LIMIT 1
`

// Devuelve una categoria por id (cualquier estado).
func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (PackageCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i PackageCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RequiresEvidence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, requires_evidence, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
  FROM package_categories
 WHERE name = $1
   AND deleted_at IS NULL
 LIMIT 1
`

// Devuelve una categoria activa por nombre exacto.
func (q *Queries) GetCategoryByName(ctx context.Context, name string) (PackageCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i PackageCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RequiresEvidence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT id, unit_id, recipient_name, category_id, received_evidence_url,
       carrier, tracking_number, received_by_user_id, received_at,
       delivered_at, returned_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM packages
 WHERE id = $1
   AND deleted_at IS NULL
`

// Devuelve un paquete por id (no soft-deleted).
func (q *Queries) GetPackageByID(ctx context.Context, id pgtype.UUID) (Package, error) {
	row := q.db.QueryRow(ctx, getPackageByID, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.RecipientName,
		&i.CategoryID,
		&i.ReceivedEvidenceUrl,
		&i.Carrier,
		&i.TrackingNumber,
		&i.ReceivedByUserID,
		&i.ReceivedAt,
		&i.DeliveredAt,
		&i.ReturnedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many


SELECT id, name, requires_evidence, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
  FROM package_categories
 WHERE deleted_at IS NULL
 ORDER BY name ASC
`

// Queries del modulo packages (sqlc).
//
// Convenciones:
//   - Listados excluyen filas con deleted_at IS NOT NULL.
//   - Concurrencia optimista: UpdatePackageStatus usa WHERE id=$1 AND
//     version=$2; cualquier UPDATE incrementa version.
//   - Outbox modulo-local: el worker bloquea con FOR UPDATE SKIP LOCKED
//     para procesar en paralelo sin doble consumo.
//
// ----------------------------------------------------------------------------
// package_categories
// ----------------------------------------------------------------------------
// Devuelve las categorias activas, orden alfabetico.
func (q *Queries) ListCategories(ctx context.Context) ([]PackageCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageCategory{}
	for rows.Next() {
		var i PackageCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RequiresEvidence,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryEventsByPackage = `-- name: ListDeliveryEventsByPackage :many
SELECT id, package_id, delivered_to_user_id, recipient_name_manual,
       delivery_method, signature_url, photo_evidence_url,
       delivered_by_user_id, delivered_at, notes, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM package_delivery_events
 WHERE package_id = $1
   AND deleted_at IS NULL
 ORDER BY delivered_at DESC
`

// Lista eventos de entrega de un paquete (por auditoria).
func (q *Queries) ListDeliveryEventsByPackage(ctx context.Context, packageID pgtype.UUID) ([]PackageDeliveryEvent, error) {
	rows, err := q.db.Query(ctx, listDeliveryEventsByPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageDeliveryEvent{}
	for rows.Next() {
		var i PackageDeliveryEvent
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.DeliveredToUserID,
			&i.RecipientNameManual,
			&i.DeliveryMethod,
			&i.SignatureUrl,
			&i.PhotoEvidenceUrl,
			&i.DeliveredByUserID,
			&i.DeliveredAt,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByStatus = `-- name: ListPackagesByStatus :many
SELECT id, unit_id, recipient_name, category_id, received_evidence_url,
       carrier, tracking_number, received_by_user_id, received_at,
       delivered_at, returned_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM packages
 WHERE status = $1
   AND deleted_at IS NULL
 ORDER BY received_at DESC
`

// Lista paquetes con un status dado (camino caliente del dashboard de
// porteria). Orden por received_at desc.
func (q *Queries) ListPackagesByStatus(ctx context.Context, status string) ([]Package, error) {
	rows, err := q.db.Query(ctx, listPackagesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.RecipientName,
			&i.CategoryID,
			&i.ReceivedEvidenceUrl,
			&i.Carrier,
			&i.TrackingNumber,
			&i.ReceivedByUserID,
			&i.ReceivedAt,
			&i.DeliveredAt,
			&i.ReturnedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByUnit = `-- name: ListPackagesByUnit :many
SELECT id, unit_id, recipient_name, category_id, received_evidence_url,
       carrier, tracking_number, received_by_user_id, received_at,
       delivered_at, returned_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM packages
 WHERE unit_id = $1
   AND deleted_at IS NULL
 ORDER BY received_at DESC
`

// Lista paquetes de una unidad, ordenados por fecha de recepcion desc.
func (q *Queries) ListPackagesByUnit(ctx context.Context, unitID pgtype.UUID) ([]Package, error) {
	rows, err := q.db.Query(ctx, listPackagesByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.RecipientName,
			&i.CategoryID,
			&i.ReceivedEvidenceUrl,
			&i.Carrier,
			&i.TrackingNumber,
			&i.ReceivedByUserID,
			&i.ReceivedAt,
			&i.DeliveredAt,
			&i.ReturnedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesPendingReminder = `-- name: ListPackagesPendingReminder :many
SELECT p.id, p.unit_id, p.recipient_name, p.category_id, p.received_evidence_url,
       p.carrier, p.tracking_number, p.received_by_user_id, p.received_at,
       p.delivered_at, p.returned_at, p.status,
       p.created_at, p.updated_at, p.deleted_at,
       p.created_by, p.updated_by, p.deleted_by, p.version
  FROM packages p
 WHERE p.status = 'received'
   AND p.deleted_at IS NULL
   AND p.received_at < now() - INTERVAL '3 days'
   AND NOT EXISTS (
        SELECT 1
          FROM package_outbox_events e
         WHERE e.package_id = p.id
           AND e.event_type = 'package.reminder'
           AND e.created_at > now() - INTERVAL '24 hours'
   )
 ORDER BY p.received_at ASC
`

// Devuelve paquetes en estado 'received' con mas de 3 dias en porteria
// y SIN evento 'package.reminder' encolado en las ultimas 24h. Usado por
// el cron de re-notificacion.
func (q *Queries) ListPackagesPendingReminder(ctx context.Context) ([]Package, error) {
	rows, err := q.db.Query(ctx, listPackagesPendingReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.RecipientName,
			&i.CategoryID,
			&i.ReceivedEvidenceUrl,
			&i.Carrier,
			&i.TrackingNumber,
			&i.ReceivedByUserID,
			&i.ReceivedAt,
			&i.DeliveredAt,
			&i.ReturnedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPendingOutboxEvents = `-- name: LockPendingOutboxEvents :many
SELECT id, package_id, event_type, payload, created_at,
       next_attempt_at, attempts, delivered_at, last_error
  FROM package_outbox_events
 WHERE delivered_at IS NULL
   AND next_attempt_at <= now()
 ORDER BY next_attempt_at ASC
 LIMIT $1
 FOR UPDATE SKIP LOCKED
`

// Bloquea los eventos pendientes (delivered_at IS NULL y next_attempt_at
// llegado) con FOR UPDATE SKIP LOCKED. Pensado para correr DENTRO de una
// transaccion: el worker procesa el lote y commitea al final.
func (q *Queries) LockPendingOutboxEvents(ctx context.Context, limit int32) ([]PackageOutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageOutboxEvent{}
	for rows.Next() {
		var i PackageOutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.NextAttemptAt,
			&i.Attempts,
			&i.DeliveredAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventDelivered = `-- name: MarkOutboxEventDelivered :exec
UPDATE package_outbox_events
   SET delivered_at = now(),
       attempts    = attempts + 1,
       last_error  = NULL
 WHERE id = $1
`

// Marca un evento como entregado (no se vuelve a procesar).
func (q *Queries) MarkOutboxEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventDelivered, id)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE package_outbox_events
   SET attempts        = attempts + 1,
       last_error      = $1,
       next_attempt_at = $2
 WHERE id = $3
`

type MarkOutboxEventFailedParams struct {
	LastError     *string
	NextAttemptAt pgtype.Timestamptz
	ID            pgtype.UUID
}

// Marca un fallo: incrementa attempts, fija last_error y reagenda
// next_attempt_at con backoff calculado por el worker (lo recibe como
// argumento).
func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.LastError, arg.NextAttemptAt, arg.ID)
	return err
}

const recordDeliveryEvent = `-- name: RecordDeliveryEvent :one

INSERT INTO package_delivery_events (
    package_id, delivered_to_user_id, recipient_name_manual,
    delivery_method, signature_url, photo_evidence_url,
    delivered_by_user_id, notes, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'completed', $7, $7
)
RETURNING id, package_id, delivered_to_user_id, recipient_name_manual,
          delivery_method, signature_url, photo_evidence_url,
          delivered_by_user_id, delivered_at, notes, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type RecordDeliveryEventParams struct {
	PackageID           pgtype.UUID
	DeliveredToUserID   pgtype.UUID
	RecipientNameManual *string
	DeliveryMethod      string
	SignatureUrl        *string
	PhotoEvidenceUrl    *string
	DeliveredByUserID   pgtype.UUID
	Notes               *string
}

// ----------------------------------------------------------------------------
// package_delivery_events
// ----------------------------------------------------------------------------
// Inserta el registro de la entrega del paquete (qr o manual).
func (q *Queries) RecordDeliveryEvent(ctx context.Context, arg RecordDeliveryEventParams) (PackageDeliveryEvent, error) {
	row := q.db.QueryRow(ctx, recordDeliveryEvent,
		arg.PackageID,
		arg.DeliveredToUserID,
		arg.RecipientNameManual,
		arg.DeliveryMethod,
		arg.SignatureUrl,
		arg.PhotoEvidenceUrl,
		arg.DeliveredByUserID,
		arg.Notes,
	)
	var i PackageDeliveryEvent
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.DeliveredToUserID,
		&i.RecipientNameManual,
		&i.DeliveryMethod,
		&i.SignatureUrl,
		&i.PhotoEvidenceUrl,
		&i.DeliveredByUserID,
		&i.DeliveredAt,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const returnPackage = `-- name: ReturnPackage :one
UPDATE packages
   SET status      = 'returned',
       returned_at = now(),
       updated_at  = now(),
       updated_by  = $1,
       version     = version + 1
 WHERE id = $2
   AND version = $3
   AND deleted_at IS NULL
   AND status = 'received'
RETURNING id, unit_id, recipient_name, category_id, received_evidence_url,
          carrier, tracking_number, received_by_user_id, received_at,
          delivered_at, returned_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type ReturnPackageParams struct {
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

// Marca el paquete como devuelto al transportador (atajo conveniente).
// Tambien usa version optimista.
func (q *Queries) ReturnPackage(ctx context.Context, arg ReturnPackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, returnPackage, arg.UpdatedBy, arg.ID, arg.ExpectedVersion)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.RecipientName,
		&i.CategoryID,
		&i.ReceivedEvidenceUrl,
		&i.Carrier,
		&i.TrackingNumber,
		&i.ReceivedByUserID,
		&i.ReceivedAt,
		&i.DeliveredAt,
		&i.ReturnedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const updatePackageStatus = `-- name: UpdatePackageStatus :one
UPDATE packages
   SET status       = $1::TEXT,
       delivered_at = CASE
                        WHEN $1::TEXT = 'delivered' THEN now()
                        ELSE delivered_at
                      END,
       returned_at  = CASE
                        WHEN $1::TEXT = 'returned' THEN now()
                        ELSE returned_at
                      END,
       updated_at   = now(),
       updated_by   = $2,
       version      = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, unit_id, recipient_name, category_id, received_evidence_url,
          carrier, tracking_number, received_by_user_id, received_at,
          delivered_at, returned_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdatePackageStatusParams struct {
	NewStatus       string
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

// Bloqueo optimista: actualiza el status si la version coincide. Si la
// version no coincide, no afecta filas y el caller mapea a 409.
func (q *Queries) UpdatePackageStatus(ctx context.Context, arg UpdatePackageStatusParams) (Package, error) {
	row := q.db.QueryRow(ctx, updatePackageStatus,
		arg.NewStatus,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.RecipientName,
		&i.CategoryID,
		&i.ReceivedEvidenceUrl,
		&i.Carrier,
		&i.TrackingNumber,
		&i.ReceivedByUserID,
		&i.ReceivedAt,
		&i.DeliveredAt,
		&i.ReturnedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}
