// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package packagesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ----------------------------------------------------------------------------
	// packages
	// ----------------------------------------------------------------------------
	// Crea un paquete nuevo en estado 'received'.
	CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error)
	// ----------------------------------------------------------------------------
	// package_outbox_events
	// ----------------------------------------------------------------------------
	// Inserta un evento en el outbox modulo-local.
	EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) (PackageOutboxEvent, error)
	// Devuelve una categoria por id (cualquier estado).
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (PackageCategory, error)
	// Devuelve una categoria activa por nombre exacto.
	GetCategoryByName(ctx context.Context, name string) (PackageCategory, error)
	// Devuelve un paquete por id (no soft-deleted).
	GetPackageByID(ctx context.Context, id pgtype.UUID) (Package, error)
	// Queries del modulo packages (sqlc).
	//
	// Convenciones:
	//   * Listados excluyen filas con deleted_at IS NOT NULL.
	//   * Concurrencia optimista: UpdatePackageStatus usa WHERE id=$1 AND
	//     version=$2; cualquier UPDATE incrementa version.
	//   * Outbox modulo-local: el worker bloquea con FOR UPDATE SKIP LOCKED
	//     para procesar en paralelo sin doble consumo.
	// ----------------------------------------------------------------------------
	// package_categories
	// ----------------------------------------------------------------------------
	// Devuelve las categorias activas, orden alfabetico.
	ListCategories(ctx context.Context) ([]PackageCategory, error)
	// Lista eventos de entrega de un paquete (por auditoria).
	ListDeliveryEventsByPackage(ctx context.Context, packageID pgtype.UUID) ([]PackageDeliveryEvent, error)
	// Lista paquetes con un status dado (camino caliente del dashboard de
	// porteria). Orden por received_at desc.
	ListPackagesByStatus(ctx context.Context, status string) ([]Package, error)
	// Lista paquetes de una unidad, ordenados por fecha de recepcion desc.
	ListPackagesByUnit(ctx context.Context, unitID pgtype.UUID) ([]Package, error)
	// Devuelve paquetes en estado 'received' con mas de 3 dias en porteria
	// y SIN evento 'package.reminder' encolado en las ultimas 24h. Usado por
	// el cron de re-notificacion.
	ListPackagesPendingReminder(ctx context.Context) ([]Package, error)
	// Bloquea los eventos pendientes (delivered_at IS NULL y next_attempt_at
	// llegado) con FOR UPDATE SKIP LOCKED. Pensado para correr DENTRO de una
	// transaccion: el worker procesa el lote y commitea al final.
	LockPendingOutboxEvents(ctx context.Context, limit int32) ([]PackageOutboxEvent, error)
	// Marca un evento como entregado (no se vuelve a procesar).
	MarkOutboxEventDelivered(ctx context.Context, id pgtype.UUID) error
	// Marca un fallo: incrementa attempts, fija last_error y reagenda
	// next_attempt_at con backoff calculado por el worker (lo recibe como
	// argumento).
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error
	// ----------------------------------------------------------------------------
	// package_delivery_events
	// ----------------------------------------------------------------------------
	// Inserta el registro de la entrega del paquete (qr o manual).
	RecordDeliveryEvent(ctx context.Context, arg RecordDeliveryEventParams) (PackageDeliveryEvent, error)
	// Marca el paquete como devuelto al transportador (atajo conveniente).
	// Tambien usa version optimista.
	ReturnPackage(ctx context.Context, arg ReturnPackageParams) (Package, error)
	// Bloqueo optimista: actualiza el status si la version coincide. Si la
	// version no coincide, no afecta filas y el caller mapea a 409.
	UpdatePackageStatus(ctx context.Context, arg UpdatePackageStatusParams) (Package, error)
}

var _ Querier = (*Queries)(nil)
