// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package incidentsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ----------------------------------------------------------------------------
// incidents
// ----------------------------------------------------------------------------

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    incident_type, severity, title, description,
    reported_by_user_id, reported_at,
    structure_id, location_detail,
    sla_assign_due_at, sla_resolve_due_at,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    'reported', $5, $5
)
RETURNING id, incident_type, severity, title, description,
          reported_by_user_id, reported_at,
          structure_id, location_detail,
          assigned_to_user_id, assigned_at,
          started_at, resolved_at, closed_at, cancelled_at,
          resolution_notes, escalated,
          sla_assign_due_at, sla_resolve_due_at,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type CreateIncidentParams struct {
	IncidentType     string
	Severity         string
	Title            string
	Description      string
	ReportedByUserID pgtype.UUID
	ReportedAt       pgtype.Timestamptz
	StructureID      pgtype.UUID
	LocationDetail   *string
	SlaAssignDueAt   pgtype.Timestamptz
	SlaResolveDueAt  pgtype.Timestamptz
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.IncidentType,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.ReportedByUserID,
		arg.ReportedAt,
		arg.StructureID,
		arg.LocationDetail,
		arg.SlaAssignDueAt,
		arg.SlaResolveDueAt,
	)
	var i Incident
	err := row.Scan(
		&i.ID, &i.IncidentType, &i.Severity, &i.Title, &i.Description,
		&i.ReportedByUserID, &i.ReportedAt,
		&i.StructureID, &i.LocationDetail,
		&i.AssignedToUserID, &i.AssignedAt,
		&i.StartedAt, &i.ResolvedAt, &i.ClosedAt, &i.CancelledAt,
		&i.ResolutionNotes, &i.Escalated,
		&i.SlaAssignDueAt, &i.SlaResolveDueAt,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT id, incident_type, severity, title, description,
       reported_by_user_id, reported_at,
       structure_id, location_detail,
       assigned_to_user_id, assigned_at,
       started_at, resolved_at, closed_at, cancelled_at,
       resolution_notes, escalated,
       sla_assign_due_at, sla_resolve_due_at,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM incidents
 WHERE id = $1
   AND deleted_at IS NULL`

func (q *Queries) GetIncidentByID(ctx context.Context, id pgtype.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentByID, id)
	var i Incident
	err := row.Scan(
		&i.ID, &i.IncidentType, &i.Severity, &i.Title, &i.Description,
		&i.ReportedByUserID, &i.ReportedAt,
		&i.StructureID, &i.LocationDetail,
		&i.AssignedToUserID, &i.AssignedAt,
		&i.StartedAt, &i.ResolvedAt, &i.ClosedAt, &i.CancelledAt,
		&i.ResolutionNotes, &i.Escalated,
		&i.SlaAssignDueAt, &i.SlaResolveDueAt,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, incident_type, severity, title, description,
       reported_by_user_id, reported_at,
       structure_id, location_detail,
       assigned_to_user_id, assigned_at,
       started_at, resolved_at, closed_at, cancelled_at,
       resolution_notes, escalated,
       sla_assign_due_at, sla_resolve_due_at,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM incidents
 WHERE deleted_at IS NULL
 ORDER BY reported_at DESC`

func (q *Queries) ListIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID, &i.IncidentType, &i.Severity, &i.Title, &i.Description,
			&i.ReportedByUserID, &i.ReportedAt,
			&i.StructureID, &i.LocationDetail,
			&i.AssignedToUserID, &i.AssignedAt,
			&i.StartedAt, &i.ResolvedAt, &i.ClosedAt, &i.CancelledAt,
			&i.ResolutionNotes, &i.Escalated,
			&i.SlaAssignDueAt, &i.SlaResolveDueAt,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listIncidentsByStatus = `-- name: ListIncidentsByStatus :many
SELECT id, incident_type, severity, title, description,
       reported_by_user_id, reported_at,
       structure_id, location_detail,
       assigned_to_user_id, assigned_at,
       started_at, resolved_at, closed_at, cancelled_at,
       resolution_notes, escalated,
       sla_assign_due_at, sla_resolve_due_at,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM incidents
 WHERE deleted_at IS NULL
   AND status = $1
 ORDER BY reported_at DESC`

func (q *Queries) ListIncidentsByStatus(ctx context.Context, status string) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID, &i.IncidentType, &i.Severity, &i.Title, &i.Description,
			&i.ReportedByUserID, &i.ReportedAt,
			&i.StructureID, &i.LocationDetail,
			&i.AssignedToUserID, &i.AssignedAt,
			&i.StartedAt, &i.ResolvedAt, &i.ClosedAt, &i.CancelledAt,
			&i.ResolutionNotes, &i.Escalated,
			&i.SlaAssignDueAt, &i.SlaResolveDueAt,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listIncidentsBySeverity = `-- name: ListIncidentsBySeverity :many
SELECT id, incident_type, severity, title, description,
       reported_by_user_id, reported_at,
       structure_id, location_detail,
       assigned_to_user_id, assigned_at,
       started_at, resolved_at, closed_at, cancelled_at,
       resolution_notes, escalated,
       sla_assign_due_at, sla_resolve_due_at,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM incidents
 WHERE deleted_at IS NULL
   AND severity = $1
 ORDER BY reported_at DESC`

func (q *Queries) ListIncidentsBySeverity(ctx context.Context, severity string) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsBySeverity, severity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID, &i.IncidentType, &i.Severity, &i.Title, &i.Description,
			&i.ReportedByUserID, &i.ReportedAt,
			&i.StructureID, &i.LocationDetail,
			&i.AssignedToUserID, &i.AssignedAt,
			&i.StartedAt, &i.ResolvedAt, &i.ClosedAt, &i.CancelledAt,
			&i.ResolutionNotes, &i.Escalated,
			&i.SlaAssignDueAt, &i.SlaResolveDueAt,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listIncidentsByReporter = `-- name: ListIncidentsByReporter :many
SELECT id, incident_type, severity, title, description,
       reported_by_user_id, reported_at,
       structure_id, location_detail,
       assigned_to_user_id, assigned_at,
       started_at, resolved_at, closed_at, cancelled_at,
       resolution_notes, escalated,
       sla_assign_due_at, sla_resolve_due_at,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM incidents
 WHERE deleted_at IS NULL
   AND reported_by_user_id = $1
 ORDER BY reported_at DESC`

func (q *Queries) ListIncidentsByReporter(ctx context.Context, reportedByUserID pgtype.UUID) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByReporter, reportedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID, &i.IncidentType, &i.Severity, &i.Title, &i.Description,
			&i.ReportedByUserID, &i.ReportedAt,
			&i.StructureID, &i.LocationDetail,
			&i.AssignedToUserID, &i.AssignedAt,
			&i.StartedAt, &i.ResolvedAt, &i.ClosedAt, &i.CancelledAt,
			&i.ResolutionNotes, &i.Escalated,
			&i.SlaAssignDueAt, &i.SlaResolveDueAt,
			&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :one
UPDATE incidents
   SET status              = $1,
       assigned_to_user_id = COALESCE($2, assigned_to_user_id),
       assigned_at         = COALESCE($3, assigned_at),
       started_at          = COALESCE($4, started_at),
       resolved_at         = COALESCE($5, resolved_at),
       closed_at           = COALESCE($6, closed_at),
       cancelled_at        = COALESCE($7, cancelled_at),
       resolution_notes    = COALESCE($8, resolution_notes),
       escalated           = COALESCE($9, escalated),
       updated_at          = now(),
       updated_by          = $10,
       version             = version + 1
 WHERE id = $11
   AND version = $12
   AND deleted_at IS NULL
RETURNING id, incident_type, severity, title, description,
          reported_by_user_id, reported_at,
          structure_id, location_detail,
          assigned_to_user_id, assigned_at,
          started_at, resolved_at, closed_at, cancelled_at,
          resolution_notes, escalated,
          sla_assign_due_at, sla_resolve_due_at,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version`

type UpdateIncidentStatusParams struct {
	NewStatus           string
	NewAssignedToUserID pgtype.UUID
	NewAssignedAt       pgtype.Timestamptz
	NewStartedAt        pgtype.Timestamptz
	NewResolvedAt       pgtype.Timestamptz
	NewClosedAt         pgtype.Timestamptz
	NewCancelledAt      pgtype.Timestamptz
	NewResolutionNotes  *string
	NewEscalated        *bool
	UpdatedBy           pgtype.UUID
	ID                  pgtype.UUID
	ExpectedVersion     int32
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentStatus,
		arg.NewStatus,
		arg.NewAssignedToUserID,
		arg.NewAssignedAt,
		arg.NewStartedAt,
		arg.NewResolvedAt,
		arg.NewClosedAt,
		arg.NewCancelledAt,
		arg.NewResolutionNotes,
		arg.NewEscalated,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Incident
	err := row.Scan(
		&i.ID, &i.IncidentType, &i.Severity, &i.Title, &i.Description,
		&i.ReportedByUserID, &i.ReportedAt,
		&i.StructureID, &i.LocationDetail,
		&i.AssignedToUserID, &i.AssignedAt,
		&i.StartedAt, &i.ResolvedAt, &i.ClosedAt, &i.CancelledAt,
		&i.ResolutionNotes, &i.Escalated,
		&i.SlaAssignDueAt, &i.SlaResolveDueAt,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// ----------------------------------------------------------------------------
// incident_attachments
// ----------------------------------------------------------------------------

const createIncidentAttachment = `-- name: CreateIncidentAttachment :one
INSERT INTO incident_attachments (
    incident_id, url, mime_type, size_bytes,
    uploaded_by, status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, 'active', $5, $5
)
RETURNING id, incident_id, url, mime_type, size_bytes,
          uploaded_by, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by`

type CreateIncidentAttachmentParams struct {
	IncidentID pgtype.UUID
	Url        string
	MimeType   string
	SizeBytes  int64
	UploadedBy pgtype.UUID
}

func (q *Queries) CreateIncidentAttachment(ctx context.Context, arg CreateIncidentAttachmentParams) (IncidentAttachment, error) {
	row := q.db.QueryRow(ctx, createIncidentAttachment,
		arg.IncidentID,
		arg.Url,
		arg.MimeType,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i IncidentAttachment
	err := row.Scan(
		&i.ID, &i.IncidentID, &i.Url, &i.MimeType, &i.SizeBytes,
		&i.UploadedBy, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy,
	)
	return i, err
}

const listAttachmentsByIncidentID = `-- name: ListAttachmentsByIncidentID :many
SELECT id, incident_id, url, mime_type, size_bytes,
       uploaded_by, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
  FROM incident_attachments
 WHERE incident_id = $1
   AND deleted_at IS NULL
 ORDER BY created_at ASC`

func (q *Queries) ListAttachmentsByIncidentID(ctx context.Context, incidentID pgtype.UUID) ([]IncidentAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByIncidentID, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentAttachment
	for rows.Next() {
		var i IncidentAttachment
		if err := rows.Scan(
			&i.ID, &i.IncidentID, &i.Url, &i.MimeType, &i.SizeBytes,
			&i.UploadedBy, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countAttachmentsByIncidentID = `-- name: CountAttachmentsByIncidentID :one
SELECT count(*)::int AS count
  FROM incident_attachments
 WHERE incident_id = $1
   AND deleted_at IS NULL`

func (q *Queries) CountAttachmentsByIncidentID(ctx context.Context, incidentID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countAttachmentsByIncidentID, incidentID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

// ----------------------------------------------------------------------------
// incident_status_history
// ----------------------------------------------------------------------------

const recordIncidentStatusHistory = `-- name: RecordIncidentStatusHistory :one
INSERT INTO incident_status_history (
    incident_id, from_status, to_status,
    transitioned_by_user_id, notes,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5,
    'recorded', $4, $4
)
RETURNING id, incident_id, from_status, to_status,
          transitioned_by_user_id, transitioned_at,
          notes, status,
          created_at, updated_at,
          created_by, updated_by`

type RecordIncidentStatusHistoryParams struct {
	IncidentID           pgtype.UUID
	FromStatus           *string
	ToStatus             string
	TransitionedByUserID pgtype.UUID
	Notes                *string
}

func (q *Queries) RecordIncidentStatusHistory(ctx context.Context, arg RecordIncidentStatusHistoryParams) (IncidentStatusHistory, error) {
	row := q.db.QueryRow(ctx, recordIncidentStatusHistory,
		arg.IncidentID,
		arg.FromStatus,
		arg.ToStatus,
		arg.TransitionedByUserID,
		arg.Notes,
	)
	var i IncidentStatusHistory
	err := row.Scan(
		&i.ID, &i.IncidentID, &i.FromStatus, &i.ToStatus,
		&i.TransitionedByUserID, &i.TransitionedAt,
		&i.Notes, &i.Status,
		&i.CreatedAt, &i.UpdatedAt,
		&i.CreatedBy, &i.UpdatedBy,
	)
	return i, err
}

const listStatusHistoryByIncidentID = `-- name: ListStatusHistoryByIncidentID :many
SELECT id, incident_id, from_status, to_status,
       transitioned_by_user_id, transitioned_at,
       notes, status,
       created_at, updated_at,
       created_by, updated_by
  FROM incident_status_history
 WHERE incident_id = $1
 ORDER BY transitioned_at DESC`

func (q *Queries) ListStatusHistoryByIncidentID(ctx context.Context, incidentID pgtype.UUID) ([]IncidentStatusHistory, error) {
	rows, err := q.db.Query(ctx, listStatusHistoryByIncidentID, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentStatusHistory
	for rows.Next() {
		var i IncidentStatusHistory
		if err := rows.Scan(
			&i.ID, &i.IncidentID, &i.FromStatus, &i.ToStatus,
			&i.TransitionedByUserID, &i.TransitionedAt,
			&i.Notes, &i.Status,
			&i.CreatedAt, &i.UpdatedAt,
			&i.CreatedBy, &i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// ----------------------------------------------------------------------------
// incident_assignments
// ----------------------------------------------------------------------------

const createIncidentAssignment = `-- name: CreateIncidentAssignment :one
INSERT INTO incident_assignments (
    incident_id, assigned_to_user_id, assigned_by_user_id,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, 'active', $3, $3
)
RETURNING id, incident_id, assigned_to_user_id, assigned_by_user_id,
          assigned_at, unassigned_at, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by`

type CreateIncidentAssignmentParams struct {
	IncidentID       pgtype.UUID
	AssignedToUserID pgtype.UUID
	AssignedByUserID pgtype.UUID
}

func (q *Queries) CreateIncidentAssignment(ctx context.Context, arg CreateIncidentAssignmentParams) (IncidentAssignment, error) {
	row := q.db.QueryRow(ctx, createIncidentAssignment,
		arg.IncidentID,
		arg.AssignedToUserID,
		arg.AssignedByUserID,
	)
	var i IncidentAssignment
	err := row.Scan(
		&i.ID, &i.IncidentID, &i.AssignedToUserID, &i.AssignedByUserID,
		&i.AssignedAt, &i.UnassignedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy,
	)
	return i, err
}

const unassignActiveByIncidentID = `-- name: UnassignActiveByIncidentID :exec
UPDATE incident_assignments
   SET status        = 'unassigned',
       unassigned_at = now(),
       updated_at    = now(),
       updated_by    = $1
 WHERE incident_id = $2
   AND status = 'active'
   AND deleted_at IS NULL`

type UnassignActiveByIncidentIDParams struct {
	UpdatedBy  pgtype.UUID
	IncidentID pgtype.UUID
}

func (q *Queries) UnassignActiveByIncidentID(ctx context.Context, arg UnassignActiveByIncidentIDParams) error {
	_, err := q.db.Exec(ctx, unassignActiveByIncidentID, arg.UpdatedBy, arg.IncidentID)
	return err
}

const getActiveAssignmentByIncidentID = `-- name: GetActiveAssignmentByIncidentID :one
SELECT id, incident_id, assigned_to_user_id, assigned_by_user_id,
       assigned_at, unassigned_at, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by
  FROM incident_assignments
 WHERE incident_id = $1
   AND status = 'active'
   AND deleted_at IS NULL
 LIMIT 1`

func (q *Queries) GetActiveAssignmentByIncidentID(ctx context.Context, incidentID pgtype.UUID) (IncidentAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveAssignmentByIncidentID, incidentID)
	var i IncidentAssignment
	err := row.Scan(
		&i.ID, &i.IncidentID, &i.AssignedToUserID, &i.AssignedByUserID,
		&i.AssignedAt, &i.UnassignedAt, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy,
	)
	return i, err
}

// ----------------------------------------------------------------------------
// incident_outbox_events
// ----------------------------------------------------------------------------

const enqueueIncidentOutboxEvent = `-- name: EnqueueIncidentOutboxEvent :one
INSERT INTO incident_outbox_events (
    incident_id, event_type, payload, next_attempt_at, attempts
) VALUES (
    $1, $2, $3, now(), 0
)
RETURNING id, incident_id, event_type, payload, created_at,
          next_attempt_at, attempts, delivered_at, last_error`

type EnqueueIncidentOutboxEventParams struct {
	IncidentID pgtype.UUID
	EventType  string
	Payload    []byte
}

func (q *Queries) EnqueueIncidentOutboxEvent(ctx context.Context, arg EnqueueIncidentOutboxEventParams) (IncidentOutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueueIncidentOutboxEvent,
		arg.IncidentID,
		arg.EventType,
		arg.Payload,
	)
	var i IncidentOutboxEvent
	err := row.Scan(
		&i.ID, &i.IncidentID, &i.EventType, &i.Payload, &i.CreatedAt,
		&i.NextAttemptAt, &i.Attempts, &i.DeliveredAt, &i.LastError,
	)
	return i, err
}

const lockPendingIncidentOutboxEvents = `-- name: LockPendingIncidentOutboxEvents :many
SELECT id, incident_id, event_type, payload, created_at,
       next_attempt_at, attempts, delivered_at, last_error
  FROM incident_outbox_events
 WHERE delivered_at IS NULL
   AND next_attempt_at <= now()
 ORDER BY next_attempt_at ASC
 LIMIT $1
 FOR UPDATE SKIP LOCKED`

func (q *Queries) LockPendingIncidentOutboxEvents(ctx context.Context, limit int32) ([]IncidentOutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockPendingIncidentOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentOutboxEvent
	for rows.Next() {
		var i IncidentOutboxEvent
		if err := rows.Scan(
			&i.ID, &i.IncidentID, &i.EventType, &i.Payload, &i.CreatedAt,
			&i.NextAttemptAt, &i.Attempts, &i.DeliveredAt, &i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const markIncidentOutboxEventDelivered = `-- name: MarkIncidentOutboxEventDelivered :exec
UPDATE incident_outbox_events
   SET delivered_at = now(),
       attempts     = attempts + 1,
       last_error   = NULL
 WHERE id = $1`

func (q *Queries) MarkIncidentOutboxEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markIncidentOutboxEventDelivered, id)
	return err
}

const markIncidentOutboxEventFailed = `-- name: MarkIncidentOutboxEventFailed :exec
UPDATE incident_outbox_events
   SET attempts        = attempts + 1,
       last_error      = $1,
       next_attempt_at = $2
 WHERE id = $3`

type MarkIncidentOutboxEventFailedParams struct {
	LastError     *string
	NextAttemptAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) MarkIncidentOutboxEventFailed(ctx context.Context, arg MarkIncidentOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markIncidentOutboxEventFailed, arg.LastError, arg.NextAttemptAt, arg.ID)
	return err
}
