// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package incidentsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Incident struct {
	ID               pgtype.UUID
	IncidentType     string
	Severity         string
	Title            string
	Description      string
	ReportedByUserID pgtype.UUID
	ReportedAt       pgtype.Timestamptz
	StructureID      pgtype.UUID
	LocationDetail   *string
	AssignedToUserID pgtype.UUID
	AssignedAt       pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	ResolvedAt       pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	CancelledAt      pgtype.Timestamptz
	ResolutionNotes  *string
	Escalated        bool
	SlaAssignDueAt   pgtype.Timestamptz
	SlaResolveDueAt  pgtype.Timestamptz
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
	DeletedBy        pgtype.UUID
	Version          int32
}

type IncidentAttachment struct {
	ID         pgtype.UUID
	IncidentID pgtype.UUID
	Url        string
	MimeType   string
	SizeBytes  int64
	UploadedBy pgtype.UUID
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedBy  pgtype.UUID
	DeletedBy  pgtype.UUID
}

type IncidentStatusHistory struct {
	ID                   pgtype.UUID
	IncidentID           pgtype.UUID
	FromStatus           *string
	ToStatus             string
	TransitionedByUserID pgtype.UUID
	TransitionedAt       pgtype.Timestamptz
	Notes                *string
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedBy            pgtype.UUID
	UpdatedBy            pgtype.UUID
}

type IncidentAssignment struct {
	ID               pgtype.UUID
	IncidentID       pgtype.UUID
	AssignedToUserID pgtype.UUID
	AssignedByUserID pgtype.UUID
	AssignedAt       pgtype.Timestamptz
	UnassignedAt     pgtype.Timestamptz
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
	DeletedBy        pgtype.UUID
}

type IncidentOutboxEvent struct {
	ID            pgtype.UUID
	IncidentID    pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
	Attempts      int32
	DeliveredAt   pgtype.Timestamptz
	LastError     *string
}
