// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package unitsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOccupant(ctx context.Context, arg AddOccupantParams) (UnitOccupancy, error)
	AddOwner(ctx context.Context, arg AddOwnerParams) (UnitOwner, error)
	// Queries del modulo units.
	//
	// Convenciones:
	//   * Nombres en CamelCase con anotaciones :one|:many|:exec.
	//   * SELECTs operativos siempre filtran deleted_at IS NULL.
	//   * No hay columna tenant_id (la base entera es del tenant — CLAUDE.md).
	//   * "Activo" para owners es until_date IS NULL; para occupants es
	//     move_out_date IS NULL. Las terminaciones NO son soft-delete: se
	//     setea la columna correspondiente para preservar historico.
	CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error)
	// Devuelve owners activos + occupants activos en una sola query.
	// "Owners activos" = unit_owners sin until_date y no soft-deleted.
	// "Occupants activos" = unit_occupancies sin move_out_date y no soft-deleted.
	// El JOIN con users obtiene el nombre completo y el documento.
	// El campo role_in_unit unifica owners (etiqueta 'owner') y occupants
	// (su rol nativo). is_primary solo aplica a occupants; en owners viene
	// siempre false. since_date corresponde a owner.since_date u
	// occupant.move_in_date segun la fuente.
	GetActivePeopleForUnit(ctx context.Context, unitID pgtype.UUID) ([]GetActivePeopleForUnitRow, error)
	GetUnitByID(ctx context.Context, id pgtype.UUID) (Unit, error)
	ListActiveOccupantsByUnit(ctx context.Context, unitID pgtype.UUID) ([]UnitOccupancy, error)
	ListAllActiveUnits(ctx context.Context) ([]Unit, error)
	ListOwnersByUnit(ctx context.Context, unitID pgtype.UUID) ([]UnitOwner, error)
	ListUnitsByStructure(ctx context.Context, structureID pgtype.UUID) ([]Unit, error)
	MoveOutOccupant(ctx context.Context, arg MoveOutOccupantParams) error
	TerminateOwnership(ctx context.Context, arg TerminateOwnershipParams) error
}

var _ Querier = (*Queries)(nil)
