// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package unitsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOccupant = `-- name: AddOccupant :one
INSERT INTO unit_occupancies (
    unit_id, user_id, role_in_unit, is_primary, move_in_date,
    status, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    'active', $6
)
RETURNING id, unit_id, user_id, role_in_unit, is_primary,
    move_in_date, move_out_date,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
`

type AddOccupantParams struct {
	UnitID     pgtype.UUID
	UserID     pgtype.UUID
	RoleInUnit string
	IsPrimary  bool
	MoveInDate pgtype.Date
	CreatedBy  pgtype.UUID
}

func (q *Queries) AddOccupant(ctx context.Context, arg AddOccupantParams) (UnitOccupancy, error) {
	row := q.db.QueryRow(ctx, addOccupant,
		arg.UnitID,
		arg.UserID,
		arg.RoleInUnit,
		arg.IsPrimary,
		arg.MoveInDate,
		arg.CreatedBy,
	)
	var i UnitOccupancy
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.UserID,
		&i.RoleInUnit,
		&i.IsPrimary,
		&i.MoveInDate,
		&i.MoveOutDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const addOwner = `-- name: AddOwner :one
INSERT INTO unit_owners (
    unit_id, user_id, percentage, since_date, status, created_by
) VALUES (
    $1, $2, $3, $4, 'active', $5
)
RETURNING id, unit_id, user_id, percentage, since_date, until_date,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
`

type AddOwnerParams struct {
	UnitID     pgtype.UUID
	UserID     pgtype.UUID
	Percentage pgtype.Numeric
	SinceDate  pgtype.Date
	CreatedBy  pgtype.UUID
}

func (q *Queries) AddOwner(ctx context.Context, arg AddOwnerParams) (UnitOwner, error) {
	row := q.db.QueryRow(ctx, addOwner,
		arg.UnitID,
		arg.UserID,
		arg.Percentage,
		arg.SinceDate,
		arg.CreatedBy,
	)
	var i UnitOwner
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.UserID,
		&i.Percentage,
		&i.SinceDate,
		&i.UntilDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one

INSERT INTO units (
    structure_id, code, type, area_m2, bedrooms, coefficient,
    status, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    'active',
    $7
)
RETURNING id, structure_id, code, type, area_m2, bedrooms, coefficient,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
`

type CreateUnitParams struct {
	StructureID pgtype.UUID
	Code        string
	Type        string
	AreaM2      pgtype.Numeric
	Bedrooms    *int32
	Coefficient pgtype.Numeric
	CreatedBy   pgtype.UUID
}

// Queries del modulo units.
//
// Convenciones:
//   - Nombres en CamelCase con anotaciones :one|:many|:exec.
//   - SELECTs operativos siempre filtran deleted_at IS NULL.
//   - No hay columna tenant_id (la base entera es del tenant — CLAUDE.md).
//   - "Activo" para owners es until_date IS NULL; para occupants es
//     move_out_date IS NULL. Las terminaciones NO son soft-delete: se
//     setea la columna correspondiente para preservar historico.
func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.StructureID,
		arg.Code,
		arg.Type,
		arg.AreaM2,
		arg.Bedrooms,
		arg.Coefficient,
		arg.CreatedBy,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.StructureID,
		&i.Code,
		&i.Type,
		&i.AreaM2,
		&i.Bedrooms,
		&i.Coefficient,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getActivePeopleForUnit = `-- name: GetActivePeopleForUnit :many
SELECT
    u.id AS user_id,
    (u.names || ' ' || u.last_names) AS full_name,
    (u.document_type || ':' || u.document_number) AS document,
    'owner'::text AS role_in_unit,
    false::boolean AS is_primary,
    o.since_date::date AS since_date
FROM unit_owners o
JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE o.unit_id = $1
  AND o.deleted_at IS NULL
  AND o.until_date IS NULL
UNION ALL
SELECT
    u.id AS user_id,
    (u.names || ' ' || u.last_names) AS full_name,
    (u.document_type || ':' || u.document_number) AS document,
    oc.role_in_unit::text AS role_in_unit,
    oc.is_primary AS is_primary,
    oc.move_in_date::date AS since_date
FROM unit_occupancies oc
JOIN users u ON u.id = oc.user_id AND u.deleted_at IS NULL
WHERE oc.unit_id = $1
  AND oc.deleted_at IS NULL
  AND oc.move_out_date IS NULL
ORDER BY since_date ASC
`

type GetActivePeopleForUnitRow struct {
	UserID     pgtype.UUID
	FullName   interface{}
	Document   interface{}
	RoleInUnit string
	IsPrimary  bool
	SinceDate  pgtype.Date
}

// Devuelve owners activos + occupants activos en una sola query.
// "Owners activos" = unit_owners sin until_date y no soft-deleted.
// "Occupants activos" = unit_occupancies sin move_out_date y no soft-deleted.
// El JOIN con users obtiene el nombre completo y el documento.
// El campo role_in_unit unifica owners (etiqueta 'owner') y occupants
// (su rol nativo). is_primary solo aplica a occupants; en owners viene
// siempre false. since_date corresponde a owner.since_date u
// occupant.move_in_date segun la fuente.
func (q *Queries) GetActivePeopleForUnit(ctx context.Context, unitID pgtype.UUID) ([]GetActivePeopleForUnitRow, error) {
	rows, err := q.db.Query(ctx, getActivePeopleForUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActivePeopleForUnitRow{}
	for rows.Next() {
		var i GetActivePeopleForUnitRow
		if err := rows.Scan(
			&i.UserID,
			&i.FullName,
			&i.Document,
			&i.RoleInUnit,
			&i.IsPrimary,
			&i.SinceDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT id, structure_id, code, type, area_m2, bedrooms, coefficient,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
FROM units
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUnitByID(ctx context.Context, id pgtype.UUID) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.StructureID,
		&i.Code,
		&i.Type,
		&i.AreaM2,
		&i.Bedrooms,
		&i.Coefficient,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const listActiveOccupantsByUnit = `-- name: ListActiveOccupantsByUnit :many
SELECT id, unit_id, user_id, role_in_unit, is_primary,
    move_in_date, move_out_date,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
FROM unit_occupancies
WHERE unit_id = $1
  AND deleted_at IS NULL
  AND move_out_date IS NULL
ORDER BY move_in_date ASC
`

func (q *Queries) ListActiveOccupantsByUnit(ctx context.Context, unitID pgtype.UUID) ([]UnitOccupancy, error) {
	rows, err := q.db.Query(ctx, listActiveOccupantsByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnitOccupancy{}
	for rows.Next() {
		var i UnitOccupancy
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.UserID,
			&i.RoleInUnit,
			&i.IsPrimary,
			&i.MoveInDate,
			&i.MoveOutDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveUnits = `-- name: ListAllActiveUnits :many
SELECT id, structure_id, code, type, area_m2, bedrooms, coefficient,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
FROM units
WHERE deleted_at IS NULL
ORDER BY code ASC
`

func (q *Queries) ListAllActiveUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listAllActiveUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.StructureID,
			&i.Code,
			&i.Type,
			&i.AreaM2,
			&i.Bedrooms,
			&i.Coefficient,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnersByUnit = `-- name: ListOwnersByUnit :many
SELECT id, unit_id, user_id, percentage, since_date, until_date,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
FROM unit_owners
WHERE unit_id = $1
  AND deleted_at IS NULL
  AND until_date IS NULL
ORDER BY since_date ASC
`

func (q *Queries) ListOwnersByUnit(ctx context.Context, unitID pgtype.UUID) ([]UnitOwner, error) {
	rows, err := q.db.Query(ctx, listOwnersByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnitOwner{}
	for rows.Next() {
		var i UnitOwner
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.UserID,
			&i.Percentage,
			&i.SinceDate,
			&i.UntilDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsByStructure = `-- name: ListUnitsByStructure :many
SELECT id, structure_id, code, type, area_m2, bedrooms, coefficient,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
FROM units
WHERE structure_id = $1
  AND deleted_at IS NULL
ORDER BY code ASC
`

func (q *Queries) ListUnitsByStructure(ctx context.Context, structureID pgtype.UUID) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnitsByStructure, structureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.StructureID,
			&i.Code,
			&i.Type,
			&i.AreaM2,
			&i.Bedrooms,
			&i.Coefficient,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveOutOccupant = `-- name: MoveOutOccupant :exec
UPDATE unit_occupancies
SET move_out_date = $2::date,
    updated_at = now(),
    updated_by = $3,
    version = version + 1
WHERE id = $1
  AND deleted_at IS NULL
  AND move_out_date IS NULL
`

type MoveOutOccupantParams struct {
	ID        pgtype.UUID
	Column2   pgtype.Date
	UpdatedBy pgtype.UUID
}

func (q *Queries) MoveOutOccupant(ctx context.Context, arg MoveOutOccupantParams) error {
	_, err := q.db.Exec(ctx, moveOutOccupant, arg.ID, arg.Column2, arg.UpdatedBy)
	return err
}

const terminateOwnership = `-- name: TerminateOwnership :exec
UPDATE unit_owners
SET until_date = $2::date,
    updated_at = now(),
    updated_by = $3,
    version = version + 1
WHERE id = $1
  AND deleted_at IS NULL
  AND until_date IS NULL
`

type TerminateOwnershipParams struct {
	ID        pgtype.UUID
	Column2   pgtype.Date
	UpdatedBy pgtype.UUID
}

func (q *Queries) TerminateOwnership(ctx context.Context, arg TerminateOwnershipParams) error {
	_, err := q.db.Exec(ctx, terminateOwnership, arg.ID, arg.Column2, arg.UpdatedBy)
	return err
}
