// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package platformiddb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformAdministrator struct {
	ID           pgtype.UUID
	Name         string
	LegalID      *string
	ContactEmail *string
	ContactPhone *string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type PlatformAuditLog struct {
	ID          pgtype.UUID
	ActorUserID pgtype.UUID
	Action      string
	TargetType  *string
	TargetID    pgtype.UUID
	Metadata    []byte
	IP          *netip.Addr
	UserAgent   *string
	CreatedAt   pgtype.Timestamptz
}

type PlatformPushDevice struct {
	ID             pgtype.UUID
	PlatformUserID pgtype.UUID
	DeviceToken    string
	Platform       string
	DeviceLabel    *string
	LastSeenAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type PlatformUser struct {
	ID                  pgtype.UUID
	DocumentType        string
	DocumentNumber      string
	Names               string
	LastNames           string
	Email               string
	Phone               *string
	PhotoUrl            *string
	PasswordHash        string
	MfaSecret           *string
	MfaEnrolledAt       pgtype.Timestamptz
	PublicCode          string
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	LastLoginAt         pgtype.Timestamptz
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
}

type PlatformUserMembership struct {
	ID             pgtype.UUID
	PlatformUserID pgtype.UUID
	TenantID       pgtype.UUID
	Role           string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type PlatformUserMfaRecoveryCode struct {
	ID             pgtype.UUID
	PlatformUserID pgtype.UUID
	CodeHash       string
	UsedAt         pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type PlatformUserSession struct {
	ID               pgtype.UUID
	PlatformUserID   pgtype.UUID
	TokenHash        string
	ParentSessionID  pgtype.UUID
	IP               *netip.Addr
	UserAgent        *string
	IssuedAt         pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	RevocationReason *string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Tenant struct {
	ID              pgtype.UUID
	Slug            string
	DisplayName     string
	DatabaseUrl     string
	Status          string
	Plan            string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ActivatedAt     pgtype.Timestamptz
	SuspendedAt     pgtype.Timestamptz
	AdministratorID pgtype.UUID
	LogoUrl         *string
	PrimaryColor    *string
	Timezone        string
	Country         string
	Currency        string
	ExpectedUnits   *int32
}
