// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_identity.sql

package platformiddb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockMembership = `-- name: BlockMembership :exec
UPDATE platform_user_memberships
SET status = 'blocked',
    updated_at = now()
WHERE platform_user_id = $1
  AND tenant_id = $2
`

type BlockMembershipParams struct {
	PlatformUserID pgtype.UUID
	TenantID       pgtype.UUID
}

func (q *Queries) BlockMembership(ctx context.Context, arg BlockMembershipParams) error {
	_, err := q.db.Exec(ctx, blockMembership, arg.PlatformUserID, arg.TenantID)
	return err
}

const createPlatformUser = `-- name: CreatePlatformUser :one
INSERT INTO platform_users (
    document_type, document_number, names, last_names,
    email, phone, password_hash, public_code, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE($9, 'active'))
RETURNING id, document_type, document_number, names, last_names, email, phone, photo_url, password_hash, mfa_secret, mfa_enrolled_at, public_code, failed_login_attempts, locked_until, last_login_at, status, created_at, updated_at, deleted_at
`

type CreatePlatformUserParams struct {
	DocumentType   string
	DocumentNumber string
	Names          string
	LastNames      string
	Email          string
	Phone          *string
	PasswordHash   string
	PublicCode     string
	Column9        interface{}
}

func (q *Queries) CreatePlatformUser(ctx context.Context, arg CreatePlatformUserParams) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, createPlatformUser,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.Names,
		arg.LastNames,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.PublicCode,
		arg.Column9,
	)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Names,
		&i.LastNames,
		&i.Email,
		&i.Phone,
		&i.PhotoUrl,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnrolledAt,
		&i.PublicCode,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPlatformUserSession = `-- name: CreatePlatformUserSession :one
INSERT INTO platform_user_sessions (
    platform_user_id, token_hash, ip, user_agent, expires_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, platform_user_id, token_hash, parent_session_id, ip, user_agent, issued_at, expires_at, revoked_at, revocation_reason, status, created_at, updated_at
`

type CreatePlatformUserSessionParams struct {
	PlatformUserID pgtype.UUID
	TokenHash      string
	IP             *netip.Addr
	UserAgent      *string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreatePlatformUserSession(ctx context.Context, arg CreatePlatformUserSessionParams) (PlatformUserSession, error) {
	row := q.db.QueryRow(ctx, createPlatformUserSession,
		arg.PlatformUserID,
		arg.TokenHash,
		arg.IP,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i PlatformUserSession
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.TokenHash,
		&i.ParentSessionID,
		&i.IP,
		&i.UserAgent,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, platform_user_id, tenant_id, role, status, created_at, updated_at
FROM platform_user_memberships
WHERE platform_user_id = $1
  AND tenant_id = $2
`

type GetMembershipParams struct {
	PlatformUserID pgtype.UUID
	TenantID       pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (PlatformUserMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.PlatformUserID, arg.TenantID)
	var i PlatformUserMembership
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.TenantID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformUserByDocument = `-- name: GetPlatformUserByDocument :one
SELECT id, document_type, document_number, names, last_names, email, phone, photo_url, password_hash, mfa_secret, mfa_enrolled_at, public_code, failed_login_attempts, locked_until, last_login_at, status, created_at, updated_at, deleted_at
FROM platform_users
WHERE document_type = $1
  AND document_number = $2
  AND deleted_at IS NULL
`

type GetPlatformUserByDocumentParams struct {
	DocumentType   string
	DocumentNumber string
}

func (q *Queries) GetPlatformUserByDocument(ctx context.Context, arg GetPlatformUserByDocumentParams) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getPlatformUserByDocument, arg.DocumentType, arg.DocumentNumber)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Names,
		&i.LastNames,
		&i.Email,
		&i.Phone,
		&i.PhotoUrl,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnrolledAt,
		&i.PublicCode,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlatformUserByEmail = `-- name: GetPlatformUserByEmail :one

SELECT id, document_type, document_number, names, last_names, email, phone, photo_url, password_hash, mfa_secret, mfa_enrolled_at, public_code, failed_login_attempts, locked_until, last_login_at, status, created_at, updated_at, deleted_at
FROM platform_users
WHERE lower(email) = lower($1)
  AND deleted_at IS NULL
`

// Queries del modulo platform_identity (DB central). Sigue ADR 0007.
func (q *Queries) GetPlatformUserByEmail(ctx context.Context, lower string) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getPlatformUserByEmail, lower)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Names,
		&i.LastNames,
		&i.Email,
		&i.Phone,
		&i.PhotoUrl,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnrolledAt,
		&i.PublicCode,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlatformUserByID = `-- name: GetPlatformUserByID :one
SELECT id, document_type, document_number, names, last_names, email, phone, photo_url, password_hash, mfa_secret, mfa_enrolled_at, public_code, failed_login_attempts, locked_until, last_login_at, status, created_at, updated_at, deleted_at
FROM platform_users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetPlatformUserByID(ctx context.Context, id pgtype.UUID) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getPlatformUserByID, id)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Names,
		&i.LastNames,
		&i.Email,
		&i.Phone,
		&i.PhotoUrl,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnrolledAt,
		&i.PublicCode,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlatformUserByPublicCode = `-- name: GetPlatformUserByPublicCode :one
SELECT id, document_type, document_number, names, last_names, email, phone, photo_url, password_hash, mfa_secret, mfa_enrolled_at, public_code, failed_login_attempts, locked_until, last_login_at, status, created_at, updated_at, deleted_at
FROM platform_users
WHERE public_code = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetPlatformUserByPublicCode(ctx context.Context, publicCode string) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getPlatformUserByPublicCode, publicCode)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Names,
		&i.LastNames,
		&i.Email,
		&i.Phone,
		&i.PhotoUrl,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnrolledAt,
		&i.PublicCode,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, platform_user_id, token_hash, parent_session_id, ip, user_agent, issued_at, expires_at, revoked_at, revocation_reason, status, created_at, updated_at
FROM platform_user_sessions
WHERE token_hash = $1
  AND status = 'active'
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (PlatformUserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i PlatformUserSession
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.TokenHash,
		&i.ParentSessionID,
		&i.IP,
		&i.UserAgent,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, display_name, database_url, status, plan, created_at, updated_at, activated_at, suspended_at, administrator_id, logo_url, primary_color, timezone, country, currency, expected_units
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.DatabaseUrl,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.AdministratorID,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Timezone,
		&i.Country,
		&i.Currency,
		&i.ExpectedUnits,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, display_name, database_url, status, plan, created_at, updated_at, activated_at, suspended_at, administrator_id, logo_url, primary_color, timezone, country, currency, expected_units
FROM tenants
WHERE slug = $1
  AND status = 'active'
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.DatabaseUrl,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.AdministratorID,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Timezone,
		&i.Country,
		&i.Currency,
		&i.ExpectedUnits,
	)
	return i, err
}

const hasMembership = `-- name: HasMembership :one
SELECT EXISTS(
    SELECT 1 FROM platform_user_memberships m
    JOIN tenants t ON t.id = m.tenant_id
    WHERE m.platform_user_id = $1
      AND t.slug = $2
      AND m.status = 'active'
      AND t.status = 'active'
) AS has_access
`

type HasMembershipParams struct {
	PlatformUserID pgtype.UUID
	Slug           string
}

func (q *Queries) HasMembership(ctx context.Context, arg HasMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMembership, arg.PlatformUserID, arg.Slug)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const incrementFailedLogin = `-- name: IncrementFailedLogin :one
UPDATE platform_users
SET failed_login_attempts = failed_login_attempts + 1,
    locked_until = CASE
        WHEN failed_login_attempts + 1 >= 5 THEN now() + INTERVAL '15 minutes'
        ELSE locked_until
    END,
    updated_at = now()
WHERE id = $1
RETURNING failed_login_attempts, locked_until
`

type IncrementFailedLoginRow struct {
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
}

func (q *Queries) IncrementFailedLogin(ctx context.Context, id pgtype.UUID) (IncrementFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, incrementFailedLogin, id)
	var i IncrementFailedLoginRow
	err := row.Scan(&i.FailedLoginAttempts, &i.LockedUntil)
	return i, err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT
    t.id          AS tenant_id,
    t.slug        AS tenant_slug,
    t.display_name AS tenant_name,
    t.logo_url,
    t.primary_color,
    m.role,
    m.status      AS membership_status
FROM platform_user_memberships m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.platform_user_id = $1
  AND m.status = 'active'
  AND t.status = 'active'
ORDER BY t.display_name
LIMIT 50
`

type ListMembershipsForUserRow struct {
	TenantID         pgtype.UUID
	TenantSlug       string
	TenantName       string
	LogoUrl          *string
	PrimaryColor     *string
	Role             string
	MembershipStatus string
}

// Indice central de membresias. La tabla platform_user_memberships
// mantiene una proyeccion liviana del role del usuario en cada tenant.
// La verdad ultima esta en tenant_user_links de cada tenant DB.
func (q *Queries) ListMembershipsForUser(ctx context.Context, platformUserID pgtype.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, platformUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantSlug,
			&i.TenantName,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.Role,
			&i.MembershipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushDevicesForUser = `-- name: ListPushDevicesForUser :many
SELECT id, platform_user_id, device_token, platform, device_label, last_seen_at, created_at, revoked_at
FROM platform_push_devices
WHERE platform_user_id = $1
  AND revoked_at IS NULL
ORDER BY last_seen_at DESC
`

func (q *Queries) ListPushDevicesForUser(ctx context.Context, platformUserID pgtype.UUID) ([]PlatformPushDevice, error) {
	rows, err := q.db.Query(ctx, listPushDevicesForUser, platformUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformPushDevice{}
	for rows.Next() {
		var i PlatformPushDevice
		if err := rows.Scan(
			&i.ID,
			&i.PlatformUserID,
			&i.DeviceToken,
			&i.Platform,
			&i.DeviceLabel,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, display_name, database_url, status, plan, created_at, updated_at, activated_at, suspended_at, administrator_id, logo_url, primary_color, timezone, country, currency, expected_units
FROM tenants
WHERE status != 'archived'
ORDER BY display_name
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.DatabaseUrl,
			&i.Status,
			&i.Plan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivatedAt,
			&i.SuspendedAt,
			&i.AdministratorID,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.Timezone,
			&i.Country,
			&i.Currency,
			&i.ExpectedUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerPushDevice = `-- name: RegisterPushDevice :one
INSERT INTO platform_push_devices (
    platform_user_id, device_token, platform, device_label
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (platform_user_id, device_token) DO UPDATE
    SET last_seen_at = now(),
        revoked_at = NULL,
        platform = EXCLUDED.platform,
        device_label = EXCLUDED.device_label
RETURNING id, platform_user_id, device_token, platform, device_label, last_seen_at, created_at, revoked_at
`

type RegisterPushDeviceParams struct {
	PlatformUserID pgtype.UUID
	DeviceToken    string
	Platform       string
	DeviceLabel    *string
}

func (q *Queries) RegisterPushDevice(ctx context.Context, arg RegisterPushDeviceParams) (PlatformPushDevice, error) {
	row := q.db.QueryRow(ctx, registerPushDevice,
		arg.PlatformUserID,
		arg.DeviceToken,
		arg.Platform,
		arg.DeviceLabel,
	)
	var i PlatformPushDevice
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.DeviceToken,
		&i.Platform,
		&i.DeviceLabel,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE platform_user_sessions
SET status = 'revoked',
    revoked_at = now(),
    revocation_reason = $2,
    updated_at = now()
WHERE platform_user_id = $1
  AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	PlatformUserID   pgtype.UUID
	RevocationReason *string
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.PlatformUserID, arg.RevocationReason)
	return err
}

const revokePushDevice = `-- name: RevokePushDevice :exec
UPDATE platform_push_devices
SET revoked_at = now()
WHERE id = $1
  AND platform_user_id = $2
`

type RevokePushDeviceParams struct {
	ID             pgtype.UUID
	PlatformUserID pgtype.UUID
}

func (q *Queries) RevokePushDevice(ctx context.Context, arg RevokePushDeviceParams) error {
	_, err := q.db.Exec(ctx, revokePushDevice, arg.ID, arg.PlatformUserID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE platform_user_sessions
SET status = 'revoked',
    revoked_at = now(),
    revocation_reason = $2,
    updated_at = now()
WHERE id = $1
`

type RevokeSessionParams struct {
	ID               pgtype.UUID
	RevocationReason *string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevocationReason)
	return err
}

const suspendPlatformUser = `-- name: SuspendPlatformUser :exec
UPDATE platform_users
SET status = 'suspended',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) SuspendPlatformUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, suspendPlatformUser, id)
	return err
}

const updatePlatformUserLastLogin = `-- name: UpdatePlatformUserLastLogin :exec
UPDATE platform_users
SET last_login_at = $2,
    failed_login_attempts = 0,
    locked_until = NULL,
    updated_at = now()
WHERE id = $1
`

type UpdatePlatformUserLastLoginParams struct {
	ID          pgtype.UUID
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) UpdatePlatformUserLastLogin(ctx context.Context, arg UpdatePlatformUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updatePlatformUserLastLogin, arg.ID, arg.LastLoginAt)
	return err
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO platform_user_memberships (
    platform_user_id, tenant_id, role, status
)
VALUES ($1, $2, $3, COALESCE($4, 'active'))
ON CONFLICT (platform_user_id, tenant_id) DO UPDATE
    SET role = EXCLUDED.role,
        status = EXCLUDED.status,
        updated_at = now()
RETURNING id, platform_user_id, tenant_id, role, status, created_at, updated_at
`

type UpsertMembershipParams struct {
	PlatformUserID pgtype.UUID
	TenantID       pgtype.UUID
	Role           string
	Column4        interface{}
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (PlatformUserMembership, error) {
	row := q.db.QueryRow(ctx, upsertMembership,
		arg.PlatformUserID,
		arg.TenantID,
		arg.Role,
		arg.Column4,
	)
	var i PlatformUserMembership
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.TenantID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
