// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package platformiddb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BlockMembership(ctx context.Context, arg BlockMembershipParams) error
	CreatePlatformUser(ctx context.Context, arg CreatePlatformUserParams) (PlatformUser, error)
	CreatePlatformUserSession(ctx context.Context, arg CreatePlatformUserSessionParams) (PlatformUserSession, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (PlatformUserMembership, error)
	GetPlatformUserByDocument(ctx context.Context, arg GetPlatformUserByDocumentParams) (PlatformUser, error)
	// Queries del modulo platform_identity (DB central). Sigue ADR 0007.
	GetPlatformUserByEmail(ctx context.Context, lower string) (PlatformUser, error)
	GetPlatformUserByID(ctx context.Context, id pgtype.UUID) (PlatformUser, error)
	GetPlatformUserByPublicCode(ctx context.Context, publicCode string) (PlatformUser, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (PlatformUserSession, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	HasMembership(ctx context.Context, arg HasMembershipParams) (bool, error)
	IncrementFailedLogin(ctx context.Context, id pgtype.UUID) (IncrementFailedLoginRow, error)
	// Indice central de membresias. La tabla platform_user_memberships
	// mantiene una proyeccion liviana del role del usuario en cada tenant.
	// La verdad ultima esta en tenant_user_links de cada tenant DB.
	ListMembershipsForUser(ctx context.Context, platformUserID pgtype.UUID) ([]ListMembershipsForUserRow, error)
	ListPushDevicesForUser(ctx context.Context, platformUserID pgtype.UUID) ([]PlatformPushDevice, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	RegisterPushDevice(ctx context.Context, arg RegisterPushDeviceParams) (PlatformPushDevice, error)
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error
	RevokePushDevice(ctx context.Context, arg RevokePushDeviceParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	SuspendPlatformUser(ctx context.Context, id pgtype.UUID) error
	UpdatePlatformUserLastLogin(ctx context.Context, arg UpdatePlatformUserLastLoginParams) error
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (PlatformUserMembership, error)
}

var _ Querier = (*Queries)(nil)
