// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package identitydb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (
    user_id, token_hash, parent_session_id,
    ip, user_agent, issued_at, expires_at, status
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    'active'
)
RETURNING id, user_id, token_hash, parent_session_id,
    ip, user_agent, issued_at, expires_at,
    revoked_at, revocation_reason, status,
    created_at, updated_at, created_by, updated_by, version
`

type CreateSessionParams struct {
	UserID          pgtype.UUID
	TokenHash       string
	ParentSessionID pgtype.UUID
	Ip              *netip.Addr
	UserAgent       *string
	IssuedAt        pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ParentSessionID,
		arg.Ip,
		arg.UserAgent,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentSessionID,
		&i.Ip,
		&i.UserAgent,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    document_type, document_number, names, last_names,
    email, phone, password_hash, mfa_secret, mfa_enrolled_at,
    status, created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    COALESCE(NULLIF($10, ''), 'active'),
    $11
)
RETURNING id, document_type, document_number, names, last_names,
    email, phone, password_hash, mfa_secret, mfa_enrolled_at,
    failed_login_attempts, locked_until, last_login_at,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
`

type CreateUserParams struct {
	DocumentType   string
	DocumentNumber string
	Names          string
	LastNames      string
	Email          *string
	Phone          *string
	PasswordHash   string
	MfaSecret      *string
	MfaEnrolledAt  pgtype.Timestamptz
	Column10       interface{}
	CreatedBy      pgtype.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.Names,
		arg.LastNames,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.MfaSecret,
		arg.MfaEnrolledAt,
		arg.Column10,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Names,
		&i.LastNames,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnrolledAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, parent_session_id,
    ip, user_agent, issued_at, expires_at,
    revoked_at, revocation_reason, status,
    created_at, updated_at, created_by, updated_by, version
FROM user_sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentSessionID,
		&i.Ip,
		&i.UserAgent,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, parent_session_id,
    ip, user_agent, issued_at, expires_at,
    revoked_at, revocation_reason, status,
    created_at, updated_at, created_by, updated_by, version
FROM user_sessions
WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentSessionID,
		&i.Ip,
		&i.UserAgent,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}

const getUserByDocument = `-- name: GetUserByDocument :one
SELECT
    id, document_type, document_number, names, last_names,
    email, phone, password_hash, mfa_secret, mfa_enrolled_at,
    failed_login_attempts, locked_until, last_login_at,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
FROM users
WHERE document_type = $1
  AND document_number = $2
  AND deleted_at IS NULL
`

type GetUserByDocumentParams struct {
	DocumentType   string
	DocumentNumber string
}

func (q *Queries) GetUserByDocument(ctx context.Context, arg GetUserByDocumentParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDocument, arg.DocumentType, arg.DocumentNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Names,
		&i.LastNames,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnrolledAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, document_type, document_number, names, last_names,
    email, phone, password_hash, mfa_secret, mfa_enrolled_at,
    failed_login_attempts, locked_until, last_login_at,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Names,
		&i.LastNames,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnrolledAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT
    id, document_type, document_number, names, last_names,
    email, phone, password_hash, mfa_secret, mfa_enrolled_at,
    failed_login_attempts, locked_until, last_login_at,
    status, created_at, updated_at, deleted_at,
    created_by, updated_by, deleted_by, version
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

// Queries del modulo identity.
//
// Convenciones:
//   - Nombres en CamelCase con anotaciones :one|:many|:exec.
//   - SELECTs siempre filtran deleted_at IS NULL para users (soft delete).
//   - No hay columna tenant_id (la base entera es del tenant — CLAUDE.md).
//   - Hashing de refresh token: sha256 hex (calculado en Go).
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Names,
		&i.LastNames,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnrolledAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :one
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1,
    updated_at = now(),
    version = version + 1
WHERE id = $1
  AND deleted_at IS NULL
RETURNING failed_login_attempts
`

func (q *Queries) IncrementFailedAttempts(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailedAttempts, id)
	var failed_login_attempts int32
	err := row.Scan(&failed_login_attempts)
	return failed_login_attempts, err
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, user_id, code_hash, used_at, status,
    created_at, updated_at, created_by, updated_by, version
FROM user_mfa_recovery_codes
WHERE user_id = $1
  AND used_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, userID pgtype.UUID) ([]UserMfaRecoveryCode, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserMfaRecoveryCode{}
	for rows.Next() {
		var i UserMfaRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :exec
UPDATE users
SET locked_until = $2,
    failed_login_attempts = 0,
    updated_at = now(),
    version = version + 1
WHERE id = $1
  AND deleted_at IS NULL
`

type LockUserParams struct {
	ID          pgtype.UUID
	LockedUntil pgtype.Timestamptz
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil)
	return err
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE user_mfa_recovery_codes
SET used_at = $2,
    status = 'used',
    updated_at = now(),
    version = version + 1
WHERE user_id = $1
  AND code_hash = $3
  AND used_at IS NULL
`

type MarkRecoveryCodeUsedParams struct {
	UserID   pgtype.UUID
	UsedAt   pgtype.Timestamptz
	CodeHash string
}

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) error {
	_, err := q.db.Exec(ctx, markRecoveryCodeUsed, arg.UserID, arg.UsedAt, arg.CodeHash)
	return err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE users
SET failed_login_attempts = 0,
    updated_at = now(),
    version = version + 1
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) ResetFailedAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedAttempts, id)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions
SET revoked_at = $2,
    revocation_reason = $3,
    status = 'revoked',
    updated_at = now(),
    version = version + 1
WHERE id = $1
  AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID               pgtype.UUID
	RevokedAt        pgtype.Timestamptz
	RevocationReason *string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt, arg.RevocationReason)
	return err
}

const revokeSessionChain = `-- name: RevokeSessionChain :exec
WITH RECURSIVE chain AS (
    SELECT us0.id AS sess_id, us0.parent_session_id AS sess_parent
    FROM user_sessions us0
    WHERE us0.id = $1
    UNION
    SELECT s.id, s.parent_session_id
    FROM user_sessions s
    JOIN chain c ON s.parent_session_id = c.sess_id
    UNION
    SELECT s.id, s.parent_session_id
    FROM user_sessions s
    JOIN chain c ON s.id = c.sess_parent
)
UPDATE user_sessions us
SET revoked_at = $2,
    revocation_reason = $3,
    status = 'revoked',
    updated_at = now(),
    version = version + 1
FROM chain
WHERE us.id = chain.sess_id
  AND us.revoked_at IS NULL
`

type RevokeSessionChainParams struct {
	ID               pgtype.UUID
	RevokedAt        pgtype.Timestamptz
	RevocationReason *string
}

func (q *Queries) RevokeSessionChain(ctx context.Context, arg RevokeSessionChainParams) error {
	_, err := q.db.Exec(ctx, revokeSessionChain, arg.ID, arg.RevokedAt, arg.RevocationReason)
	return err
}

const unlockUser = `-- name: UnlockUser :exec
UPDATE users
SET locked_until = NULL,
    failed_login_attempts = 0,
    updated_at = now(),
    version = version + 1
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) UnlockUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unlockUser, id)
	return err
}

const updateLastLoginAt = `-- name: UpdateLastLoginAt :exec
UPDATE users
SET last_login_at = $2,
    updated_at = now(),
    version = version + 1
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateLastLoginAtParams struct {
	ID          pgtype.UUID
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) UpdateLastLoginAt(ctx context.Context, arg UpdateLastLoginAtParams) error {
	_, err := q.db.Exec(ctx, updateLastLoginAt, arg.ID, arg.LastLoginAt)
	return err
}
