// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (UserSession, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (UserSession, error)
	GetUserByDocument(ctx context.Context, arg GetUserByDocumentParams) (User, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	// Queries del modulo identity.
	//
	// Convenciones:
	//   * Nombres en CamelCase con anotaciones :one|:many|:exec.
	//   * SELECTs siempre filtran deleted_at IS NULL para users (soft delete).
	//   * No hay columna tenant_id (la base entera es del tenant — CLAUDE.md).
	//   * Hashing de refresh token: sha256 hex (calculado en Go).
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	IncrementFailedAttempts(ctx context.Context, id pgtype.UUID) (int32, error)
	ListUnusedRecoveryCodes(ctx context.Context, userID pgtype.UUID) ([]UserMfaRecoveryCode, error)
	LockUser(ctx context.Context, arg LockUserParams) error
	MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) error
	ResetFailedAttempts(ctx context.Context, id pgtype.UUID) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeSessionChain(ctx context.Context, arg RevokeSessionChainParams) error
	UnlockUser(ctx context.Context, id pgtype.UUID) error
	UpdateLastLoginAt(ctx context.Context, arg UpdateLastLoginAtParams) error
}

var _ Querier = (*Queries)(nil)
