// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package penaltiesdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PenaltyCatalog struct {
	ID                       pgtype.UUID
	Code                     string
	Name                     string
	Description              *string
	DefaultSanctionType      string
	BaseAmount               pgtype.Numeric
	RecurrenceMultiplier     pgtype.Numeric
	RecurrenceCapMultiplier  pgtype.Numeric
	RequiresCouncilThreshold pgtype.Numeric
	Status                   string
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	DeletedAt                pgtype.Timestamptz
	CreatedBy                pgtype.UUID
	UpdatedBy                pgtype.UUID
	DeletedBy                pgtype.UUID
	Version                  int32
}

type Penalty struct {
	ID                      pgtype.UUID
	CatalogID               pgtype.UUID
	DebtorUserID            pgtype.UUID
	UnitID                  pgtype.UUID
	SourceIncidentID        pgtype.UUID
	SanctionType            string
	Amount                  pgtype.Numeric
	Reason                  string
	ImposedByUserID         pgtype.UUID
	NotifiedAt              pgtype.Timestamptz
	AppealDeadlineAt        pgtype.Timestamptz
	ConfirmedAt             pgtype.Timestamptz
	SettledAt               pgtype.Timestamptz
	DismissedAt             pgtype.Timestamptz
	CancelledAt             pgtype.Timestamptz
	RequiresCouncilApproval bool
	CouncilApprovedByUserID pgtype.UUID
	CouncilApprovedAt       pgtype.Timestamptz
	IdempotencyKey          *string
	Status                  string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	CreatedBy               pgtype.UUID
	UpdatedBy               pgtype.UUID
	DeletedBy               pgtype.UUID
	Version                 int32
}

type PenaltyAppeal struct {
	ID                pgtype.UUID
	PenaltyID         pgtype.UUID
	SubmittedByUserID pgtype.UUID
	SubmittedAt       pgtype.Timestamptz
	Grounds           string
	ResolvedByUserID  pgtype.UUID
	ResolvedAt        pgtype.Timestamptz
	Resolution        *string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
	DeletedBy         pgtype.UUID
	Version           int32
}

type PenaltyStatusHistory struct {
	ID                   pgtype.UUID
	PenaltyID            pgtype.UUID
	FromStatus           *string
	ToStatus             string
	TransitionedByUserID pgtype.UUID
	TransitionedAt       pgtype.Timestamptz
	Notes                *string
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedBy            pgtype.UUID
	UpdatedBy            pgtype.UUID
}

type PenaltyOutboxEvent struct {
	ID             pgtype.UUID
	PenaltyID      pgtype.UUID
	EventType      string
	Payload        []byte
	IdempotencyKey *string
	CreatedAt      pgtype.Timestamptz
	NextAttemptAt  pgtype.Timestamptz
	Attempts       int32
	DeliveredAt    pgtype.Timestamptz
	LastError      *string
}
