// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: penalties.sql

package penaltiesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ---------------------------------------------------------------------------
// penalty_catalog
// ---------------------------------------------------------------------------

const createPenaltyCatalogEntry = `-- name: CreatePenaltyCatalogEntry :one
INSERT INTO penalty_catalog (
    code, name, description, default_sanction_type,
    base_amount, recurrence_multiplier, recurrence_cap_multiplier,
    requires_council_threshold, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'active', $9, $9
)
RETURNING id, code, name, description, default_sanction_type,
          base_amount, recurrence_multiplier, recurrence_cap_multiplier,
          requires_council_threshold, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreatePenaltyCatalogEntryParams struct {
	Code                     string
	Name                     string
	Description              *string
	DefaultSanctionType      string
	BaseAmount               pgtype.Numeric
	RecurrenceMultiplier     pgtype.Numeric
	RecurrenceCapMultiplier  pgtype.Numeric
	RequiresCouncilThreshold pgtype.Numeric
	CreatedBy                pgtype.UUID
}

func (q *Queries) CreatePenaltyCatalogEntry(ctx context.Context, arg CreatePenaltyCatalogEntryParams) (PenaltyCatalog, error) {
	row := q.db.QueryRow(ctx, createPenaltyCatalogEntry,
		arg.Code, arg.Name, arg.Description, arg.DefaultSanctionType,
		arg.BaseAmount, arg.RecurrenceMultiplier, arg.RecurrenceCapMultiplier,
		arg.RequiresCouncilThreshold, arg.CreatedBy,
	)
	var i PenaltyCatalog
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Description,
		&i.DefaultSanctionType,
		&i.BaseAmount, &i.RecurrenceMultiplier, &i.RecurrenceCapMultiplier,
		&i.RequiresCouncilThreshold, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getPenaltyCatalogByID = `-- name: GetPenaltyCatalogByID :one
SELECT id, code, name, description, default_sanction_type,
       base_amount, recurrence_multiplier, recurrence_cap_multiplier,
       requires_council_threshold, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM penalty_catalog
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetPenaltyCatalogByID(ctx context.Context, id pgtype.UUID) (PenaltyCatalog, error) {
	row := q.db.QueryRow(ctx, getPenaltyCatalogByID, id)
	var i PenaltyCatalog
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Description,
		&i.DefaultSanctionType,
		&i.BaseAmount, &i.RecurrenceMultiplier, &i.RecurrenceCapMultiplier,
		&i.RequiresCouncilThreshold, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listPenaltyCatalog = `-- name: ListPenaltyCatalog :many
SELECT id, code, name, description, default_sanction_type,
       base_amount, recurrence_multiplier, recurrence_cap_multiplier,
       requires_council_threshold, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM penalty_catalog
 WHERE deleted_at IS NULL
 ORDER BY code ASC
`

func (q *Queries) ListPenaltyCatalog(ctx context.Context) ([]PenaltyCatalog, error) {
	rows, err := q.db.Query(ctx, listPenaltyCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyCatalog
	for rows.Next() {
		var i PenaltyCatalog
		if err := rows.Scan(
			&i.ID, &i.Code, &i.Name, &i.Description,
			&i.DefaultSanctionType,
			&i.BaseAmount, &i.RecurrenceMultiplier, &i.RecurrenceCapMultiplier,
			&i.RequiresCouncilThreshold, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePenaltyCatalogEntry = `-- name: UpdatePenaltyCatalogEntry :one
UPDATE penalty_catalog
   SET code                       = $1,
       name                       = $2,
       description                = $3,
       default_sanction_type      = $4,
       base_amount                = $5,
       recurrence_multiplier      = $6,
       recurrence_cap_multiplier  = $7,
       requires_council_threshold = $8,
       status                     = $9,
       updated_at                 = now(),
       updated_by                 = $10,
       version                    = version + 1
 WHERE id = $11
   AND version = $12
   AND deleted_at IS NULL
RETURNING id, code, name, description, default_sanction_type,
          base_amount, recurrence_multiplier, recurrence_cap_multiplier,
          requires_council_threshold, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdatePenaltyCatalogEntryParams struct {
	NewCode                     string
	NewName                     string
	NewDescription              *string
	NewDefaultSanctionType      string
	NewBaseAmount               pgtype.Numeric
	NewRecurrenceMultiplier     pgtype.Numeric
	NewRecurrenceCapMultiplier  pgtype.Numeric
	NewRequiresCouncilThreshold pgtype.Numeric
	NewStatus                   string
	UpdatedBy                   pgtype.UUID
	ID                          pgtype.UUID
	ExpectedVersion             int32
}

func (q *Queries) UpdatePenaltyCatalogEntry(ctx context.Context, arg UpdatePenaltyCatalogEntryParams) (PenaltyCatalog, error) {
	row := q.db.QueryRow(ctx, updatePenaltyCatalogEntry,
		arg.NewCode, arg.NewName, arg.NewDescription,
		arg.NewDefaultSanctionType,
		arg.NewBaseAmount, arg.NewRecurrenceMultiplier,
		arg.NewRecurrenceCapMultiplier,
		arg.NewRequiresCouncilThreshold, arg.NewStatus,
		arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i PenaltyCatalog
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Description,
		&i.DefaultSanctionType,
		&i.BaseAmount, &i.RecurrenceMultiplier, &i.RecurrenceCapMultiplier,
		&i.RequiresCouncilThreshold, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// ---------------------------------------------------------------------------
// penalties
// ---------------------------------------------------------------------------

const createPenalty = `-- name: CreatePenalty :one
INSERT INTO penalties (
    catalog_id, debtor_user_id, unit_id, source_incident_id,
    sanction_type, amount, reason, imposed_by_user_id,
    requires_council_approval, idempotency_key,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    'drafted', $8, $8
)
RETURNING id, catalog_id, debtor_user_id, unit_id, source_incident_id,
          sanction_type, amount, reason, imposed_by_user_id,
          notified_at, appeal_deadline_at, confirmed_at,
          settled_at, dismissed_at, cancelled_at,
          requires_council_approval,
          council_approved_by_user_id, council_approved_at,
          idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreatePenaltyParams struct {
	CatalogID               pgtype.UUID
	DebtorUserID            pgtype.UUID
	UnitID                  pgtype.UUID
	SourceIncidentID        pgtype.UUID
	SanctionType            string
	Amount                  pgtype.Numeric
	Reason                  string
	ImposedByUserID         pgtype.UUID
	RequiresCouncilApproval bool
	IdempotencyKey          *string
}

func (q *Queries) CreatePenalty(ctx context.Context, arg CreatePenaltyParams) (Penalty, error) {
	row := q.db.QueryRow(ctx, createPenalty,
		arg.CatalogID, arg.DebtorUserID, arg.UnitID, arg.SourceIncidentID,
		arg.SanctionType, arg.Amount, arg.Reason, arg.ImposedByUserID,
		arg.RequiresCouncilApproval, arg.IdempotencyKey,
	)
	var i Penalty
	err := row.Scan(
		&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
		&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
		&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
		&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
		&i.RequiresCouncilApproval,
		&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
		&i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getPenaltyByID = `-- name: GetPenaltyByID :one
SELECT id, catalog_id, debtor_user_id, unit_id, source_incident_id,
       sanction_type, amount, reason, imposed_by_user_id,
       notified_at, appeal_deadline_at, confirmed_at,
       settled_at, dismissed_at, cancelled_at,
       requires_council_approval,
       council_approved_by_user_id, council_approved_at,
       idempotency_key, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM penalties
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetPenaltyByID(ctx context.Context, id pgtype.UUID) (Penalty, error) {
	row := q.db.QueryRow(ctx, getPenaltyByID, id)
	var i Penalty
	err := row.Scan(
		&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
		&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
		&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
		&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
		&i.RequiresCouncilApproval,
		&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
		&i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const listPenalties = `-- name: ListPenalties :many
SELECT id, catalog_id, debtor_user_id, unit_id, source_incident_id,
       sanction_type, amount, reason, imposed_by_user_id,
       notified_at, appeal_deadline_at, confirmed_at,
       settled_at, dismissed_at, cancelled_at,
       requires_council_approval,
       council_approved_by_user_id, council_approved_at,
       idempotency_key, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM penalties
 WHERE deleted_at IS NULL
 ORDER BY created_at DESC
`

func (q *Queries) ListPenalties(ctx context.Context) ([]Penalty, error) {
	rows, err := q.db.Query(ctx, listPenalties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Penalty
	for rows.Next() {
		var i Penalty
		if err := rows.Scan(
			&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
			&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
			&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
			&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
			&i.RequiresCouncilApproval,
			&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
			&i.IdempotencyKey, &i.Status,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
			&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePenaltyStatus = `-- name: UpdatePenaltyStatus :one
UPDATE penalties
   SET status     = $1,
       updated_at = now(),
       updated_by = $2,
       version    = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, catalog_id, debtor_user_id, unit_id, source_incident_id,
          sanction_type, amount, reason, imposed_by_user_id,
          notified_at, appeal_deadline_at, confirmed_at,
          settled_at, dismissed_at, cancelled_at,
          requires_council_approval,
          council_approved_by_user_id, council_approved_at,
          idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdatePenaltyStatusParams struct {
	NewStatus       string
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdatePenaltyStatus(ctx context.Context, arg UpdatePenaltyStatusParams) (Penalty, error) {
	row := q.db.QueryRow(ctx, updatePenaltyStatus,
		arg.NewStatus, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Penalty
	err := row.Scan(
		&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
		&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
		&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
		&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
		&i.RequiresCouncilApproval,
		&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
		&i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const setPenaltyNotified = `-- name: SetPenaltyNotified :one
UPDATE penalties
   SET status             = 'notified',
       notified_at        = $1,
       appeal_deadline_at = $2,
       updated_at         = now(),
       updated_by         = $3,
       version            = version + 1
 WHERE id = $4
   AND version = $5
   AND deleted_at IS NULL
RETURNING id, catalog_id, debtor_user_id, unit_id, source_incident_id,
          sanction_type, amount, reason, imposed_by_user_id,
          notified_at, appeal_deadline_at, confirmed_at,
          settled_at, dismissed_at, cancelled_at,
          requires_council_approval,
          council_approved_by_user_id, council_approved_at,
          idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type SetPenaltyNotifiedParams struct {
	NotifiedAt       pgtype.Timestamptz
	AppealDeadlineAt pgtype.Timestamptz
	UpdatedBy        pgtype.UUID
	ID               pgtype.UUID
	ExpectedVersion  int32
}

func (q *Queries) SetPenaltyNotified(ctx context.Context, arg SetPenaltyNotifiedParams) (Penalty, error) {
	row := q.db.QueryRow(ctx, setPenaltyNotified,
		arg.NotifiedAt, arg.AppealDeadlineAt, arg.UpdatedBy,
		arg.ID, arg.ExpectedVersion,
	)
	var i Penalty
	err := row.Scan(
		&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
		&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
		&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
		&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
		&i.RequiresCouncilApproval,
		&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
		&i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const setPenaltyCouncilApproved = `-- name: SetPenaltyCouncilApproved :one
UPDATE penalties
   SET council_approved_by_user_id = $1,
       council_approved_at         = $2,
       updated_at                  = now(),
       updated_by                  = $3,
       version                     = version + 1
 WHERE id = $4
   AND version = $5
   AND deleted_at IS NULL
RETURNING id, catalog_id, debtor_user_id, unit_id, source_incident_id,
          sanction_type, amount, reason, imposed_by_user_id,
          notified_at, appeal_deadline_at, confirmed_at,
          settled_at, dismissed_at, cancelled_at,
          requires_council_approval,
          council_approved_by_user_id, council_approved_at,
          idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type SetPenaltyCouncilApprovedParams struct {
	CouncilApprovedBy pgtype.UUID
	CouncilApprovedAt pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
	ID                pgtype.UUID
	ExpectedVersion   int32
}

func (q *Queries) SetPenaltyCouncilApproved(ctx context.Context, arg SetPenaltyCouncilApprovedParams) (Penalty, error) {
	row := q.db.QueryRow(ctx, setPenaltyCouncilApproved,
		arg.CouncilApprovedBy, arg.CouncilApprovedAt, arg.UpdatedBy,
		arg.ID, arg.ExpectedVersion,
	)
	var i Penalty
	err := row.Scan(
		&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
		&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
		&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
		&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
		&i.RequiresCouncilApproval,
		&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
		&i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const setPenaltyConfirmed = `-- name: SetPenaltyConfirmed :one
UPDATE penalties
   SET status       = 'confirmed',
       confirmed_at = $1,
       updated_at   = now(),
       updated_by   = $2,
       version      = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, catalog_id, debtor_user_id, unit_id, source_incident_id,
          sanction_type, amount, reason, imposed_by_user_id,
          notified_at, appeal_deadline_at, confirmed_at,
          settled_at, dismissed_at, cancelled_at,
          requires_council_approval,
          council_approved_by_user_id, council_approved_at,
          idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type SetPenaltyConfirmedParams struct {
	ConfirmedAt     pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SetPenaltyConfirmed(ctx context.Context, arg SetPenaltyConfirmedParams) (Penalty, error) {
	row := q.db.QueryRow(ctx, setPenaltyConfirmed,
		arg.ConfirmedAt, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Penalty
	err := row.Scan(
		&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
		&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
		&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
		&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
		&i.RequiresCouncilApproval,
		&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
		&i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const setPenaltySettled = `-- name: SetPenaltySettled :one
UPDATE penalties
   SET status     = 'settled',
       settled_at = $1,
       updated_at = now(),
       updated_by = $2,
       version    = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, catalog_id, debtor_user_id, unit_id, source_incident_id,
          sanction_type, amount, reason, imposed_by_user_id,
          notified_at, appeal_deadline_at, confirmed_at,
          settled_at, dismissed_at, cancelled_at,
          requires_council_approval,
          council_approved_by_user_id, council_approved_at,
          idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type SetPenaltySettledParams struct {
	SettledAt       pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SetPenaltySettled(ctx context.Context, arg SetPenaltySettledParams) (Penalty, error) {
	row := q.db.QueryRow(ctx, setPenaltySettled,
		arg.SettledAt, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Penalty
	err := row.Scan(
		&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
		&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
		&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
		&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
		&i.RequiresCouncilApproval,
		&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
		&i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const setPenaltyDismissed = `-- name: SetPenaltyDismissed :one
UPDATE penalties
   SET status       = 'dismissed',
       dismissed_at = $1,
       updated_at   = now(),
       updated_by   = $2,
       version      = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, catalog_id, debtor_user_id, unit_id, source_incident_id,
          sanction_type, amount, reason, imposed_by_user_id,
          notified_at, appeal_deadline_at, confirmed_at,
          settled_at, dismissed_at, cancelled_at,
          requires_council_approval,
          council_approved_by_user_id, council_approved_at,
          idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type SetPenaltyDismissedParams struct {
	DismissedAt     pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SetPenaltyDismissed(ctx context.Context, arg SetPenaltyDismissedParams) (Penalty, error) {
	row := q.db.QueryRow(ctx, setPenaltyDismissed,
		arg.DismissedAt, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Penalty
	err := row.Scan(
		&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
		&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
		&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
		&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
		&i.RequiresCouncilApproval,
		&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
		&i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const setPenaltyCancelled = `-- name: SetPenaltyCancelled :one
UPDATE penalties
   SET status       = 'cancelled',
       cancelled_at = $1,
       updated_at   = now(),
       updated_by   = $2,
       version      = version + 1
 WHERE id = $3
   AND version = $4
   AND deleted_at IS NULL
RETURNING id, catalog_id, debtor_user_id, unit_id, source_incident_id,
          sanction_type, amount, reason, imposed_by_user_id,
          notified_at, appeal_deadline_at, confirmed_at,
          settled_at, dismissed_at, cancelled_at,
          requires_council_approval,
          council_approved_by_user_id, council_approved_at,
          idempotency_key, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type SetPenaltyCancelledParams struct {
	CancelledAt     pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SetPenaltyCancelled(ctx context.Context, arg SetPenaltyCancelledParams) (Penalty, error) {
	row := q.db.QueryRow(ctx, setPenaltyCancelled,
		arg.CancelledAt, arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i Penalty
	err := row.Scan(
		&i.ID, &i.CatalogID, &i.DebtorUserID, &i.UnitID, &i.SourceIncidentID,
		&i.SanctionType, &i.Amount, &i.Reason, &i.ImposedByUserID,
		&i.NotifiedAt, &i.AppealDeadlineAt, &i.ConfirmedAt,
		&i.SettledAt, &i.DismissedAt, &i.CancelledAt,
		&i.RequiresCouncilApproval,
		&i.CouncilApprovedByUserID, &i.CouncilApprovedAt,
		&i.IdempotencyKey, &i.Status,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const countPenaltyReincidence = `-- name: CountPenaltyReincidence :one
SELECT count(*)::int AS cnt
  FROM penalties
 WHERE debtor_user_id = $1
   AND catalog_id = $2
   AND confirmed_at >= $3
   AND status IN ('confirmed', 'settled')
   AND deleted_at IS NULL
`

func (q *Queries) CountPenaltyReincidence(ctx context.Context, debtorUserID pgtype.UUID, catalogID pgtype.UUID, since pgtype.Timestamptz) (int32, error) {
	row := q.db.QueryRow(ctx, countPenaltyReincidence, debtorUserID, catalogID, since)
	var cnt int32
	err := row.Scan(&cnt)
	return cnt, err
}

// ---------------------------------------------------------------------------
// penalty_appeals
// ---------------------------------------------------------------------------

const createPenaltyAppeal = `-- name: CreatePenaltyAppeal :one
INSERT INTO penalty_appeals (
    penalty_id, submitted_by_user_id, grounds,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, 'submitted', $2, $2
)
RETURNING id, penalty_id, submitted_by_user_id, submitted_at,
          grounds, resolved_by_user_id, resolved_at, resolution,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreatePenaltyAppealParams struct {
	PenaltyID         pgtype.UUID
	SubmittedByUserID pgtype.UUID
	Grounds           string
}

func (q *Queries) CreatePenaltyAppeal(ctx context.Context, arg CreatePenaltyAppealParams) (PenaltyAppeal, error) {
	row := q.db.QueryRow(ctx, createPenaltyAppeal,
		arg.PenaltyID, arg.SubmittedByUserID, arg.Grounds,
	)
	var i PenaltyAppeal
	err := row.Scan(
		&i.ID, &i.PenaltyID, &i.SubmittedByUserID, &i.SubmittedAt,
		&i.Grounds, &i.ResolvedByUserID, &i.ResolvedAt, &i.Resolution,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getPenaltyAppealByID = `-- name: GetPenaltyAppealByID :one
SELECT id, penalty_id, submitted_by_user_id, submitted_at,
       grounds, resolved_by_user_id, resolved_at, resolution,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM penalty_appeals
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetPenaltyAppealByID(ctx context.Context, id pgtype.UUID) (PenaltyAppeal, error) {
	row := q.db.QueryRow(ctx, getPenaltyAppealByID, id)
	var i PenaltyAppeal
	err := row.Scan(
		&i.ID, &i.PenaltyID, &i.SubmittedByUserID, &i.SubmittedAt,
		&i.Grounds, &i.ResolvedByUserID, &i.ResolvedAt, &i.Resolution,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const getActiveAppealByPenaltyID = `-- name: GetActiveAppealByPenaltyID :one
SELECT id, penalty_id, submitted_by_user_id, submitted_at,
       grounds, resolved_by_user_id, resolved_at, resolution,
       status, created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM penalty_appeals
 WHERE penalty_id = $1
   AND status IN ('submitted', 'under_review')
   AND deleted_at IS NULL
 LIMIT 1
`

func (q *Queries) GetActiveAppealByPenaltyID(ctx context.Context, penaltyID pgtype.UUID) (PenaltyAppeal, error) {
	row := q.db.QueryRow(ctx, getActiveAppealByPenaltyID, penaltyID)
	var i PenaltyAppeal
	err := row.Scan(
		&i.ID, &i.PenaltyID, &i.SubmittedByUserID, &i.SubmittedAt,
		&i.Grounds, &i.ResolvedByUserID, &i.ResolvedAt, &i.Resolution,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

const resolvePenaltyAppeal = `-- name: ResolvePenaltyAppeal :one
UPDATE penalty_appeals
   SET resolved_by_user_id = $1,
       resolved_at         = now(),
       resolution          = $2,
       status              = $3,
       updated_at          = now(),
       updated_by          = $4,
       version             = version + 1
 WHERE id = $5
   AND version = $6
   AND deleted_at IS NULL
RETURNING id, penalty_id, submitted_by_user_id, submitted_at,
          grounds, resolved_by_user_id, resolved_at, resolution,
          status, created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type ResolvePenaltyAppealParams struct {
	ResolvedBy      pgtype.UUID
	Resolution      string
	NewStatus       string
	UpdatedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) ResolvePenaltyAppeal(ctx context.Context, arg ResolvePenaltyAppealParams) (PenaltyAppeal, error) {
	row := q.db.QueryRow(ctx, resolvePenaltyAppeal,
		arg.ResolvedBy, arg.Resolution, arg.NewStatus,
		arg.UpdatedBy, arg.ID, arg.ExpectedVersion,
	)
	var i PenaltyAppeal
	err := row.Scan(
		&i.ID, &i.PenaltyID, &i.SubmittedByUserID, &i.SubmittedAt,
		&i.Grounds, &i.ResolvedByUserID, &i.ResolvedAt, &i.Resolution,
		&i.Status, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		&i.CreatedBy, &i.UpdatedBy, &i.DeletedBy, &i.Version,
	)
	return i, err
}

// ---------------------------------------------------------------------------
// penalty_status_history
// ---------------------------------------------------------------------------

const recordPenaltyStatusHistory = `-- name: RecordPenaltyStatusHistory :one
INSERT INTO penalty_status_history (
    penalty_id, from_status, to_status,
    transitioned_by_user_id, notes,
    status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5,
    'recorded', $4, $4
)
RETURNING id, penalty_id, from_status, to_status,
          transitioned_by_user_id, transitioned_at, notes,
          status, created_at, updated_at,
          created_by, updated_by
`

type RecordPenaltyStatusHistoryParams struct {
	PenaltyID            pgtype.UUID
	FromStatus           *string
	ToStatus             string
	TransitionedByUserID pgtype.UUID
	Notes                *string
}

func (q *Queries) RecordPenaltyStatusHistory(ctx context.Context, arg RecordPenaltyStatusHistoryParams) (PenaltyStatusHistory, error) {
	row := q.db.QueryRow(ctx, recordPenaltyStatusHistory,
		arg.PenaltyID, arg.FromStatus, arg.ToStatus,
		arg.TransitionedByUserID, arg.Notes,
	)
	var i PenaltyStatusHistory
	err := row.Scan(
		&i.ID, &i.PenaltyID, &i.FromStatus, &i.ToStatus,
		&i.TransitionedByUserID, &i.TransitionedAt, &i.Notes,
		&i.Status, &i.CreatedAt, &i.UpdatedAt,
		&i.CreatedBy, &i.UpdatedBy,
	)
	return i, err
}

const listPenaltyStatusHistory = `-- name: ListPenaltyStatusHistory :many
SELECT id, penalty_id, from_status, to_status,
       transitioned_by_user_id, transitioned_at, notes,
       status, created_at, updated_at,
       created_by, updated_by
  FROM penalty_status_history
 WHERE penalty_id = $1
 ORDER BY transitioned_at DESC
`

func (q *Queries) ListPenaltyStatusHistory(ctx context.Context, penaltyID pgtype.UUID) ([]PenaltyStatusHistory, error) {
	rows, err := q.db.Query(ctx, listPenaltyStatusHistory, penaltyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyStatusHistory
	for rows.Next() {
		var i PenaltyStatusHistory
		if err := rows.Scan(
			&i.ID, &i.PenaltyID, &i.FromStatus, &i.ToStatus,
			&i.TransitionedByUserID, &i.TransitionedAt, &i.Notes,
			&i.Status, &i.CreatedAt, &i.UpdatedAt,
			&i.CreatedBy, &i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ---------------------------------------------------------------------------
// penalty_outbox_events
// ---------------------------------------------------------------------------

const enqueuePenaltyOutboxEvent = `-- name: EnqueuePenaltyOutboxEvent :one
INSERT INTO penalty_outbox_events (
    penalty_id, event_type, payload, idempotency_key,
    next_attempt_at, attempts
) VALUES (
    $1, $2, $3, $4, now(), 0
)
RETURNING id, penalty_id, event_type, payload, idempotency_key,
          created_at, next_attempt_at, attempts,
          delivered_at, last_error
`

type EnqueuePenaltyOutboxEventParams struct {
	PenaltyID      pgtype.UUID
	EventType      string
	Payload        []byte
	IdempotencyKey *string
}

func (q *Queries) EnqueuePenaltyOutboxEvent(ctx context.Context, arg EnqueuePenaltyOutboxEventParams) (PenaltyOutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueuePenaltyOutboxEvent,
		arg.PenaltyID, arg.EventType, arg.Payload, arg.IdempotencyKey,
	)
	var i PenaltyOutboxEvent
	err := row.Scan(
		&i.ID, &i.PenaltyID, &i.EventType, &i.Payload, &i.IdempotencyKey,
		&i.CreatedAt, &i.NextAttemptAt, &i.Attempts,
		&i.DeliveredAt, &i.LastError,
	)
	return i, err
}

const lockPendingPenaltyOutboxEvents = `-- name: LockPendingPenaltyOutboxEvents :many
SELECT id, penalty_id, event_type, payload, idempotency_key,
       created_at, next_attempt_at, attempts,
       delivered_at, last_error
  FROM penalty_outbox_events
 WHERE delivered_at IS NULL
   AND next_attempt_at <= now()
 ORDER BY next_attempt_at ASC
 LIMIT $1
 FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockPendingPenaltyOutboxEvents(ctx context.Context, limit int32) ([]PenaltyOutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockPendingPenaltyOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyOutboxEvent
	for rows.Next() {
		var i PenaltyOutboxEvent
		if err := rows.Scan(
			&i.ID, &i.PenaltyID, &i.EventType, &i.Payload, &i.IdempotencyKey,
			&i.CreatedAt, &i.NextAttemptAt, &i.Attempts,
			&i.DeliveredAt, &i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPenaltyOutboxEventDelivered = `-- name: MarkPenaltyOutboxEventDelivered :exec
UPDATE penalty_outbox_events
   SET delivered_at = now(),
       attempts     = attempts + 1,
       last_error   = NULL
 WHERE id = $1
`

func (q *Queries) MarkPenaltyOutboxEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPenaltyOutboxEventDelivered, id)
	return err
}

const markPenaltyOutboxEventFailed = `-- name: MarkPenaltyOutboxEventFailed :exec
UPDATE penalty_outbox_events
   SET attempts        = attempts + 1,
       last_error      = $1,
       next_attempt_at = $2
 WHERE id = $3
`

type MarkPenaltyOutboxEventFailedParams struct {
	LastError     *string
	NextAttemptAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) MarkPenaltyOutboxEventFailed(ctx context.Context, arg MarkPenaltyOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markPenaltyOutboxEventFailed,
		arg.LastError, arg.NextAttemptAt, arg.ID,
	)
	return err
}
