// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package residentialdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Soft-delete: marca la estructura como archived.
	ArchiveStructure(ctx context.Context, arg ArchiveStructureParams) (ResidentialStructure, error)
	// Crea una estructura nueva.
	CreateStructure(ctx context.Context, arg CreateStructureParams) (ResidentialStructure, error)
	// Una estructura por id (solo activas).
	GetStructureByID(ctx context.Context, id pgtype.UUID) (ResidentialStructure, error)
	// Queries del modulo residential_structure (sqlc).
	//
	// Convenciones:
	//   * Listados excluyen filas con deleted_at IS NOT NULL.
	//   * Soft-delete via marcar status='archived' y deleted_at = now().
	//   * Concurrencia optimista: cada update incrementa version y compara
	//     contra el version provisto (WHERE version = $expected).
	// Lista todas las estructuras activas ordenadas por order_index, name.
	ListActiveStructures(ctx context.Context) ([]ResidentialStructure, error)
	// Lista los hijos directos de una estructura padre.
	ListChildStructures(ctx context.Context, parentID pgtype.UUID) ([]ResidentialStructure, error)
	// Actualiza una estructura usando concurrencia optimista. Si la version
	// no coincide o la fila no existe (o esta archivada), la query no
	// devuelve filas y el repo distingue ambos casos.
	UpdateStructure(ctx context.Context, arg UpdateStructureParams) (ResidentialStructure, error)
}

var _ Querier = (*Queries)(nil)
