// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: residential.sql

package residentialdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveStructure = `-- name: ArchiveStructure :one
UPDATE residential_structures
   SET status     = 'archived',
       deleted_at = now(),
       deleted_by = $2,
       updated_at = now(),
       updated_by = $2,
       version    = version + 1
 WHERE id = $1
   AND deleted_at IS NULL
RETURNING id, name, type, parent_id, description, order_index, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type ArchiveStructureParams struct {
	ID        pgtype.UUID
	DeletedBy pgtype.UUID
}

// Soft-delete: marca la estructura como archived.
func (q *Queries) ArchiveStructure(ctx context.Context, arg ArchiveStructureParams) (ResidentialStructure, error) {
	row := q.db.QueryRow(ctx, archiveStructure, arg.ID, arg.DeletedBy)
	var i ResidentialStructure
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Description,
		&i.OrderIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const createStructure = `-- name: CreateStructure :one
INSERT INTO residential_structures (
    name, type, parent_id, description, order_index, status,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, 'active', $6, $6
)
RETURNING id, name, type, parent_id, description, order_index, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type CreateStructureParams struct {
	Name        string
	Type        string
	ParentID    pgtype.UUID
	Description *string
	OrderIndex  int32
	CreatedBy   pgtype.UUID
}

// Crea una estructura nueva.
func (q *Queries) CreateStructure(ctx context.Context, arg CreateStructureParams) (ResidentialStructure, error) {
	row := q.db.QueryRow(ctx, createStructure,
		arg.Name,
		arg.Type,
		arg.ParentID,
		arg.Description,
		arg.OrderIndex,
		arg.CreatedBy,
	)
	var i ResidentialStructure
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Description,
		&i.OrderIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const getStructureByID = `-- name: GetStructureByID :one
SELECT id, name, type, parent_id, description, order_index, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM residential_structures
 WHERE id = $1
   AND deleted_at IS NULL
`

// Una estructura por id (solo activas).
func (q *Queries) GetStructureByID(ctx context.Context, id pgtype.UUID) (ResidentialStructure, error) {
	row := q.db.QueryRow(ctx, getStructureByID, id)
	var i ResidentialStructure
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Description,
		&i.OrderIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}

const listActiveStructures = `-- name: ListActiveStructures :many

SELECT id, name, type, parent_id, description, order_index, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM residential_structures
 WHERE deleted_at IS NULL
 ORDER BY order_index, name
`

// Queries del modulo residential_structure (sqlc).
//
// Convenciones:
//   - Listados excluyen filas con deleted_at IS NOT NULL.
//   - Soft-delete via marcar status='archived' y deleted_at = now().
//   - Concurrencia optimista: cada update incrementa version y compara
//     contra el version provisto (WHERE version = $expected).
//
// Lista todas las estructuras activas ordenadas por order_index, name.
func (q *Queries) ListActiveStructures(ctx context.Context) ([]ResidentialStructure, error) {
	rows, err := q.db.Query(ctx, listActiveStructures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResidentialStructure{}
	for rows.Next() {
		var i ResidentialStructure
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Description,
			&i.OrderIndex,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildStructures = `-- name: ListChildStructures :many
SELECT id, name, type, parent_id, description, order_index, status,
       created_at, updated_at, deleted_at,
       created_by, updated_by, deleted_by, version
  FROM residential_structures
 WHERE parent_id = $1
   AND deleted_at IS NULL
 ORDER BY order_index, name
`

// Lista los hijos directos de una estructura padre.
func (q *Queries) ListChildStructures(ctx context.Context, parentID pgtype.UUID) ([]ResidentialStructure, error) {
	rows, err := q.db.Query(ctx, listChildStructures, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResidentialStructure{}
	for rows.Next() {
		var i ResidentialStructure
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Description,
			&i.OrderIndex,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStructure = `-- name: UpdateStructure :one
UPDATE residential_structures
   SET name        = $1,
       type        = $2,
       parent_id   = $3,
       description = $4,
       order_index = $5,
       updated_at  = now(),
       updated_by  = $6,
       version     = version + 1
 WHERE id = $7
   AND deleted_at IS NULL
   AND version = $8
RETURNING id, name, type, parent_id, description, order_index, status,
          created_at, updated_at, deleted_at,
          created_by, updated_by, deleted_by, version
`

type UpdateStructureParams struct {
	Name        string
	Type        string
	ParentID    pgtype.UUID
	Description *string
	OrderIndex  int32
	UpdatedBy   pgtype.UUID
	ID          pgtype.UUID
	Version     int32
}

// Actualiza una estructura usando concurrencia optimista. Si la version
// no coincide o la fila no existe (o esta archivada), la query no
// devuelve filas y el repo distingue ambos casos.
func (q *Queries) UpdateStructure(ctx context.Context, arg UpdateStructureParams) (ResidentialStructure, error) {
	row := q.db.QueryRow(ctx, updateStructure,
		arg.Name,
		arg.Type,
		arg.ParentID,
		arg.Description,
		arg.OrderIndex,
		arg.UpdatedBy,
		arg.ID,
		arg.Version,
	)
	var i ResidentialStructure
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Description,
		&i.OrderIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Version,
	)
	return i, err
}
