// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notificationsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationTemplate struct {
	ID                  pgtype.UUID
	EventType           string
	Channel             string
	Locale              string
	Subject             *string
	BodyTemplate        string
	ProviderTemplateRef *string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	UpdatedBy           pgtype.UUID
	DeletedBy           pgtype.UUID
	Version             int32
}

type NotificationPreference struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	EventType string
	Channel   string
	Enabled   bool
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	DeletedBy pgtype.UUID
	Version   int32
}

type NotificationConsent struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Channel         string
	ConsentedAt     pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	ConsentProofURL *string
	LegalBasis      *string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	UpdatedBy       pgtype.UUID
	DeletedBy       pgtype.UUID
	Version         int32
}

type NotificationPushToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Platform   string
	Token      string
	LastSeenAt pgtype.Timestamptz
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedBy  pgtype.UUID
	DeletedBy  pgtype.UUID
	Version    int32
}

type NotificationProviderConfig struct {
	ID           pgtype.UUID
	Channel      string
	ProviderName string
	Config       []byte
	IsActive     bool
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedBy    pgtype.UUID
	Version      int32
}

type NotificationOutbox struct {
	ID              pgtype.UUID
	EventType       string
	RecipientUserID pgtype.UUID
	Channel         string
	Payload         []byte
	IdempotencyKey  string
	ScheduledAt     pgtype.Timestamptz
	SentAt          pgtype.Timestamptz
	Attempts        int32
	LastError       *string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	UpdatedBy       pgtype.UUID
	DeletedBy       pgtype.UUID
	Version         int32
}

type NotificationDelivery struct {
	ID                pgtype.UUID
	OutboxID          pgtype.UUID
	ProviderName      string
	ProviderMessageID *string
	ProviderStatus    *string
	DeliveredAt       pgtype.Timestamptz
	FailureReason     *string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
	DeletedBy         pgtype.UUID
}
